#ComLogMgt@Search
--ComLogMgt@SearchSELECT A.MNGT_NO     , A.FLAG     , WORK_USR_ID AS CHANGE_USR     , MAX(B.LOC_NM)||' ['||A.WORK_USR_ID||']' AS CHANGE_USR_NM     , to_char(LOG_YMD,'yyyy-mm-dd hh24:mi:ss') AS CHANGE_DATE  FROM COM_LOG_MST A        LEFT OUTER JOIN CRM_USR_MST B 
               ON A.WORK_USR_ID = B.USR_ID WHERE A.MNGT_NO LIKE '@HBL_NO%'
 [COL_NM]
   AND A.COL_NM IN ('@COL_NM')
 [/COL_NM]GROUP BY A.LOG_YMD,A.MNGT_NO,A.FLAG,A.WORK_USR_ID ORDER BY A.MNGT_NO,A.LOG_YMD
#ComLogMgt@SearchColumn
--ComLogMgt@SearchColumn
WITH W_COM_LOG_MST
AS
(
    SELECT A.COL_NM
         , A.TABLE_NM
      FROM COM_LOG_MST A
     GROUP BY A.COL_NM
            , A.TABLE_NM   
)
SELECT A.COL_NM AS CODE
     , NVL(B.COMMENTS,B.COLUMN_NAME) AS NAME
  FROM W_COM_LOG_MST A
       LEFT OUTER JOIN USER_COL_COMMENTS B
               ON A.TABLE_NM = B.TABLE_NAME
              AND A.COL_NM   = B.COLUMN_NAME
#ComLogMgt@SearchDetail
--ComLogMgt@SearchDetailSELECT A.MNGT_NO     , A.FLAG     , CASE WHEN C.DATA_TYPE = 'NUMBER'             THEN UFN_FORMAT(NVL(A.OLD_VAL,0),'2')            ELSE A.OLD_VAL       END OLD_VAL     , CASE WHEN C.DATA_TYPE = 'NUMBER'             THEN UFN_FORMAT(NVL(A.NEW_VAL,0),'2')            ELSE A.NEW_VAL       END NEW_VAL     , NVL(B.COMMENTS,B.COLUMN_NAME) AS COMMENTS  FROM COM_LOG_MST A        LEFT OUTER JOIN USER_COL_COMMENTS B          ON A.TABLE_NM = B.TABLE_NAME         AND A.COL_NM  = B.COLUMN_NAME        LEFT OUTER JOIN COLS C          ON A.TABLE_NM = C.TABLE_NAME         AND A.COL_NM = C.COLUMN_NAME WHERE A.MNGT_NO = '@HBL_NO'   AND A.LOG_YMD = to_date('@CHANGE_DATE','yyyy-mm-dd hh24:mi:ss')    AND A.WORK_USR_ID = '@CHANGE_USR'
 [COL_NM]
   AND A.COL_NM IN ('@COL_NM')
 [/COL_NM] ORDER BY A.MNGT_NO, LOG_YMD
