#SysSmartHelp@CheckNodeForDelete
Select NODE_ID 	,NODE_TYPE 	,PARENT_NODE_ID 	,TITLE 	,CONTENT 	,INS_USR 	,INS_DATE 	,UPD_USR 	,UPD_DATEFrom SYS_HELP_MSTWhere 	PARENT_NODE_ID = '@NODE_ID' 	AND NODE_TYPE='G'
#SysSmartHelp@DeleteNode
begin	--Delete children	DELETE SYS_HELP_MST 	WHERE PARENT_NODE_ID = '@NODE_ID';		--Delete node itself	DELETE SYS_HELP_MST	WHERE NODE_ID='@NODE_ID';end;
#SysSmartHelp@GetChildNodes
Select NODE_ID 	,NODE_TYPE 	,PARENT_NODE_ID 	,TITLE 	--,CONTENT 				--CONTENT must be retrieved individually	,INS_USR 	,INS_DATE 	,UPD_USR 	,UPD_DATEFrom SYS_HELP_MSTWhere 	PARENT_NODE_ID='@PARENT_NODE_ID'ORDER BY DISPLAY_SEQ, NODE_ID
#SysSmartHelp@GetNewNodeID
SELECT '@NODE_TYPE'||TO_CHAR(SYSDATE,'YYMMDD')||LPAD(cast(NVL(MAX(SUBSTR(NODE_ID,8,4)),0) AS INT) + 1 ,4,'0000') AS NEW_IDFROM SYS_HELP_MSTWHERE SUBSTR(NODE_ID,2,6) = TO_CHAR(SYSDATE,'YYMMDD')
#SysSmartHelp@GetNode
Select *From SYS_HELP_MSTWhere 	NODE_ID = '@NODE_ID' 
#SysSmartHelp@GetNodeOrderInParent
Select 	 A.DISPLAY_SEQ	 ,A.NODE_ID	 ,A.TITLEFrom SYS_HELP_MST AWhere 	A.PARENT_NODE_ID = (SELECT PARENT_NODE_ID FROM SYS_HELP_MST WHERE NODE_ID='@NODE_ID')ORDER BY A.DISPLAY_SEQ, A.NODE_ID
#SysSmartHelp@GetNodeProperties
Select 	 A.NODE_ID 	,A.NODE_TYPE 	,A.TITLE 	,A.INS_USR 	,A.INS_DATE 	,A.UPD_USR 	,A.UPD_DATE	,A.PARENT_NODE_ID 	,B.NODE_TYPE AS PARENT_NODE_TYPE	,B.TITLE AS PARENT_TITLEFrom SYS_HELP_MST A LEFT OUTER JOIN SYS_HELP_MST B ON A.PARENT_NODE_ID = B.NODE_IDWhere 	A.NODE_ID = '@NODE_ID' 
#SysSmartHelp@GetRoots
SELECT * FROM SYS_HELP_MSTWHERE NODE_TYPE='R'
ORDER BY DISPLAY_SEQ
#SysSmartHelp@InsertNode
Insert Into SYS_HELP_MST(	NODE_ID 	,NODE_TYPE 	,PARENT_NODE_ID 	,TITLE 	,CONTENT	,DISPLAY_SEQ	,INS_USR 	,INS_DATE)Values (	'@NODE_ID' 	,'@NODE_TYPE' 	,'@PARENT_NODE_ID' 	,'@TITLE' 	,'@CONTENT' 	,(SELECT NVL(MAX(DISPLAY_SEQ),0)+1 FROM SYS_HELP_MST WHERE PARENT_NODE_ID='@PARENT_NODE_ID')	,'@INS_USR' 	,SYSDATE)
#SysSmartHelp@UpdateNodeContent
declare	cont CLOB;
	cont2 CLOB;
	cont3 CLOB;begincont :=TO_CLOB('@MSG_CONTENT');
cont2 :=TO_CLOB('@MSG_CONTENT2');
cont3 :=TO_CLOB('@MSG_CONTENT3');Update SYS_HELP_MSTSet 	 CONTENT=cont||cont2||cont3	,UPD_USR='@UPD_USR' 	,UPD_DATE= SYSDATEWhere	NODE_ID = '@NODE_ID';end;
#SysSmartHelp@UpdateNodeDisplaySeq
UPDATE SYS_HELP_MST 	SET DISPLAY_SEQ=@DISPLAY_SEQ WHERE	NODE_ID='@NODE_ID'
#SysSmartHelp@UpdateNodeTitle
Update SYS_HELP_MSTSet 	TITLE='@TITLE' 	,UPD_USR='@UPD_USR' 	,UPD_DATE= SYSDATEWhere	NODE_ID = '@NODE_ID'	
