#EdmMainMgt@DeleteStandby
 UPDATE EDM_DOC_MST  SET STATUS   = '0' --대기자료 삭제시 FLAG만 변경 / 최종 휴지통 기능에서 삭제시 DB제거됨"    ,UPD_USER='@UPD_USER'    ,UPD_DT = SYSDATE    ,DBTIMESTAMP=TO_CHAR(SYSTIMESTAMP, 'YYYYMMDD_HH24MISS.FF3')WHERE RCVD_DTTM     = '@RCVD_DTTM'    AND RCVD_FILENAME = '@RCVD_FILENAME'    
#EdmMainMgt@DeleteStandbyMerge
--EdmMainMgt@DeleteStandbyMergeUPDATE EDM_DOC_MST    SET STATUS      = '8' --병합후 삭제     , UPD_USER    = '@USR_ID'     , UPD_DT      = SYSDATE     , DBTIMESTAMP = TO_CHAR(SYSTIMESTAMP, 'YYYYMMDD_HH24MISS.FF3') WHERE RCVD_DTTM     = '@RCVD_DTTM'   AND RCVD_FILENAME = '@RCVD_FILENAME'
#EdmMainMgt@InsertDocument
     INSERT INTO EDM_DOC_MST (             RCVD_DTTM            , RCVD_FILENAME            , RCVD_PATH            , RCVD_FAXNO            , RCVD_SENDER            , STATUS            , EDM_NAME            , EDM_CLS            , EDM_TYP            , EDM_NO            , EDM_SEQ            , EDM_RMK            , EDM_TEAM            , EDM_TPIC            , INS_DT            , INS_USER            , UPD_DT            , UPD_USER            , DBTIMESTAMP     ) VALUES (             '@RCVD_DTTM'             , '@RCVD_FILENAME'            , '@RCVD_PATH'            , '@RCVD_FAXNO'            , '@RCVD_SENDER'            , '@STATUS'            , '@EDM_NAME'            , '@EDM_CLS'            , '@EDM_TYP'            , '@EDM_NO'            , '@EDM_SEQ'            , '@EDM_RMK'            , '@EDM_TEAM'            , '@EDM_TPIC'            , SYSDATE            , '@USR_ID'            , SYSDATE            , '@USR_ID'            , TO_CHAR(SYSTIMESTAMP, 'YYYYMMDD_HH24MISS.FF3')     )    
#EdmMainMgt@InsertStandby
--EdmMainMgt@InsertStandbyINSERT INTO EDM_DOC_MST (         RCVD_DTTM        , RCVD_FILENAME        , RCVD_PATH        , RCVD_FAXNO        , RCVD_SENDER        , STATUS        , EDM_NAME        , EDM_CLS        , EDM_TYP        , EDM_NO        , EDM_SEQ        , EDM_RMK        , EDM_TEAM        , EDM_TPIC        , INS_DT        , INS_USER        , UPD_DT        , UPD_USER        , DBTIMESTAMP ) VALUES (           '@RCVD_DTTM'        , '@RCVD_FILENAME'        , '@RCVD_PATH'        , '@RCVD_FAXNO'        , '@RCVD_SENDER'        , '@STATUS'        , '@EDM_NAME'        , '@EDM_CLS'        , '@EDM_TYP'        , '@EDM_NO'        , '@EDM_SEQ'        , '@EDM_RMK'        , '@EDM_TEAM'        , '@EDM_TPIC'        , SYSDATE        , '@USR_ID'        , SYSDATE        , '@USR_ID'        , TO_CHAR(SYSTIMESTAMP, 'YYYYMMDD_HH24MISS.FF3'))
#EdmMainMgt@Search
--EdmMainMgt@SearchSELECT RCVD_PATH     , RCVD_SENDER     , STATUS     , EDM_CLS     , EDM_TYP     , EDM_NO     , EDM_SEQ     , EDM_TEAM     , TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') AS RCVD_DTTM  FROM EDM_DOC_MST WHERE RCVD_DTTM     = '@RCVD_DTTM'    AND RCVD_FILENAME = '@RCVD_FILENAME'
#EdmMainMgt@SearchRefresh
--EdmMainMgt@SearchRefreshSELECT 'N' AS CHK
     , (DECODE(NVL(EDM_NAME,''),'',              SUBSTR(RCVD_DTTM,1,4) || '-' ||            SUBSTR(RCVD_DTTM,5,2) || '-' ||            SUBSTR(RCVD_DTTM,7,2) || ' ' ||            SUBSTR(RCVD_DTTM,9,2) || ':' ||            SUBSTR(RCVD_DTTM,11,2), EDM_NAME)       ) AS EDM_NAME     , EDM_RMK     , RCVD_SENDER     , RCVD_DTTM     , RCVD_PATH     , RCVD_FILENAME     , EDM_TPIC     , RCVD_FAXNO  FROM EDM_DOC_MST  WHERE 1=1    AND STATUS = '1'    --0. 삭제문서, 1: 대기문서, 9: 등록문서"----콤보박스에 --select-- 표시 추가하면서 필수로 변경--   AND RCVD_FAXNO = '@EDM_TEAM' --부서명(FAXNO)"-- [EDM_TPIC]--   AND EDM_TPIC = '@EDM_TPIC' --P.I.C"-- [/EDM_TPIC]-- [EDM_NAME]--   AND (--         ((DECODE(NVL(EDM_NAME,''),'',  --               SUBSTR(RCVD_DTTM,1,4) || '-' ||--               SUBSTR(RCVD_DTTM,5,2) || '-' ||--               SUBSTR(RCVD_DTTM,7,2) || ' ' ||--               SUBSTR(RCVD_DTTM,9,2) || ':' ||--               SUBSTR(RCVD_DTTM,11,2), EDM_NAME--          )) LIKE '%@EDM_NAME%')--        OR (RCVD_SENDER LIKE '%@EDM_NAME%')--        OR (EDM_RMK     LIKE '%@EDM_NAME%')--       )  --TITLE--  [/EDM_NAME] ORDER BY (DECODE(INS_USER,'FILETOTIF',0 ,1)), RCVD_DTTM DESC    
