#BwsCargoList@SearchCntr
SELECT CNTRNO	 , CNTRTYPE	 , SEAL1	 , SEAL2	 , QTY	 , UNIT	 , WGT	 , CBM	 , PART  FROM MTBL_CNT WHERE WHCD 	= '@WHCD'   AND DELNO 	= '@DELNO'
#BwsCargoList@SearchDo
SELECT DOM.LICENSE_NO
     , DOM.RPNO
     , DOD.QTY
     , DOD.WGT
     , DOM.DO_DT
     , DOM.DO_TYPE
  FROM MTDO_MST DOM
  JOIN MTDO_DTL DOD
    ON DOM.WHCD = DOD.WHCD
   AND DOM.RPNO = DOD.RPNO
 WHERE DOM.WHCD = '@WHCD'
   AND DOM.DELNO = '@DELNO'
   
#BwsCargoList@SearchIsu
SELECT GIM.GINO     , GIM.RPNO AS RPNO     , DOM.LICENSE_NO     , GID.ISSUED_TYPE     , GID.PICK_SD AS QTY     , GID.PICK_WGT AS WGT     , GID.PICK_CBM AS CBM     , GIM.EDI_REMARK     , GIM.SEND_NO
     , GIM.GI_DT  FROM MTGI_MST GIM  JOIN MTGI_DTL GID    ON GIM.WHCD = GID.WHCD   AND GIM.DONO = GID.DONO
  LEFT
  JOIN MTDO_MST DOM
    ON GIM.WHCD = DOM.WHCD
   AND GIM.RPNO = DOM.RPNO WHERE GID.WHCD = '@WHCD'   AND GID.DELNO = '@DELNO'
#BwsCargoList@SearchRcp
SELECT RTRIM(INV.DELNO) DELNO	 , RTRIM(INV.GRNO) GRNO	 , INV.GR_DT	 , INV.GR_TM	 , INV.MRN || '-' || INV.MSN || '-' || INV.HSN AS MRNNO	 , INV.MRN 	 , INV.MSN	 , INV.HSN	 , RTRIM(INV.HBLNO) HBLNO	 , GRM.EDI_REMARK	 , NVL(INV.BUYERNM,GRM.BILL_CUSTNM) AS BUYERNM	 , INV.ETA	 , INV.HATD	 , INV.GOODS_NM	 , INV.BL_QTY AS QTY	 , INV.BL_WGT AS GWT	 , INV.BL_CBM AS CWT	 , INV.GR_QTY AS GR_QTY	 , INV.GR_WGT AS GR_WGT	 , INV.GR_CBM AS GR_CBM	 , BLM.VENDORNM	 , NVL(BLM.IN_TRANS_TERM,SYSDATE) AS IN_TRANS_TERM	 , (SELECT PLT_NO 	      FROM MTGR_DTL	     WHERE WHCD = GRM.WHCD	       AND GRNO = GRM.GRNO) AS PLT_NO	 , BLM.FWDNM	 , BLM.TS_YN	 , (SELECT COUNT(*)          FROM MTBL_CNT BLC	     WHERE BLC.WHCD 	= BLM.WHCD 	       AND BLC.DELNO 	= BLM.DELNO ) AS CNT 	 , BLM.DNG_YN 	 , GRM.GR_RMK AS GR_RMK  	 [V_10] 	 , (SELECT WM_CONCAT(TO_CHAR(CNTRNO))   	      FROM MTBL_CNT BLC 	     WHERE BLC.WHCD 	= BLM.WHCD 	       AND BLC.DELNO 	= BLM.DELNO  	     GROUP BY DELNO) AS CNTRNO 	 [/V_10] 	 [ESSA] 	 , '' AS CNTRNO 	 [/ESSA] 	 , GRM.EDI_SEND_INS_REMARK AS EDI_SEND_INS_REMARK 	 , GRM.EDI_STATUS AS EDI_STATUS 	 , BLM.RECV_TYPE || '.' ||	   (SELECT CD_NM 	      FROM MDM_COM_CODE 	     WHERE GRP_CD	='W03' 	       AND COMN_CD	=BLM.RECV_TYPE) AS RECV_TYPE	 , INV.VESSEL AS VESSEL  FROM MTBL_MST BLM  JOIN MT_INVENTORY INV  	ON BLM.WHCD 	= INV.WHCD   AND BLM.DELNO 	= INV.DELNO
  LEFT  JOIN (SELECT *           FROM MTGR_MST          WHERE GRNO LIKE 'GR%') GRM  	ON INV.WHCD 	= GRM.WHCD   AND INV.GRNO	 	= GRM.GRNO   [CNTRNO]  JOIN (SELECT WHCD, DELNO, MAX(CNTRNO) CNTRNO  	      FROM MTBL_CNT  		 WHERE WHCD 	= '@WHCD'  		   AND CNTRNO 	LIKE '%@REFNO%'  		 GROUP BY WHCD, DELNO) BLC	ON BLM.WHCD 	= BLC.WHCD   AND BLM.DELNO 	= BLC.DELNO	   [/CNTRNO] WHERE INV.WHCD = '@WHCD'   AND INV.SEAAIR <> 'T'   [ORD_YMD]   AND BLM.ETA BETWEEN '@FROM_DT' AND '@TO_DT'   [/ORD_YMD]   [GR_YMD]   AND INV.GR_DT BETWEEN '@FROM_DT' AND '@TO_DT'   [/GR_YMD]   [HBLNO]   AND INV.HBLNO LIKE '%@REFNO%'   [/HBLNO]   [GRNO]   AND INV.GRNO LIKE '%@REFNO%'   [/GRNO]   [SEND_NO]   AND INV.GR_SEND_NO LIKE '%@REFNO%'   [/SEND_NO]   [MRNNO]   AND INV.MRN || '-' || INV.MSN || '-' || INV.HSN LIKE '%@REFNO%'   [/MRNNO]   [BUYER]   AND INV.BUYERCD || INV.BUYERNM LIKE '%@REFNO%'   [/BUYER] ORDER     BY INV.GR_DT DESC     , INV.GR_TM DESC     , INV.GRNO DESC
