#HelpSqlExecuter@SearchSql
--HelpSqlExecuter@SearchSqlSELECT 'N' AS CHK      ,SQL_ID      ,TITLE      ,SQL_STR       ,APPLY_SOURCE       ,(SELECT CD_NM FROM MDM_COM_CODE WHERE GRP_CD = 'H01' AND  COMN_CD =  APPLY_SOURCE) AS APPLY_SOURCE_NM     FROM SYS_ALTER_TABLE WHERE APPLY_SOURCE = '04' ORDER BY SQL_ID
