#ExternalLogin@AuthCheck
-- Login@AuthCheckSELECT NVL(MAX(ROWNUM),0) AS CNT  FROM MDM_USER_AUTHWHERE USR_ID = '@USR_ID'   AND USE_YN = 'Y'
#ExternalLogin@CheckUser
-- ExternalLogin@CheckUserSELECT   M.USR_ID AS USERID        ,M.USE_YN AS USEYN        ,M.PSWD   AS PASSWORD         ,CASE WHEN M.LOGIN_FAIL_CNT  >= 5               THEN 'Y'              WHEN M.LOGIN_FAIL_CNT  = -1               THEN 'R'              ELSE 'N'          END    AS LOCK_YN        ,CASE WHEN NVL(ADD_MONTHS(M.PSWD_CHG_YMD,NVL((SELECT PWD_CHG_MM												        FROM MDM_OFFICE_MST												       WHERE OFFICE_CD = M.CUST_CD),3))-7,SYSDATE) <= SYSDATE                THEN 'Y'              ELSE 'N'          END    AS CHANGE_PASSFROM MDM_EXT_USR_MST MWHERE M.USR_ID = '@UserID'
#ExternalLogin@GET_DOMAIN_DB_INFO
--This special Sql is for Getting connection string info from the Admin Schema (ELVIS_SYS)SELECT 	   DOMAIN	  ,TNS_NM	  ,USR_ID	  ,USR_PWD	  ,NEW_CUST_YNFROM SYS_CUST_MSTWHERE	UPPER(DOMAIN) = UPPER('@DOMAIN')
#ExternalLogin@GetDmoainList
   SELECT  DOMAIN AS NAME    	   ,TNS_NM AS CODE           [SETOFFICE]    	   ,USR_ID    	   ,USR_PWD           [/SETOFFICE]    FROM SYS_CUST_MST          [SETOFFICE]   WHERE UPPER(DOMAIN) = UPPER('@DOMAIN')          [/SETOFFICE]
#ExternalLogin@RET_USER2
Select A.USR_ID,     A.ENG_NM AS USR_NM,     CASE WHEN A.TEL IS NULL THEN C.TEL_NO ELSE A.TEL END AS USR_TEL,     CASE WHEN A.FAX IS NULL THEN C.FAX_NO ELSE A.FAX END AS USR_FAX,    A.EMAIL AS USR_MAIL,     REPLACE(O.LOC_ADDR, CHR(13), '') AS CO_LOC_ADDR,    REPLACE(O.ENG_ADDR, CHR(13), '') AS CO_ENG_ADDR,    O.OFFICE_NM AS CO_OFFICE_NM,    REPLACE(O.LOC_BANK_INFO, CHR(13), '') AS CO_LOC_BANK,    O.LOCAL_NM AS CO_OFFICE_LOCALNM,    REPLACE(O.FCUR_BANK_INFO, CHR(13), '') AS CO_FCUR_BANK,    A.ORG_CD AS ORG_CD,     O.CURR_CD,     A.ENG_NM||' ['||TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI')||']' AS USR_NM_YMD,     (SELECT DEPT_NM FROM MDM_DEPT_MST  WHERE  DEPT_CD = A.ORG_CD) AS ORG_NM ,    A.LOCAL_NM AS USR_LOCNMFrom MDM_USER_MST A, MDM_OFFICE_MST O,MDM_CUST_MST CWhere A.USR_ID= '@USR_ID' 	AND O.OFFICE_CD = A.OFFICE_CD	AND O.OFFICE_CD = C.CUST_CD(+)
#ExternalLogin@SearchOffice
SELECT        A.OFFICE_NM     , A.LOC_NM     , REPLACE(A.LOC_ADDR,CHR(13)||CHR(10),' ') AS LOC_ADDR     , REPLACE(A.ENG_ADDR,CHR(13)||CHR(10),' ') AS ENG_ADDR     , B.CUST_NM||CHR(13)||CHR(10)||B.BL_ADDR AS BL_ADDR     , A.CURR_CD     , A.CTRY_CD     , NVL((SELECT B.OPT_ITEM1 FROM MDM_COM_CODE  B WHERE B.GRP_CD ='M03' AND COMN_CD = A.CURR_CD),2) AS DCM_POINT     , A.AIR_PORT_CD     , (SELECT LOC_NM FROM MDM_PORT_MST WHERE LOC_CD = A.AIR_PORT_CD ) AS AIR_PORT_NM     , A.SEA_PORT_CD     , (SELECT LOC_NM FROM MDM_PORT_MST WHERE LOC_CD = A.SEA_PORT_CD ) AS SEA_PORT_NM     , A.AIR_BL_PREFIX     , A.SEA_BL_PREFIX     , A.OFFICE_PREFIX     , A.CUSTOMS_CD     , A.FOUND_YEAR     , A.HQ_OFFICE_CD     , A.UPPER_ORG_CD     , B.AGENT_IATA_NO AS AGENT_IATA_CD     , A.LANG_CD     , (SELECT MAX(FARE_CD) FROM MDM_FRT_MST WHERE FARE_GRP_CD = 'AAF') AS AIR_FRT_CD     , (SELECT MAX(FARE_CD) FROM MDM_FRT_MST WHERE FARE_GRP_CD = 'OCF') AS SEA_FRT_CD     , (SELECT MAX(FARE_CD) FROM MDM_FRT_MST WHERE FARE_GRP_CD = 'VAT') AS VAT_FRT_CD     , (SELECT MAX(FARE_NM) FROM MDM_FRT_MST WHERE FARE_GRP_CD = 'VAT') AS VAT_FRT_NM     , A.VAT_PER     , A.CITY_CD     , UFN_TABLE_ITEM('OFFICE_CONFIG',A.OFFICE_CD,'AUTO_SLIP_BUY_TAX','') AS AUTO_SLIP_BY_TAX     , UFN_TABLE_ITEM('OFFICE_CONFIG',A.OFFICE_CD,'AUTO_INVOICE','') AS AUTO_INVOICE     , UFN_TABLE_ITEM('OFFICE_CONFIG',A.OFFICE_CD,'PFM_BY_OP','') AS PFM_BY_OP  FROM MDM_OFFICE_MST  A LEFT OUTER JOIN MDM_CUST_MST B ON A.OFFICE_CD = B.CUST_CD WHERE A.OFFICE_CD= '@OFFICE_CD' 
#ExternalLogin@SearchUser
-- Login@SearchUserSELECT A.USR_ID     , A.ENG_NM     , A.LOC_NM     , A.GEND      , A.HP_NO     , A.TEL_NO     , A.FAX_NO     , A.EMAIL     , UPPER(A.CUST_CD) AS OFFICE_CD     , A.AUTH_TYPE     , A.FIRST_LOAD_FORM     , FIRST_LOAD_FORMFROM MDM_EXT_USR_MST AWHERE USE_YN = 'Y'  AND USR_ID = '@UserID'    
#ExternalLogin@SearchUserFuncAuth
-- Login@SearchUserFuncAuthSELECT SYS_ID     , PGM_ID     , FUNC_ID  FROM (  	SELECT SYS_ID  	     , PGM_ID  	     , FUNC_ID  	     , MIN(USE_YN) AS USE_YN  	  FROM (    		    SELECT SYS_ID		         , PGM_ID		         , FUNC_ID		         , USE_YN		      FROM MDM_USER_AUTH		     WHERE USR_ID = '@UserID'		       AND FUNC_ID <> PGM_ID		       --AND USE_YN = 'Y'		    UNION		    SELECT SYS_ID		         , PGM_ID		         , FUNC_ID		         , USE_YN		      FROM MDM_GRP_AUTH 		     WHERE GRP_ID=(SELECT AUTH_TYPE FROM MDM_USER_MST 		                    WHERE USR_ID = '@UserID') 		       AND FUNC_ID <> PGM_ID 		       AND USE_YN = 'Y' 		) GROUP BY SYS_ID, PGM_ID, FUNC_ID		       ) WHERE USE_YN = 'Y'
#ExternalLogin@SearchUserPgmAuth
-- Login@SearchUserPgmAuthSELECT  SYS_ID      , PGM_ID FROM (		  	SELECT  SYS_ID			      , PGM_ID			      , MIN(USE_YN) AS USE_YN			  FROM (							SELECT SYS_ID 								 , PGM_ID 								 , USE_YN							  FROM MDM_USER_AUTH							 WHERE USR_ID = '@UserID'							   AND PGM_ID = FUNC_ID							  -- AND USE_YN = 'Y'							 GROUP BY  SYS_ID							          ,PGM_ID							          ,USE_YN							UNION ALL							SELECT SYS_ID							     , PGM_ID 							     , USE_YN							  FROM MDM_GRP_AUTH 							 WHERE GRP_ID =(SELECT AUTH_TYPE FROM MDM_USER_MST WHERE USR_ID='@UserID') 							   AND USE_YN='Y'							 GROUP BY SYS_ID							         ,PGM_ID 							         ,USE_YN				   )		  GROUP BY SYS_ID			       ,PGM_ID		)WHERE USE_YN='Y'
#ExternalLogin@UpdateFailCnt
--Login@UpdateFailCntUPDATE MDM_EXT_USR_MST   SET      [FAILED]        LOGIN_FAIL_CNT = LOGIN_FAIL_CNT+1     [/FAILED]     [SUCCESS]         LOGIN_FAIL_CNT = 0     [/SUCCESS]     [UNLOCK]         LOGIN_FAIL_CNT = -1        ,PSWD = UNF_MD5_ENCRYPTION('@PSWD')     [/UNLOCK] WHERE USR_ID='@USR_ID'
