#HelpServerInfoMgt@Delete
--HelpServerInfoMgt@DeleteDELETE   FROM SYS_CUST_MST@@DB_LINK WHERE DOMAIN = '@DB_DOMAIN'
#HelpServerInfoMgt@Insert
--HelpServerInfoMgt@InsertINSERT INTO SYS_CUST_MST@@DB_LINK(   SVC_CD  ,DOMAIN  ,APPLY_SOURCE  ,TNS_NM  ,USR_ID  ,USR_PWD  ,NEW_CUST_YN  ,DB_IP  ,DB_IP_EXT  ,DB_PORT  ,DB_SID  ,CUST_CD  ,CUST_NM  ,CUST_LOC_NM  ,USE_YN  ,TB_CHG_YN  ,DATA_CHK  ,WCF_LOG_YN  ,WEB_IP  ,WEB_IP_EXT
  ,WEB_PORT  ,INS_USR  ,INS_YMD  ,INS_HM  ,UPD_USR  ,UPD_YMD  ,UPD_HM)VALUES (   '@SVC_CD'  ,'@DOMAIN'  ,NVL('@APPLY_SOURCE','01')  ,'@TNS_NM'  ,'@USR_ID'  ,'@USR_PWD'  ,'@NEW_CUST_YN'  ,'@DB_IP'  ,'@DB_IP_EXT'  ,'@DB_PORT'  ,'@DB_SID'  ,'@CUST_CD'  ,'@CUST_NM'  ,'@CUST_LOC_NM'  ,'@USE_YN'  ,'@TB_CHG_YN'  ,'@DATA_CHK'  ,'@WCF_LOG_YN'  ,'@WEB_IP'  ,'@WEB_IP_EXT'  ,'@WEB_PORT'  ,'@INS_USR'  ,TO_CHAR(SYSDATE,'YYYYMMDD')  ,TO_CHAR(SYSDATE,'HH24MISS')  ,'@UPD_USR'  ,TO_CHAR(SYSDATE,'YYYYMMDD')  ,TO_CHAR(SYSDATE,'HH24MISS'))
#HelpServerInfoMgt@Search
--HelpServerInfoMgt@SearchSELECT '' AS TNS_SET      ,'@DB_LINK' AS DB_LINK      ,SVC_CD      ,APPLY_SOURCE	  ,DOMAIN	  ,DOMAIN AS DB_DOMAIN	  ,TNS_NM	  ,USR_ID	  ,USR_PWD	  ,NEW_CUST_YN	  ,DB_IP	  ,DB_IP_EXT	  ,DB_PORT	  ,DB_SID	  ,CUST_CD	  ,CUST_NM	  ,CUST_LOC_NM	  ,USE_YN	  ,TB_CHG_YN	  ,DATA_CHK	  ,WCF_LOG_YN	  ,WEB_IP	  ,WEB_IP_EXT
	  ,WEB_PORT	  ,INS_USR	  ,INS_YMD	  ,INS_HM	  ,UPD_USR	  ,UPD_YMD	  ,UPD_HM  FROM SYS_CUST_MST@@DB_LINK WHERE 1=1[SEARCH_KEY]   AND ( 1 != 1   OR DOMAIN LIKE '%@SEARCH_KEY%'   OR TNS_NM LIKE '%@SEARCH_KEY%'   OR USR_ID LIKE '%@SEARCH_KEY%'   OR DB_IP LIKE '%@SEARCH_KEY%' 	   OR CUST_CD LIKE '%@SEARCH_KEY%'   OR CUST_NM LIKE '%@SEARCH_KEY%'   OR CUST_LOC_NM LIKE '%@SEARCH_KEY%'  )[/SEARCH_KEY][SVC_CD]  AND SVC_CD = '@SVC_CD'[/SVC_CD][DOMAIN]  AND DOMAIN IN ('@DOMAIN')[/DOMAIN] ORDER BY DOMAIN
#HelpServerInfoMgt@Update
--HelpServerInfoMgt@UpdateUPDATE SYS_CUST_MST@@DB_LINK   SET DOMAIN = '@DOMAIN'      ,APPLY_SOURCE = '@APPLY_SOURCE'      ,SVC_CD = '@SVC_CD'      ,TNS_NM = '@TNS_NM'      ,USR_ID = '@USR_ID'      ,USR_PWD = '@USR_PWD'      ,NEW_CUST_YN = '@NEW_CUST_YN'      ,DB_IP = '@DB_IP'      ,DB_IP_EXT = '@DB_IP_EXT'      ,DB_PORT = '@DB_PORT'      ,DB_SID = '@DB_SID'      ,CUST_CD = '@CUST_CD'      ,CUST_NM = '@CUST_NM'      ,CUST_LOC_NM = '@CUST_LOC_NM'      ,USE_YN = '@USE_YN'      ,TB_CHG_YN = '@TB_CHG_YN'      ,DATA_CHK = '@DATA_CHK'      ,WCF_LOG_YN = '@WCF_LOG_YN'      ,WEB_IP = '@WEB_IP'      ,WEB_IP_EXT = '@WEB_IP_EXT'      ,WEB_PORT = '@WEB_PORT'      ,UPD_USR = '@UPD_USR'      ,UPD_YMD = TO_CHAR(SYSDATE,'YYYYMMDD')      ,UPD_HM = TO_CHAR(SYSDATE,'HH24MISS') WHERE DOMAIN = '@DB_DOMAIN'
