#MdmExrateMgt@Check
--MdmExrateMgt@CheckSELECT BASE_CURR   FROM MDM_EX_RATE WHERE OFFICE_CD 	= '@OFFICE_CD'		AND	BASE_CURR	= '@BASE_CURR'    		AND EXRT_YMD 	= '@CURR_DATE'
#MdmExrateMgt@CN_Copy
--MdmExrateMgt@CopyBEGIN	    DELETE MDM_EX_RATE WHERE  OFFICE_CD 	= '@OFFICE_CD'			AND	BASE_CURR	= '@BASE_CURR' 	   		AND EXRT_YMD 	= '@CURR_DATE';   		INSERT INTO MDM_EX_RATE(			OFFICE_CD		, BASE_CURR		, CURR_CD			, EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT		, CASH_SELLRT	, WIRE_SEND_EXRT	, WIRE_RECV_EXRT	, EXCH_BASERT		  , USD_CONV_RT		, INS_USR		, INS_YMD			, INS_HM			, UPD_USR		  , UPD_YMD			, UPD_HM		  )	 SELECT OFFICE_CD	 	  , BASE_CURR	 	  , CURR_CD	 	  , '@CURR_DATE'	 	  , CURR_UNIT	 	  ,	CASH_BUYRT	 	  , CASH_SELLRT	 	  , WIRE_SEND_EXRT	 	  , WIRE_RECV_EXRT	 	  , EXCH_BASERT	 	  , USD_CONV_RT	 	  , '@USR_ID'	 	  , UFN_DATE_FORMAT('DATE')	 	  , UFN_DATE_FORMAT('TIME')	 	  , '@USR_ID'		  , UFN_DATE_FORMAT('DATE')		  , UFN_DATE_FORMAT('TIME') 	   FROM MDM_EX_RATE  	  WHERE OFFICE_CD 	= '@OFFICE_CD'		AND	BASE_CURR	= '@BASE_CURR'    		AND EXRT_YMD 	= '@EXRT_YMD';END ;
#MdmExrateMgt@Copy
--MdmExrateMgt@CopyBEGIN	INSERT INTO MDM_EX_RATE(			OFFICE_CD		, BASE_CURR		, CURR_CD			, EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT		, CASH_SELLRT	, WIRE_SEND_EXRT	, WIRE_RECV_EXRT	, EXCH_BASERT		  , USD_CONV_RT		, INS_USR		, INS_YMD			, INS_HM			, UPD_USR		  , UPD_YMD			, UPD_HM        		  )	 SELECT OFFICE_CD	 	  , BASE_CURR	 	  , CURR_CD	 	  , '@CURR_DATE'	 	  , CURR_UNIT	 	  ,	CASH_BUYRT	 	  , CASH_SELLRT	 	  , WIRE_SEND_EXRT	 	  , WIRE_RECV_EXRT	 	  , EXCH_BASERT	 	  , USD_CONV_RT	 	  , '@USR_ID'	 	  , UFN_DATE_FORMAT('DATE')	 	  , UFN_DATE_FORMAT('TIME')	 	  , '@USR_ID'		  , UFN_DATE_FORMAT('DATE')		  , UFN_DATE_FORMAT('TIME') 	   FROM MDM_EX_RATE  	  WHERE OFFICE_CD 	= '@OFFICE_CD'		AND	BASE_CURR	= '@BASE_CURR'    		AND EXRT_YMD 	= '@EXRT_YMD';   			INSERT INTO MDM_EX_RATE2(			OFFICE_CD		, BASE_CURR		, CURR_CD			, EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT		, CASH_SELLRT	, WIRE_SEND_EXRT	, WIRE_RECV_EXRT	, EXCH_BASERT		  , USD_CONV_RT		, SEQ		  , INS_USR			, INS_YMD		, INS_HM			, UPD_USR		  , UPD_YMD			, UPD_HM        		  )	 SELECT OFFICE_CD	 	  , BASE_CURR	 	  , CURR_CD	 	  , '@CURR_DATE'	 	  , CURR_UNIT	 	  ,	CASH_BUYRT	 	  , CASH_SELLRT	 	  , WIRE_SEND_EXRT	 	  , WIRE_RECV_EXRT	 	  , EXCH_BASERT	 	  , USD_CONV_RT	 	  , SEQ	 	  , '@USR_ID'	 	  , UFN_DATE_FORMAT('DATE')	 	  , UFN_DATE_FORMAT('TIME')	 	  , '@USR_ID'		  , UFN_DATE_FORMAT('DATE')		  , UFN_DATE_FORMAT('TIME') 	   FROM MDM_EX_RATE2  	  WHERE OFFICE_CD 	= '@OFFICE_CD'		AND	BASE_CURR	= '@BASE_CURR'    		AND EXRT_YMD 	= '@EXRT_YMD';   		   		END ;
#MdmExrateMgt@Delete
--MdmExrateMgt@DeleteDELETE MDM_EX_RATE WHERE OFFICE_CD	= '@OFFICE_CD'   AND BASE_CURR 	= '@BASE_CURR'   AND CURR_CD 		= '@CURR_CD'   AND EXRT_YMD 	= '@EXRT_YMD'
#MdmExrateMgt@Delete2
--MdmExrateMgt@Delete2DELETE MDM_EX_RATE2 WHERE OFFICE_CD	= '@OFFICE_CD'   AND BASE_CURR 	= '@BASE_CURR'   AND CURR_CD 		= '@CURR_CD'   AND EXRT_YMD 	= '@EXRT_YMD'   AND SEQ			= '@SEQ'
#MdmExrateMgt@DeleteAll
--MdmExrateMgt@DeleteAllBEGIN	DELETE MDM_EX_RATE	 WHERE EXRT_YMD	 = '@EXRT_YMD'	   AND OFFICE_CD = '@OFFICE_CD'	   AND BASE_CURR = '@BASE_CURR';	 	DELETE MDM_EX_RATE2	 WHERE EXRT_YMD	 = '@EXRT_YMD'	   AND OFFICE_CD = '@OFFICE_CD'	   AND BASE_CURR = '@BASE_CURR';   --  AND SEQ 		 = '001';	 END;	    
#MdmExrateMgt@DeleteMonthly
-- MdmExrateMgt@DeleteMonthlyDELETE MDM_MM_EX_RATE WHERE OFFICE_CD	= '@OFFICE_CD'   AND BASE_CURR 	= '@BASE_CURR'   AND CURR_CD 		= '@CURR_CD'   AND EXRT_MM 	= '@EXRT_MM'
#MdmExrateMgt@GetExRate
/* Local Amount Value Search */ -- 2012.01.17SELECT NVL(CASE WHEN '@CURR_CLS' = 'A' THEN A.EXCH_BASERT                WHEN '@CURR_CLS' = 'B' THEN A.CASH_BUYRT	                WHEN '@CURR_CLS' = 'C' THEN A.CASH_SELLRT	                WHEN '@CURR_CLS' = 'D' THEN A.WIRE_SEND_EXRT                WHEN '@CURR_CLS' = 'E' THEN A.WIRE_RECV_EXRT           END, 1) AS EX_RATE,      (SELECT NVL(CASE WHEN '@CURR_CLS' = 'A' THEN B.EXCH_BASERT                       WHEN '@CURR_CLS' = 'B' THEN B.CASH_BUYRT	                       WHEN '@CURR_CLS' = 'C' THEN B.CASH_SELLRT	                       WHEN '@CURR_CLS' = 'D' THEN B.WIRE_SEND_EXRT                       WHEN '@CURR_CLS' = 'E' THEN B.WIRE_RECV_EXRT                  END, 1)        FROM   MDM_EX_RATE B        WHERE  B.BASE_CURR = A.BASE_CURR        AND    B.CURR_CD   = 'USD'        AND    B.EXRT_YMD  = A.EXRT_YMD       AND    B.OFFICE_CD = '@OFFICE_CD') AS USD_EX_RATE,       A.CURR_UNITFROM   MDM_EX_RATE AWHERE  A.BASE_CURR = '@BASE_CURR' --SESSION("Currency")AND    A.CURR_CD   = '@CURR_CD'   --CURR_CD  AND    A.EXRT_YMD  = '@EXRT_YMD'AND    A.OFFICE_CD = '@OFFICE_CD' 
#MdmExrateMgt@Holiday
-- MdmExrateMgt@HolidayWITH H AS (	SELECT *	  FROM CRM_HOLIDAYS	 WHERE 1=1	   AND HD_YMD BETWEEN TO_DATE('@EXRT_YMD', 'yyyyMMdd') AND TO_DATE('@EXRT_YMD', 'yyyyMMdd') + 4)SELECT *  FROM (	SELECT (SELECT CASE WHEN TO_DATE(MIN(HD_YMD), 'yyyyMMdd') - 1 = TO_DATE('@EXRT_YMD', 'yyyyMMdd')	                    THEN 1	                    ELSE 0	               END 	          FROM CRM_HOLIDAYS 	         WHERE HD_YMD > '@EXRT_YMD') AS MULTI	     , H.*	  FROM H)WHERE MULTI = 1
#MdmExrateMgt@Insert
--MdmExrateMgt@InsertBEGIN  	INSERT INTO MDM_EX_RATE(			OFFICE_CD	    	, BASE_CURR		, CURR_CD					  , EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT			, CASH_SELLRT			  , WIRE_SEND_EXRT		, WIRE_RECV_EXRT			  , EXCH_BASERT         , USD_CONV_RT	, RMK			  , INS_USR				, INS_YMD			, INS_HM					  , UPD_USR  			, UPD_YMD			, UPD_HM			  )     VALUES (			'@OFFICE_CD'			, '@BASE_CURR'			, '@CURR_CD'					      , '@EXRT_YMD'				, @CURR_UNIT		  , @CASH_BUYRT				, @CASH_SELLRT		  , @WIRE_SEND_EXRT			, @WIRE_RECV_EXRT		  , @EXCH_BASERT		  , @USD_CONV_RT            , '@RMK'		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	 	, UFN_DATE_FORMAT('TIME')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	    , UFN_DATE_FORMAT('TIME')		  ) ;		  END ;
#MdmExrateMgt@Insert2
--MdmExrateMgt@Insert2BEGIN  	INSERT INTO MDM_EX_RATE2(			OFFICE_CD	    	, BASE_CURR		, CURR_CD					  , EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT			, CASH_SELLRT			  , WIRE_SEND_EXRT		, WIRE_RECV_EXRT			  , EXCH_BASERT         		  , USD_CONV_RT			, RMK				, SEQ		  , INS_USR				, INS_YMD			, INS_HM					  , UPD_USR  			, UPD_YMD			, UPD_HM			  )     VALUES (			'@OFFICE_CD'			, '@BASE_CURR'			, '@CURR_CD'					      , '@EXRT_YMD'				, @CURR_UNIT		  , @CASH_BUYRT				, @CASH_SELLRT		  , @WIRE_SEND_EXRT			, @WIRE_RECV_EXRT		  , @EXCH_BASERT		  , @USD_CONV_RT            , '@RMK'					, '@SEQ'		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	 	, UFN_DATE_FORMAT('TIME')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	    , UFN_DATE_FORMAT('TIME')		  ) ;		  END ;
#MdmExrateMgt@InsertAS
-- MdmExrateMgt@InsertAS    INSERT INTO CRM_AS_MST (            INS_USR      , INS_YMD          , INS_HM          , UPD_USR      , UPD_YMD          , UPD_HM          , REQ_YMD      , REQ_HM          , SYS_ID       , FORM_ID          , MNGT_NO            , REQ_SVC             , CUST_CD           , CONTENT                 , REQ_USR              , TEL_NO             , PROC_TYPE                  , WORK_USR            , PRAR_YMD             , CMPT_YMD                , PRIORITY               , FREE_YN             , REQ_TYPE            , CMPT_RMK           , REQ_SVC2           , UPPER_MNGT_NO                )        VALUES (            'ADMIN'    , TO_CHAR(SYSDATE,'YYYYMMDD'),    TO_CHAR(SYSDATE,'HH24MISS')          , 'ADMIN'    , TO_CHAR(SYSDATE,'YYYYMMDD'),    TO_CHAR(SYSDATE,'HH24MISS')          , TO_CHAR(SYSDATE,'YYYYMMDD')    , TO_CHAR(SYSDATE,'HH24MISS')          , 'ELVIS'    , 'ComRequestMgt'          , '@MNGT_NO'                     ,'Z'                     ,'YJIT'                   ,'@CONTENT'                   ,'ADMIN'                    ,''                      ,'0'                  ,''                 ,''          ,''          ,'0'                  ,'Y'                      ,''                  ,''                 ,'R005'                  ,'@MNGT_NO'                )
#MdmExrateMgt@InsertMonthly
-- MdmExrateMgt@InsertMonthlyBEGIN  	INSERT INTO MDM_MM_EX_RATE(			OFFICE_CD	    	, BASE_CURR		, CURR_CD					  , EXRT_MM			    , CURR_UNIT		  , CASH_BUYRT			, CASH_SELLRT			  , WIRE_SEND_EXRT		, WIRE_RECV_EXRT			  , EXCH_BASERT         , USD_CONV_RT				  , INS_USR				, INS_YMD			, INS_HM					  , UPD_USR  			, UPD_YMD			, UPD_HM			  )     VALUES (			'@OFFICE_CD'			, '@BASE_CURR'			, '@CURR_CD'					      , '@EXRT_MM'				, @CURR_UNIT		  , NVL(@CASH_BUYRT,0)		, NVL(@CASH_SELLRT,0)		  , NVL(@WIRE_SEND_EXRT,0)	, NVL(@WIRE_RECV_EXRT,0)		  , NVL(@EXCH_BASERT,0)		  , NVL(@USD_CONV_RT,0)		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	 	, UFN_DATE_FORMAT('TIME')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	    , UFN_DATE_FORMAT('TIME')		  ) ;		  END ;
#MdmExrateMgt@Merge
--MdmExrateMgt@MergeMERGE INTO MDM_EX_RATE AUSING  ( 		SELECT 				'@OFFICE_CD'		AS OFFICE_CD 	            			,'@BASE_CURR'		AS BASE_CURR	            			,'@CURR_CD'		AS CURR_CD               				,'@EXRT_YMD'		AS EXRT_YMD		    			,@CURR_UNIT              AS CURR_UNIT                			,@CASH_BUYRT		AS CASH_BUYRT						,@CASH_SELLRT            AS CASH_SELLRT              			,@WIRE_SEND_EXRT		AS WIRE_SEND_EXRT        				,@WIRE_RECV_EXRT         AS WIRE_RECV_EXRT           			,@EXCH_BASERT            AS EXCH_BASERT              			,@USD_CONV_RT            AS USD_CONV_RT	            			,'@RMK'                  AS RMK			,'@USR_ID'		AS INS_USR		    			,UFN_DATE_FORMAT('DATE')	AS INS_YMD	         				,UFN_DATE_FORMAT('TIME') AS INS_HM                   			,'@USR_ID'		AS UPD_USR  		    			,UFN_DATE_FORMAT('DATE')	AS UPD_YMD	            			,UFN_DATE_FORMAT('TIME') AS UPD_HM                   		  FROM DUAL	   ) BON (A.OFFICE_CD = B.OFFICE_CD AND A.BASE_CURR = B.BASE_CURR AND A.CURR_CD = B.CURR_CD AND A.EXRT_YMD = B.EXRT_YMD)WHEN MATCHED THEN	UPDATE SET							 CURR_UNIT      = @CURR_UNIT                               			, CASH_BUYRT	 = @CASH_BUYRT									, CASH_SELLRT    = @CASH_SELLRT                             			, WIRE_SEND_EXRT = @WIRE_SEND_EXRT								, WIRE_RECV_EXRT = @WIRE_RECV_EXRT                            			, EXCH_BASERT    = @EXCH_BASERT                               			, USD_CONV_RT	 = @USD_CONV_RT                             			, RMK            = '@RMK'            			, INS_USR	 = '@USR_ID'								, INS_YMD	 = UFN_DATE_FORMAT('DATE')		 				, INS_HM         = UFN_DATE_FORMAT('TIME')                  	  			, UPD_USR  	 = '@USR_ID'								, UPD_YMD	 = UFN_DATE_FORMAT('DATE')					, UPD_HM         = UFN_DATE_FORMAT('TIME')    		 WHEN NOT MATCHED THEN	INSERT (			OFFICE_CD	    	, BASE_CURR			, CURR_CD					  , EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT			, CASH_SELLRT			  , WIRE_SEND_EXRT		, WIRE_RECV_EXRT			  , EXCH_BASERT         , USD_CONV_RT		, RMK				  , INS_USR				, INS_YMD			, INS_HM					  , UPD_USR  			, UPD_YMD			, UPD_HM			  )     VALUES (			'@OFFICE_CD'		, '@BASE_CURR'		, '@CURR_CD'					      , '@EXRT_YMD'			, @CURR_UNIT		  , @CASH_BUYRT			, @CASH_SELLRT		  , @WIRE_SEND_EXRT		, @WIRE_RECV_EXRT		  , @EXCH_BASERT		, @USD_CONV_RT 		, '@RMK'						  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	 	, UFN_DATE_FORMAT('TIME')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	    , UFN_DATE_FORMAT('TIME')		  ) 		  
#MdmExrateMgt@Merge2
--MdmExrateMgt@Merge2MERGE INTO MDM_EX_RATE2 AUSING  ( 		SELECT 				'@OFFICE_CD'		AS OFFICE_CD 	            			,'@BASE_CURR'		AS BASE_CURR	            			,'@CURR_CD'		AS CURR_CD               				,'@EXRT_YMD'		AS EXRT_YMD		    			,@CURR_UNIT              AS CURR_UNIT                			,@CASH_BUYRT		AS CASH_BUYRT						,@CASH_SELLRT            AS CASH_SELLRT              			,@WIRE_SEND_EXRT		AS WIRE_SEND_EXRT        				,@WIRE_RECV_EXRT         AS WIRE_RECV_EXRT           			,@EXCH_BASERT            AS EXCH_BASERT              			,@USD_CONV_RT            AS USD_CONV_RT	            			,'@RMK'                  AS RMK			,'@SEQ'					 AS SEQ			,'@USR_ID'		AS INS_USR		    			,UFN_DATE_FORMAT('DATE')	AS INS_YMD	         				,UFN_DATE_FORMAT('TIME') AS INS_HM                   			,'@USR_ID'		AS UPD_USR  		    			,UFN_DATE_FORMAT('DATE')	AS UPD_YMD	            			,UFN_DATE_FORMAT('TIME') AS UPD_HM                   		  FROM DUAL	   ) BON (A.OFFICE_CD = B.OFFICE_CD AND A.BASE_CURR = B.BASE_CURR AND A.CURR_CD = B.CURR_CD AND A.EXRT_YMD = B.EXRT_YMD AND A.SEQ = B.SEQ)WHEN MATCHED THEN	UPDATE SET							 CURR_UNIT      = @CURR_UNIT                               			, CASH_BUYRT	 = @CASH_BUYRT									, CASH_SELLRT    = @CASH_SELLRT                             			, WIRE_SEND_EXRT = @WIRE_SEND_EXRT								, WIRE_RECV_EXRT = @WIRE_RECV_EXRT                            			, EXCH_BASERT    = @EXCH_BASERT                               			, USD_CONV_RT	 = @USD_CONV_RT                             			, RMK            = '@RMK'            			, INS_USR	 = '@USR_ID'								, INS_YMD	 = UFN_DATE_FORMAT('DATE')		 				, INS_HM         = UFN_DATE_FORMAT('TIME')                  	  			, UPD_USR  	 = '@USR_ID'								, UPD_YMD	 = UFN_DATE_FORMAT('DATE')					, UPD_HM         = UFN_DATE_FORMAT('TIME')    		 WHEN NOT MATCHED THEN	INSERT (			OFFICE_CD	    	, BASE_CURR			, CURR_CD					  , EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT			, CASH_SELLRT			  , WIRE_SEND_EXRT		, WIRE_RECV_EXRT			  , EXCH_BASERT         , USD_CONV_RT		, RMK		, SEQ			  , INS_USR				, INS_YMD			, INS_HM					  , UPD_USR  			, UPD_YMD			, UPD_HM			  )     VALUES (			'@OFFICE_CD'		, '@BASE_CURR'		, '@CURR_CD'					      , '@EXRT_YMD'			, @CURR_UNIT		  , @CASH_BUYRT			, @CASH_SELLRT		  , @WIRE_SEND_EXRT		, @WIRE_RECV_EXRT		  , @EXCH_BASERT		, @USD_CONV_RT 		, '@RMK'	, LPAD('@SEQ',3,'0')						  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	 	, UFN_DATE_FORMAT('TIME')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	    , UFN_DATE_FORMAT('TIME')		  ) 		  
#MdmExrateMgt@Search
--MdmExrateMgt@SearchSELECT CURR_CD     , CURR_UNIT     , CASH_BUYRT     , CASH_SELLRT	 , WIRE_SEND_EXRT     , WIRE_RECV_EXRT     , EXCH_BASERT     , USD_CONV_RT     , RMK  FROM MDM_EX_RATE WHERE OFFICE_CD = '@OFFICE_CD'   AND EXRT_YMD = '@S_EXRT_YMD' ORDER BY CURR_CD
#MdmExrateMgt@Search2
--MdmExrateMgt@Search2SELECT  OFFICE_CD      , BASE_CURR      , CURR_CD      , EXRT_YMD      , SEQ      , CURR_UNIT      , CASH_BUYRT      , CASH_SELLRT      , WIRE_SEND_EXRT      , WIRE_RECV_EXRT      , EXCH_BASERT      , USD_CONV_RT      , INS_USR      , INS_YMD      , INS_HM      , UPD_USR      , UPD_YMD      , UPD_HM      , RMK  FROM MDM_EX_RATE2  WHERE EXRT_YMD = '@S_EXRT_YMD'   AND SEQ = '@S_SEQ' [CURR_CD]   AND CURR_CD IN ('USD','EUR','JPY','AUD') [/CURR_CD]ORDER BY SEQ, CURR_CD
#MdmExrateMgt@Search2All
--MdmExrateMgt@Search2AllSELECT  OFFICE_CD      , BASE_CURR      , CURR_CD      , EXRT_YMD      , SEQ      , CURR_UNIT      , CASH_BUYRT      , CASH_SELLRT      , WIRE_SEND_EXRT      , WIRE_RECV_EXRT      , EXCH_BASERT      , USD_CONV_RT      , INS_USR      , INS_YMD      , INS_HM      , UPD_USR      , UPD_YMD      , UPD_HM      , RMK  FROM MDM_EX_RATE2  WHERE EXRT_YMD = '@S_EXRT_YMD'   --AND SEQ >= LPAD( '@S_EXRATE_SEQ', 3, '0')   --2022.11.29 jwheo 노루로제넷 최초고시환율만 가져가도록 수정.   AND TO_NUMBER(NVL(SEQ,'0')) = 1ORDER BY SEQ, CURR_CD
#MdmExrateMgt@SearchMonthly
-- MdmExrateMgt@SearchMonthlySELECT OFFICE_CD     , BASE_CURR     , CURR_CD     , EXRT_MM     , CURR_UNIT     , CASH_BUYRT     , CASH_SELLRT     , WIRE_SEND_EXRT     , WIRE_RECV_EXRT     , EXCH_BASERT     , USD_CONV_RT     , UPD_USR     , UPD_YMD     , UPD_HM  FROM MDM_MM_EX_RATE WHERE OFFICE_CD = '@OFFICE_CD'   AND BASE_CURR = '@BASE_CURR'   AND EXRT_MM = '@EXRT_MM' ORDER BY CURR_CD   
#MdmExrateMgt@Update
--MdmExrateMgt@UpdateUPDATE MDM_EX_RATE    SET CURR_UNIT		= '@CURR_UNIT'     , CASH_BUYRT		= @CASH_BUYRT     , CASH_SELLRT		= @CASH_SELLRT     , WIRE_SEND_EXRT	= @WIRE_SEND_EXRT     , WIRE_RECV_EXRT	= @WIRE_RECV_EXRT     , EXCH_BASERT		= @EXCH_BASERT     , USD_CONV_RT		= @USD_CONV_RT     , RMK              = '@RMK'     , UPD_USR			= '@USR_ID'     , UPD_YMD			= UFN_DATE_FORMAT('DATE')     , UPD_HM			= UFN_DATE_FORMAT('TIME')WHERE  OFFICE_CD 		= '@OFFICE_CD'  AND  BASE_CURR 		= '@BASE_CURR'  AND  CURR_CD 			= '@CURR_CD'  AND  EXRT_YMD 		= '@EXRT_YMD'
#MdmExrateMgt@Update2
--MdmExrateMgt@Update2UPDATE MDM_EX_RATE2    SET CURR_UNIT		= '@CURR_UNIT'     , CASH_BUYRT		= @CASH_BUYRT     , CASH_SELLRT		= @CASH_SELLRT     , WIRE_SEND_EXRT	= @WIRE_SEND_EXRT     , WIRE_RECV_EXRT	= @WIRE_RECV_EXRT     , EXCH_BASERT		= @EXCH_BASERT     , USD_CONV_RT		= @USD_CONV_RT     , RMK              = '@RMK'     , UPD_USR			= '@USR_ID'     , UPD_YMD			= UFN_DATE_FORMAT('DATE')     , UPD_HM			= UFN_DATE_FORMAT('TIME')WHERE  OFFICE_CD 		= '@OFFICE_CD'  AND  BASE_CURR 		= '@BASE_CURR'  AND  CURR_CD 			= '@CURR_CD'  AND  EXRT_YMD 		= '@EXRT_YMD'  AND  SEQ				= '@SEQ'
#MdmExrateMgt@UpdateMonthly
-- MdmExrateMgt@UpdateMonthlyUPDATE MDM_MM_EX_RATE    SET CURR_UNIT		= '@CURR_UNIT'     , CASH_BUYRT		= 'CASH_BUYRT     , CASH_SELLRT		= NVL(@CASH_SELLRT,0)     , WIRE_SEND_EXRT	= NVL(@WIRE_SEND_EXRT,0)     , WIRE_RECV_EXRT	= NVL(@WIRE_RECV_EXRT,0)     , EXCH_BASERT		= NVL(@EXCH_BASERT,0)     , USD_CONV_RT		= NVL(@USD_CONV_RT,0)     , UPD_USR			= '@USR_ID'     , UPD_YMD			= UFN_DATE_FORMAT('DATE')     , UPD_HM			= UFN_DATE_FORMAT('TIME')WHERE  OFFICE_CD 		= '@OFFICE_CD'  AND  BASE_CURR 		= '@BASE_CURR'  AND  CURR_CD 			= '@CURR_CD'  AND  EXRT_MM 		    = '@EXRT_MM'
#MdmExrateMgt@WeekDay
--MdmExrateMgt@WeekDaySELECT TO_CHAR( TO_DATE('@EX_DATE', 'YYYYMMDD'),'D')AS EX_DATE FROM DUAL
