#MdmUserAuth@Insert
BEGIN	DELETE MDM_USER_AUTH 	 WHERE SYS_ID = '@SYS_ID' 	   AND PGM_ID = '@PGM_ID' 	   AND FUNC_ID = '@FUNC_ID' 	   AND USR_ID = '@USR_ID';		INSERT INTO MDM_USER_AUTH(		SYS_ID,		PGM_ID,		FUNC_ID,		USR_ID,		USE_YN,		INS_USR,		INS_YMD,	    INS_HM,		UPD_USR,	    UPD_YMD,	    UPD_HM)	VALUES (		'@SYS_ID',		'@PGM_ID',		'@FUNC_ID',		'@USR_ID',		'@USE_YN',		'@INS_USR',		UFN_DATE_FORMAT('DATE') , 		UFN_DATE_FORMAT('TIME'),		'@UPD_USR',		UFN_DATE_FORMAT('DATE') , 		UFN_DATE_FORMAT('TIME')     );     END;				
#MdmUserAuth@Search
-- MdmUserAuth@SearchSELECT A.USR_ID     AS USR_ID     , A.LOC_NM     AS USR_NM     , A.AUTH_TYPE  AS GRP_ID  FROM MDM_USER_MST A WHERE A.OFFICE_CD = '@OFFICE_CD'
   AND A.AUTH_TYPE = '@AUTH_TP'   [PGM_ID]
   AND A.USR_ID IN (SELECT USR_ID FROM MDM_USER_AUTH WHERE PGM_ID = '@PGM_ID')
   [/PGM_ID] ORDER BY USR_ID
#MdmUserAuth@SearchUserAuth
-- MdmUserAuth@SearchUserAuthSELECT H.SYS_ID      , H.PGM_ID      , H.FUNC_ID      , H.PGM_NM      , H.PGM_TYPE      , H.PGM_GRP     , NVL(H.USE_YN,'N') AS USE_YN     , H.PROGRAM_NAME      , F_TYPE     , H.USE_YN FROM (   		SELECT A.SYS_ID             , A.PGM_ID             , A.FUNC_ID             , A.PGM_NM             , A.PGM_TYPE              , A.PGM_GRP             , CASE WHEN B.USE_YN IS NULL                    THEN C.USE_YN                    ELSE B.USE_YN               END USE_YN             , A.TOP_ID             , A.LOWER_ID             , (SELECT PGM_NM                   FROM SYS_PROGRAM@DL_SYS                 WHERE PGM_ID = A.PGM_ID                    AND PGM_TYPE = 'P'                    AND SYS_ID = 'FMS'                )  AS PROGRAM_NAME             , CASE A.PGM_TYPE WHEN 'P' THEN 'Screen' WHEN 'F' THEN 'Button'  END AS F_TYPE            FROM SYS_PROGRAM@DL_SYS A                 LEFT OUTER JOIN MDM_USER_AUTH B                               ON A.SYS_ID = B.SYS_ID                              AND A.PGM_ID = B.PGM_ID                              AND A.FUNC_ID = B.FUNC_ID                              AND B.USR_ID = '@USR_ID'				 LEFT OUTER JOIN MDM_GRP_AUTH  C 				              ON A.SYS_ID = C.SYS_ID 				             AND A.PGM_ID = C.PGM_ID 				             AND A.FUNC_ID = C.FUNC_ID 				             AND C.GRP_ID = '@GRP_ID'	    ) H WHERE 1=1ORDER BY H.SYS_ID       , H.PGM_GRP       , H.PGM_ID,PGM_TYPE DESC       , H.FUNC_ID
