#ComDocumentMgt@Delete
--ComDocumentMgt@DeleteDELETE   FROM COM_DOC_MST WHERE MNGT_NO = '@MNGT_NO'    AND SEQ = '@SEQ'
#ComDocumentMgt@Insert
--ComDocumentMgt@InsertINSERT INTO COM_DOC_MST( 	        MNGT_NO	      , SEQ	      , FILE_NM	      , FILE_PATH	      , SCREEN	      , RMK	      , INS_USR	      , INS_YMD	      , INS_HM	      [DOC_TYPE], DOC_TYPE[/DOC_TYPE]	      [FILE_SIZE], FILE_SIZE[/FILE_SIZE]	      )   VALUES ( '@MNGT_NO'   		  , '@SEQ'          , '@FILE_NM'          , '@FILE_PATH'          , '@SCREEN'          , '@RMK'          , '@INS_USR'          , UFN_DATE_FORMAT('DATE')          , UFN_DATE_FORMAT('TIME')          [DOC_TYPE], '@DOC_TYPE'[/DOC_TYPE]          [FILE_SIZE], @FILE_SIZE[/FILE_SIZE]          )
#ComDocumentMgt@NewSeq
--ComDocumentMgt@NewSeqSELECT NVL(MAX(SEQ),0) + 1 AS SEQ  FROM COM_BOARD_CMT_MST WHERE BOARD_ID = '@BOARD_ID'
#ComDocumentMgt@Search
--ComDocumentMgt@SearchSELECT MNGT_NO	 , SEQ     , FILE_NM     , FILE_PATH     , SUBSTR(FILE_NM, INSTR(FILE_NM, '.', -1) + 1, LENGTH(FILE_NM) - INSTR(FILE_NM, '.', -1)) FILE_ICON     , RMK     , UFN_FORMAT(INS_YMD,'DATE') AS INS_YMD     , SCREEN     , 'Y' AS SUCCESS     , DOC_TYPE     , FILE_SIZE     , FORM_ID  FROM COM_DOC_MST WHERE 1 = 1 [OFFICE_CD]   --AND OFFICE_CD = '@OFFICE_CD' [/OFFICE_CD] [MNGT_NO]   --AND (   MNGT_NO = '@MNGT_NO'    --     OR MNGT_NO IN (SELECT Z.MNGT_NO FROM CRM_AS_MST Z WHERE UPPER_MNGT_NO IN (SELECT UPPER_MNGT_NO FROM CRM_AS_MST WHERE MNGT_NO = '@MNGT_NO'))   --    )    AND MNGT_NO IN (SELECT '@MNGT_NO' FROM DUAL                   UNION                   SELECT Z.MNGT_NO FROM CRM_AS_MST Z WHERE UPPER_MNGT_NO IN (SELECT UPPER_MNGT_NO FROM CRM_AS_MST WHERE MNGT_NO = '@MNGT_NO')) [/MNGT_NO] 	 ORDER BY INS_YMD DESC, INS_HM DESC
#ComDocumentMgt@Update
-- ComDocumentMgt@UpdateUPDATE COM_DOC_MST    SET FILE_NM = '@FILE_NM'     , FILE_PATH = '@FILE_PATH'     , SCREEN = '@SCREEN'     , RMK = '@RMK'     , UPD_USR = '@UPD_USR'     , UPD_YMD = UFN_DATE_FORMAT('DATE')     , UPD_HM = UFN_DATE_FORMAT('TIME')     [DOC_TYPE], DOC_TYPE = '@DOC_TYPE'[/DOC_TYPE]     [FILE_SIZE], FILE_SIZE = @FILE_SIZE[/FILE_SIZE] WHERE MNGT_NO = '@MNGT_NO'   AND SEQ = '@SEQ'
