#MdmGroupAuth@CopyAdd
--MdmGroupAuth@CopyAddMERGE INTO MDM_GRP_AUTH G	USING ( 		    SELECT SYS_ID				 , PGM_ID				 , FUNC_ID					 , USE_YN		      FROM MDM_GRP_AUTH		     WHERE GRP_ID ='@FM_GRP_ID'		       AND USE_YN = 'Y') DG		    ON (G.PGM_ID = DG.PGM_ID		        AND G.FUNC_ID = DG.FUNC_ID		        AND G.GRP_ID = '@TO_GRP_ID')	    WHEN NOT MATCHED THEN		            INSERT( SYS_ID	   , PGM_ID		, FUNC_ID     , GRP_ID	      , USE_YN				      , INS_USR	   , INS_YMD	, INS_HM				      , UPD_USR	   , UPD_YMD	, UPD_HM					   )			    VALUES( DG.SYS_ID  , DG.PGM_ID  , DG.FUNC_ID  , '@TO_GRP_ID'  , USE_YN				      , '@USR_ID'  , UFN_DATE_FORMAT('DATE')  , UFN_DATE_FORMAT('TIME') 					  , '@USR_ID'  , UFN_DATE_FORMAT('DATE')  , UFN_DATE_FORMAT('TIME') 					  )							     WHEN MATCHED THEN		            UPDATE SET USE_YN = DG.USE_YN
#MdmGroupAuth@CopyNew
--MdmGroupAuth@CopyNewBEGIN  DELETE MDM_GRP_AUTH   WHERE GRP_ID = '@TO_GRP_ID';      INSERT INTO MDM_GRP_AUTH        SELECT SYS_ID             , PGM_ID             , FUNC_ID             , '@TO_GRP_ID' AS GRP_ID             , USE_YN             , '@USR_ID' AS INS_USR             , UFN_DATE_FORMAT('DATE') AS INS_YMD             , UFN_DATE_FORMAT('TIME') AS INS_HM		     , '@USR_ID' AS UPD_USR		     , UFN_DATE_FORMAT('DATE') AS UPD_YMD		     , UFN_DATE_FORMAT('TIME') AS UPD_HM		  FROM MDM_GRP_AUTH		 WHERE GRP_ID = '@FM_GRP_ID';END;
#MdmGroupAuth@DEL_GROUP_AUTH
-- MdmGroupAuth@DEL_GROUP_AUTHDelete MDM_GRP_AUTHWhere GRP_ID = '@GRP_ID'	
#MdmGroupAuth@Insert
-- MdmGroupAuth@InsertBEGIN	DELETE MDM_GRP_AUTH     WHERE SYS_ID = '@SYS_ID'       AND PGM_ID = '@PGM_ID'       AND FUNC_ID = '@FUNC_ID'       AND GRP_ID = '@GRP_ID';       	INSERT INTO MDM_GRP_AUTH(		SYS_ID,		PGM_ID,		FUNC_ID,		GRP_ID,		USE_YN,		INS_USR,		INS_YMD,		INS_HM,		UPD_USR,		UPD_YMD,		UPD_HM	 ) VALUES (		'@SYS_ID',		'@PGM_ID',		'@FUNC_ID',		'@GRP_ID',		'@USE_YN',		'@INS_USR',		UFN_DATE_FORMAT('DATE'),		UFN_DATE_FORMAT('TIME'),		'@UPD_USR',		UFN_DATE_FORMAT('DATE'),		UFN_DATE_FORMAT('TIME')	);END ;
#MdmGroupAuth@Search
-- MdmGroupAuth@SearchSELECT COMN_CD AS GRP_ID     , CD_NM   AS GRP_NM FROM MDM_COM_CODEWHERE GRP_CD = 'S04'   [AUTH_ADMIN_FALSE]  AND COMN_CD <> '0'  [/AUTH_ADMIN_FALSE]ORDER BY SORT, GRP_ID
#MdmGroupAuth@SearchGroupAuth
-- MdmGroupAuth@SearchGroupAuthSELECT H.SYS_ID     , H.PGM_ID     , H.FUNC_ID      , H.PGM_NM     , H.PGM_TYPE      , H.PGM_GRP     , NVL(H.USE_YN,'N') AS USE_YN     , H.GRP_ID     , H.PROGRAM_NAME     , H.LOWER_ID     , H.TOP_ID     , H.F_TYPEFROM (		SELECT A.SYS_ID 		     , A.PGM_ID 		     , A.FUNC_ID		     , A.PGM_NM		     , A.PGM_TYPE		     , A.PGM_GRP		     , B.USE_YN		     , B.GRP_ID		     , D.PGM_NM AS PROGRAM_NAME		     , A.LOWER_ID		     , A.TOP_ID		     , CASE WHEN A.PGM_TYPE = 'P' 		            THEN 'Screen' 		            ELSE 'Button'		       END AS F_TYPE		 FROM SYS_PROGRAM A		    , MDM_GRP_AUTH B		    , ( SELECT PGM_ID,PGM_TYPE,SYS_ID,PGM_NM,FUNC_ID		          FROM SYS_PROGRAM		         WHERE PGM_TYPE = 'P'		       ) D		WHERE B.GRP_ID (+) = '@GRP_ID'		  AND A.SYS_ID  = B.SYS_ID(+)		  AND A.PGM_ID  = B.PGM_ID(+)		  AND A.FUNC_ID = B.FUNC_ID(+)		  AND A.SYS_ID = D.SYS_ID(+)		  AND A.PGM_ID =  D.PGM_ID(+) ) H  WHERE 1=1ORDER BY SYS_ID,PGM_GRP,PGM_ID,PGM_TYPE DESC,FUNC_ID 
