#EchCustomerTariff@Save
-- EchCustomerTariff@Save MERGE INTO ECH_VENDOR_TARIFF A	USING ( SELECT '@DOC_CD'		AS DOC_CD	             , @KLNET			AS KLNET	             , @KLNET_DC_RATE   AS KLNET_DC_RATE	             , '@KLNET_TYPE'	AS KLNET_TYPE	             , @KTNET			AS KTNET	             , @KTNET_DC_RATE   AS KTNET_DC_RATE	             , '@KTNET_TYPE'	AS KTNET_TYPE	             , @KCNET			AS KCNET	             , @KCNET_DC_RATE   AS KCNET_DC_RATE	             , '@KCNET_TYPE'	AS KCNET_TYPE	             , '@USR_ID'  		AS USR_ID				 , TO_CHAR(SYSDATE,'yyyyMMdd') AS INS_YMD				 , TO_CHAR(SYSDATE,'HH24MISS') AS INS_HM	          FROM DUAL )X       ON (A.DOC_CD = X.DOC_CD)        WHEN MATCHED THEN        UPDATE SET A.KLNET     	   = X.KLNET                 , A.KLNET_TYPE    = X.KLNET_TYPE                 , A.KLNET_DC_RATE = X.KLNET_DC_RATE                 , A.KTNET 	       = X.KTNET                 , A.KTNET_DC_RATE = X.KTNET_DC_RATE                 , A.KTNET_TYPE    = X.KTNET_TYPE                 , A.KCNET 	       = X.KCNET                 , A.KCNET_DC_RATE = X.KCNET_DC_RATE                 , A.KCNET_TYPE    = X.KCNET_TYPE    	     	 , A.UPD_YMD 	   = X.INS_YMD        	 	 , A.UPD_HM  	   = X.INS_HM WHEN NOT MATCHED THEN	           INSERT (  A.DOC_CD                  , A.KLNET                  , A.KLNET_DC_RATE                  , A.KLNET_TYPE                   , A.KTNET                  , A.KTNET_DC_RATE                  , A.KTNET_TYPE                   , A.KCNET                  , A.KCNET_DC_RATE                  , A.KCNET_TYPE                   , A.INS_USR                  , A.INS_YMD                  , A.INS_HM                  , A.UPD_USR                  , A.UPD_YMD                  , A.UPD_HM          )VALUES(  X.DOC_CD                  , X.KLNET                  , X.KLNET_DC_RATE                  , X.KLNET_TYPE                   , X.KTNET                  , X.KTNET_DC_RATE                  , X.KTNET_TYPE                   , X.KCNET                  , X.KCNET_DC_RATE                  , X.KCNET_TYPE                   , X.USR_ID                  , X.INS_YMD                  , X.INS_HM                  , X.USR_ID                  , X.INS_YMD                  , X.INS_HM          )
#EchCustomerTariff@Search
-- EchCustomerTariff@SearchSELECT A.CUST_CD     , A.CUST_NM     , A.DOC_CD     , A.DOC_NM     , B.VENDOR     , NVL(B.UNIT_PRC,0) AS UNIT_PRC     , NVL(B.UNIT_TYPE,'V') AS UNIT_TYPE     , NVL(B.DC_RATE,0) AS DC_RATE  FROM (        SELECT A.CUST_CD              , A.CUST_LOC_NM AS CUST_NM             , B.DOC_CD             , B.DOC_NM             , B.SORT          FROM CRM_CUST_MST  A             , (SELECT COMN_CD AS DOC_CD,CD_NM AS DOC_NM,SORT FROM MDM_COM_CODE WHERE GRP_CD = 'Y01') B         WHERE 1=1            AND A.CHAIN_ID IS NOT NULL           [S_CUST_CD]               AND A.CUST_CD = '@S_CUST_CD'           [/S_CUST_CD]           [S_CUST_NM]               AND A.CUST_LOC_NM LIKE '%@S_CUST_NM%'           [/S_CUST_NM]           [S_DOC_CD]               AND B.DOC_CD = '@S_DOC_CD'           [/S_DOC_CD]                  ) A LEFT OUTER JOIN ECH_CUST_TARIFF B           ON A.CUST_CD = B.CUST_CD          AND A.DOC_CD = B.DOC_CD   ORDER BY A.CUST_CD,A.SORT
#EchCustomerTariff@SearchChainList
--EchCustomerTariff@SearchChainListSELECT 	   CUST_CD	 , CUST_LOC_NM	 , CHAIN_ID	 , CASE WHEN CHAIN_START_YMD IS NOT NULL
	 		THEN SUBSTR(CHAIN_START_YMD,1,4) || '-' || SUBSTR(CHAIN_START_YMD,5,2) || '-' || SUBSTR(CHAIN_START_YMD,7,2)
	 		ELSE '' END AS CHAIN_START_YMD
	 , CASE WHEN CHAIN_END_YMD IS NOT NULL
	 		THEN SUBSTR(CHAIN_END_YMD,1,4) || '-' || SUBSTR(CHAIN_END_YMD,5,2) || '-' || SUBSTR(CHAIN_END_YMD,7,2)
	 		ELSE '' END AS CHAIN_END_YMD  FROM CRM_CUST_MST  WHERE CHAIN_ID IS NOT NULL [S_DATE]   AND CHAIN_START_YMD >= '@S_DATE' [/S_DATE] [E_DATE]   AND CHAIN_START_YMD <= '@E_DATE' [/E_DATE] [CUST_CD]   AND CUST_CD = '@CUST_CD' [/CUST_CD] [CUST_NM]   AND CUST_LOC_NM LIKE '%@CUST_LOC_NM%' [/CUST_NM]
 ORDER BY CUST_LOC_NM
#EchCustomerTariff@SearchVendorTariff
-- EchCustomerTariff@SearchVendorTariffSELECT A.COMN_CD AS DOC_CD     , A.CD_NM AS DOC_NM     , NVL(B.KLNET,0) AS KLNET     , NVL(B.KLNET_DC_RATE,0) AS KLNET_DC_RATE     , NVL(B.KLNET_TYPE,'X') AS KLNET_TYPE     , NVL(B.KTNET,0) AS KTNET     , NVL(B.KTNET_DC_RATE,0) AS KTNET_DC_RATE     , NVL(B.KTNET_TYPE,'X') AS KTNET_TYPE     , NVL(B.KCNET,0) AS KCNET     , NVL(B.KCNET_DC_RATE,0) AS KCNET_DC_RATE     , NVL(B.KCNET_TYPE,'X') AS KCNET_TYPE  FROM MDM_COM_CODE A       LEFT OUTER JOIN ECH_VENDOR_TARIFF B         ON A.COMN_CD = B.DOC_CD WHERE A.GRP_CD = 'Y01' ORDER BY A.SORT
