#CrmTaxNotiMgt@BuyTax
--CrmTaxNotiMgt@BuyTax
SELECT  
	'@SEQ' AS NUM
    ,A.WRITEDATE AS ISSUE_YMD    -- 계산서일자
    ,A.NTSSENDKEY AS TAX_ISSUE_NO  -- 승인번호
    ,A.INVOICERCORPNAME AS CUST_NM  --상호
    ,A.INVOICERCORPNUM AS CUST_CD  --사업자번호    
    ,(CASE WHEN TRIM(TO_CHAR(A.TAXTYPE,'00')) = '01' THEN '과세'
              WHEN TRIM(TO_CHAR(A.TAXTYPE,'00')) = '02' THEN '영세'
              ELSE '면세'
     END) AS VAT_TYPE   -- 과세, 영세, 면세
    ,A.AMOUNTTOTAL            AS LOC_AMT  -- 공급가액
    ,A.TAXTOTAL               AS VAT_AMT  -- 세액
    ,A.TOTALAMOUNT    AS SUM_AMT  -- 합계
    ,A.REMARK1 || A.REMARK2 || A.REMARK3 AS RMK  -- 비고
    ,A.INVOICEEEMAIL AS PIC_EMAIL
    ,R.SUBJ AS SUBJE
    ,R.CONT1 AS BODYCONT1
    ,R.CONT2 AS BODYCONT2
    ,R.CONT3 AS BODYCONT3
    ,'(주)쉥커코리아' AS SENDER_COMP_NM
    ,'심수경' AS SENDER_NM
    ,'Su-kyoung.sim@dbschenker.com' AS SENDER_EMAIL
    ,'02-3140-0820' AS SENDER_TEL
FROM BARO_TAX_RECV A    
CROSS JOIN CRM_TAX_NOTI_CUST@DL_CRM R
WHERE R.OFFICE_CD ='SISK'
 AND R.SEQ = '@SEQ'
 AND A.WRITEDATE BETWEEN '@STYMD' AND '@TOYMD'
 AND A.TAX_BILL_NO IS NULL
 AND A.INVOICEEEMAIL IS NOT NULL
 ORDER BY PIC_EMAIL
#CrmTaxNotiMgt@Delete
--CrmProjectMgt@DeleteDELETE   FROM CRM_TAX_NOTI_CUST WHERE SEQ = '@SEQ'
#CrmTaxNotiMgt@Insert
Insert Into CRM_TAX_NOTI_CUST(	SEQ 	,OFFICE_CD	,NOTI_TYPE 	,DOMAIN 	,CYCLE_TYPE 	,ST_YMD 	,ST_HM 	,DAYS 	,SUN	,MON	,TUE	,WED	,THU	,FRI	,SAT	,DAY1 	,DAY2 	,DAY3 	,DAY4 	,DAY5 	,USE_YN 	,SUBJ	,CONT1	,CONT2	,CONT3	,CONT4	,INS_USR 	,INS_YMD 	,INS_HM 	)Values (	'@SEQ' 	,'@NOTI_TYPE' 	,'@DOMAIN' 	,'@CYCLE_TYPE' 	,'@ST_YMD' 	,'@ST_HM' 	,@DAYS 	,'@SUN'	,'@MON'	,'@TUE'	,'@WED'	,'@THU'	,'@FRI'	,'@SAT'	,@DAY1 	,@DAY2 	,@DAY3 	,@DAY4 	,@DAY5 	,'@USE_YN' 	,'@SUBJ'	,'@CONT1'	,'@CONT2'	,'@CONT3'	,'@CONT4'		,'@USR_ID'     ,TO_CHAR(SYSDATE,'yyyyMMdd')    ,TO_CHAR(SYSDATE,'HH24MISS')	)
#CrmTaxNotiMgt@MaxNum
SELECT RTRIM(TO_CHAR(NVL(TO_NUMBER(MAX(SEQ))+1,1),'000000')) AS NEXT_NUM   FROM CRM_TAX_NOTI_CUST
#CrmTaxNotiMgt@Search
SELECT SEQ 	,OFFICE_CD	,NOTI_TYPE 	,DOMAIN 	,CYCLE_TYPE 	,ST_YMD 	,ST_HM 	,DAYS 	,SUN	,MON	,TUE	,WED	,THU	,FRI	,SAT	,DAY1 	,DAY2 	,DAY3 	,DAY4 	,DAY5 	,USE_YN 	,SUBJ	,CONT1	,CONT2	,CONT3	,CONT4	,INS_USR 	,INS_YMD 	,INS_HM 	,UPD_USR 	,UPD_YMD 	,UPD_HMFROM CRM_TAX_NOTI_CUST
WHERE 1=1[SEQ]	AND SEQ = '@SEQ' [/SEQ]
[ST_HM]
	AND ST_HM = '@ST_HM' 
[/ST_HM]
#CrmTaxNotiMgt@SearchEachData
-- --SELECT DB_IP, DB_PORT, DB_SID, USR_ID, USR_PWD FROM SYS_CUST_MST@ELVIS WHERE DOMAIN = '@DOMAIN'SELECT '110.45.209.20' AS DB_IP, DB_PORT, DB_SID, USR_ID, USR_PWD FROM SYS_CUST_MST@ELVIS WHERE DOMAIN = '@DOMAIN'
#CrmTaxNotiMgt@SearchTarget
-- CrmTaxNotiMgt@SearchTargetSELECT * FROM CRM_TAX_NOTI_CUST 
WHERE USE_YN = 'Y'
[ST_HM]
	AND ST_HM='@ST_HM'
[/ST_HM]
#CrmTaxNotiMgt@Update
Update CRM_TAX_NOTI_CUSTSet OFFICE_CD='@OFFICE_CD'	,NOTI_TYPE='@NOTI_TYPE' 	,DOMAIN='@DOMAIN' 	,CYCLE_TYPE='@CYCLE_TYPE' 	,ST_YMD='@ST_YMD' 	,ST_HM='@ST_HM' 	,DAYS=@DAYS 	,SUN='@SUN' 	,MON='@MON' 	,TUE='@TUE' 	,WED='@WED' 	,THU='@THU' 	,FRI='@FRI' 	,SAT='@SAT' 	,DAY1=@DAY1	,DAY2=@DAY2 	,DAY3=@DAY3 	,DAY4=@DAY4 	,DAY5=@DAY5 	,USE_YN='@USE_YN' 	,SUBJ='@SUBJ'	,CONT1='@CONT1'	,CONT2='@CONT2'	,CONT3='@CONT3'	,CONT4='@CONT4'	,UPD_USR='@USR_ID'     ,UPD_YMD=TO_CHAR(SYSDATE,'yyyyMMdd')    ,UPD_HM=TO_CHAR(SYSDATE,'HH24MISS')Where	SEQ = '@SEQ'	
#CrmTaxNotiMgt@UpdateDate
Update CRM_TAX_NOTI_CUSTSet  SEND_YMD=TO_CHAR(SYSDATE,'yyyyMMdd')    ,SEND_HM=TO_CHAR(SYSDATE,'HH24MISS')Where	SEQ = '@SEQ'	
