#SysBoardList@Delete
--SysBoardList@DeleteDELETE CRM_BOARD_CUST WHERE BOARD_ID = '@BOARD_ID'
#SysBoardList@Insert
-- SysBoardList@InsertMERGE INTO CRM_BOARD_CUST A     USING (SELECT '@BOARD_ID' AS BOARD_ID                 , '@DOMAIN' AS DOMAIN              FROM DUAL            ) B        ON (A.BOARD_ID = B.BOARD_ID AND A.DOMAIN = B.DOMAIN) WHEN NOT MATCHED THEN         INSERT (BOARD_ID, DOMAIN, INS_USR, INS_YMD, INS_HM) 
         VALUES ('@BOARD_ID', '@DOMAIN', '@USR_ID', TO_CHAR(SYSDATE,'yyyyMMdd'), TO_CHAR(SYSDATE,'HH24MISS'))
#SysBoardList@Search
-- SysBoardList@SearchSELECT CASE WHEN R.NOTICE_YN = 'Y'            THEN '[공지]'            ELSE BOARD_ID       END AS BOARD_SEQ     , R.BOARD_ID     , R.TITLE             , R.USR_NM     , R.INS_YMD     , R.EDIT     , R.NOTICE_YN  FROM (     SELECT A.BOARD_ID         , A.TITLE         , B.LOC_NM AS USR_NM         , TO_CHAR(TO_DATE(A.INS_YMD,'yyyyMMdd'),'yyyy-MM-dd') AS INS_YMD         , 'Edit' AS EDIT          , CASE WHEN A.EXP_YMD < UFN_DATE_FORMAT('DATE')                THEN 'N'                ELSE A.NOTICE_YN           END AS NOTICE_YN               FROM CRM_BOARD_MST A         , CRM_USR_MST B      WHERE A.INS_USR = B.USR_ID      ) R ORDER BY R.NOTICE_YN DESC, R.INS_YMD DESC
#SysBoardList@SearchCustList
-- SysBoardList@SearchCustListSELECT CASE WHEN B.DOMAIN IS NULL            THEN 'N'            ELSE 'Y'       END AS CHK     , A.CUST_CD     , A.CUST_NM     , A.DOMAIN     , A.CTRY_CD     , A.LANG_CD     , A.DB_IP_EXT     , A.WEB_IP_EXT     , (CASE WHEN (SELECT CRM_CD                     FROM EVB_MEMB_SET Z                    INNER JOIN CRM_CUST_MST X                            ON X.CUST_CD = Z.CRM_CD                    WHERE MEMB_STATE = 'S'                      AND X.DOMAIN = A.DOMAIN                      AND ROWNUM = 1) IS NOT NULL             THEN 'Y'             ELSE 'N'         END) AS ELVIS_BILL_YN  FROM SYS_CUST_MST@ELVIS A         LEFT OUTER JOIN CRM_BOARD_CUST B                 ON A.DOMAIN = B.DOMAIN                 AND B.BOARD_ID = '@BOARD_ID' WHERE 1=1   AND SVC_CD IN ('E', 'S')   AND USE_YN = 'Y'UNION ALLSELECT CASE WHEN B.DOMAIN IS NULL            THEN 'N'            ELSE 'Y'       END AS CHK     , A.CUST_CD     , A.CUST_NM     , A.DOMAIN     , A.CTRY_CD     , A.LANG_CD     , A.DB_IP_EXT     , A.WEB_IP_EXT     , (CASE WHEN (SELECT CRM_CD                     FROM EVB_MEMB_SET Z                    INNER JOIN CRM_CUST_MST X                            ON X.CUST_CD = Z.CRM_CD                    WHERE MEMB_STATE = 'S'                      AND X.DOMAIN = A.DOMAIN                      AND ROWNUM = 1) IS NOT NULL             THEN 'Y'             ELSE 'N'         END) AS ELVIS_BILL_YN  FROM SYS_CUST_MST@ELVIS_PLUS A         LEFT OUTER JOIN CRM_BOARD_CUST B                 ON A.DOMAIN = B.DOMAIN                 AND B.BOARD_ID = '@BOARD_ID' WHERE 1=1   AND SVC_CD IN ('E21')   AND USE_YN = 'Y' ORDER BY 3
#SysBoardList@SearchCustomer
-- SysBoardList@SearchCustomerSELECT 'N' AS CHK     , A.CUST_CD     , A.CUST_LOC_NM AS CUST_NM     , A.DOMAIN     , A.CTRY_CD     , A.LANG_CD     , A.DB_IP_EXT     , A.WEB_IP_EXT     , (CASE WHEN (SELECT CRM_CD                     FROM EVB_MEMB_SET Z                    INNER JOIN CRM_CUST_MST X                       ON X.CUST_CD = Z.CRM_CD                    WHERE MEMB_STATE = 'S'                      AND X.DOMAIN = A.DOMAIN                      AND ROWNUM = 1) IS NOT NULL             THEN 'Y'             ELSE 'N'         END) AS ELVIS_BILL_YN  FROM SYS_CUST_MST@ELVIS A WHERE 1=1   AND SVC_CD IN ('E', 'S')  ORDER BY A.CUST_NM  
