#SysMenuMgt@Delete
-- SysMenuMgt@DeleteDELETE FROM SYS_MENU_MST WHERE OFFICE_CD = '@OFFICE_CD'
#SysMenuMgt@Insert
-- SysMenuMgt@InsertINSERT INTO SYS_MENU_MST(      OFFICE_CD	, MENU_CD 	, UPPER_MENU_CD 	, FORM_ID 	, FORM_NM 	, FORM_TAG	, GRP_TAG	 	, CONVERT_ID	, RMK	, USE_YN 	, INS_USR 	, INS_YMD 	, INS_HM 	, UPD_USR 	, UPD_YMD 	, UPD_HM)VALUES (	  '@OFFICE_CD'	, '@MENU_CD'	, '@UPPER_MENU_CD' 	, '@FORM_ID' 	, '@FORM_NM' 	, NVL('@FORM_TAG','F')	, NVL('@GRP_TAG','F')	, '@CONVERT_ID'	, '@RMK' 	, '@USE_YN' 	, '@USR_ID'	, TO_CHAR(SYSDATE,'YYYYMMDD')	, TO_CHAR(SYSDATE,'HH24MISS')	, '@USR_ID'	, TO_CHAR(SYSDATE,'YYYYMMDD')	, TO_CHAR(SYSDATE,'HH24MISS'))
#SysMenuMgt@Search
-- SysMenuMgt@SearchSELECT SYS_ID     , PGM_ID     , FUNC_ID     , PGM_NM     , PGM_TYPE     , PGM_GRP  FROM SYS_PROGRAM WHERE PGM_TYPE = 'P'   AND SYS_ID = '@SYS_ID' [PGM_GRP]   AND PGM_GRP LIKE '@PGM_GRP%' [/PGM_GRP] [PGM_ID]   AND PGM_ID LIKE '@PGM_ID%' [/PGM_ID] ORDER BY SYS_ID        , PGM_GRP        , PGM_ID
#SysMenuMgt@SearchConvertList
-- SysMenuMgt@SearchConvertListSELECT (FORM_ID || '=' || CONVERT_ID) AS FORM_ID  FROM SYS_MENU_MST WHERE OFFICE_CD = '@HQ_OFFICE_CD'   AND CONVERT_ID IS NOT NULL ORDER BY FORM_ID 
#SysMenuMgt@SearchMenuTree
-- SysMenuMgt@SearchMenuTreeSELECT OFFICE_CD		AS OFFICE_CD     , MENU_CD			AS MENU_CD     , MENU_CD 			AS NEW_MENU     , UPPER_MENU_CD	AS UPPER_MENU_CD     , UPPER_MENU_CD 	AS NEW_UPPER     , FORM_ID			AS FORM_ID     , FORM_NM			AS FORM_NM     , FORM_TAG			AS FORM_TAG     , GRP_TAG			AS GRP_TAG     , CONVERT_ID		AS CONVERT_ID     , RMK				AS RMK  FROM SYS_MENU_MST WHERE OFFICE_CD = '@OFFICE_CD' ORDER BY MENU_CD
