#SysOfficeSetup@Search
-- SysOfficeSetup@SearchSELECT A.OFFICE_NM     , A.ENG_ADDR     , A.LOC_NM     , A.LOC_ADDR     , A.CTRY_CD     , B.CTRY_NM     , A.CURR_CD     , C.CD_NM AS CURR_NM     , A.AIR_PORT_CD     , D.LOC_NM AS AIR_PORT_NM     , A.SEA_PORT_CD     , E.LOC_NM AS SEA_PORT_NM     , F.AGENT_IATA_NO AS AGENT_IATA_CD     , A.SEA_BL_PREFIX     , A.AIR_BL_PREFIX     , A.OFFICE_PREFIX     , A.LOC_BANK_INFO     , A.LOC_BANK_ENG_INFO     , A.FCUR_BANK_INFO     , A.CUSTOMS_CD     , A.FOUND_YEAR     , A.TAX_OFFICE_CD     , A.VAT_PER     , A.ACCT_APLY_GRP
     , G1.ID AS FNC_ID
     , G1.PWD AS FNC_PWD
     , G2.SENDER_ID AS AIR_SENDER_ID
     , G3.SENDER_ID AS FWB_PIMA
     , G4.SENDER_ID AS AMS_PIMA
     , G5.ID AS AIRCIS_ID
     , G5.PWD AS AIRCIS_PWD
     , G6.ID AS AIR_KT_ID
     , G6.PWD AS AIR_KT_PWD
     , G7.ID AS AIR_ULOGIS_ID
     , G7.PWD AS AIR_ULOGIS_PWD
     
     , H1.SENDER_ID AS SEA_SENDER_ID
     , H2.ID AS SEA_KT_ID
     , H2.PWD AS SEA_KT_PWD
     , H3.ID AS SEA_ULOGIS_ID
     , H3.PWD AS SEA_ULOGIS_PWD
     , H4.ID AS AFR_ID
     , H4.PWD AS AFR_PWD
  FROM MDM_OFFICE_MST A         LEFT OUTER JOIN MDM_CTRY_MST B ON B.CTRY_CD = A.CTRY_CD         LEFT OUTER JOIN MDM_COM_CODE C ON C.COMN_CD = A.CURR_CD AND C.GRP_CD = 'M03'         LEFT OUTER JOIN MDM_PORT_MST D ON D.LOC_CD = A.AIR_PORT_CD         LEFT OUTER JOIN MDM_PORT_MST E ON E.LOC_CD = A.SEA_PORT_CD         LEFT OUTER JOIN MDM_CUST_MST F ON F.CUST_CD = A.OFFICE_CD
         LEFT OUTER JOIN MDM_OFFICE_EDI G1 ON G1.OFFICE_CD = A.OFFICE_CD AND G1.EDI_SYS_CD = 'FNC'
         LEFT OUTER JOIN MDM_OFFICE_EDI G2 ON G2.OFFICE_CD = A.OFFICE_CD AND G2.EDI_SYS_CD = 'OMFCS'
         LEFT OUTER JOIN MDM_OFFICE_EDI G3 ON G3.OFFICE_CD = A.OFFICE_CD AND G3.EDI_SYS_CD = 'FWB'
         LEFT OUTER JOIN MDM_OFFICE_EDI G4 ON G4.OFFICE_CD = A.OFFICE_CD AND G4.EDI_SYS_CD = 'PIMA'
         LEFT OUTER JOIN MDM_OFFICE_EDI G5 ON G5.OFFICE_CD = A.OFFICE_CD AND G5.EDI_SYS_CD = 'AIRCIS'
         LEFT OUTER JOIN MDM_OFFICE_EDI G6 ON G6.OFFICE_CD = A.OFFICE_CD AND G6.EDI_SYS_CD = 'KT_CA'
         LEFT OUTER JOIN MDM_OFFICE_EDI G7 ON G7.OFFICE_CD = A.OFFICE_CD AND G7.EDI_SYS_CD = 'KT_UA'
         LEFT OUTER JOIN MDM_OFFICE_EDI H1 ON H1.OFFICE_CD = A.OFFICE_CD AND H1.EDI_SYS_CD = 'SOMFC'
         LEFT OUTER JOIN MDM_OFFICE_EDI H2 ON H2.OFFICE_CD = A.OFFICE_CD AND H2.EDI_SYS_CD = 'KT_CS'
         LEFT OUTER JOIN MDM_OFFICE_EDI H3 ON H3.OFFICE_CD = A.OFFICE_CD AND H3.EDI_SYS_CD = 'KT_US'
         LEFT OUTER JOIN MDM_OFFICE_EDI H4 ON H4.OFFICE_CD = A.OFFICE_CD AND H4.EDI_SYS_CD = 'SOAHR'
 WHERE A.OFFICE_CD = '@OFFICE_CD'
#SysOfficeSetup@SearchAccount
-- SysOfficeSetup@SearchAccount
SELECT A.ACCT_TYPE     , A.ACCT_CD     , B.ACCT_NM     , A.OFFICE_CD  FROM MDM_OFFICE_ACCT A
  		 LEFT OUTER JOIN ACT_CODE_MST B ON B.OFFICE_CD = A.OFFICE_CD AND B.ACCT_CD = A.ACCT_CD WHERE 1=1   AND A.OFFICE_CD = '@OFFICE_CD'UNIONSELECT A.COMN_CD AS ACCT_TYPE	 , '' AS ACCT_CD	 , '' AS ACCT_NM	 , '@OFFICE_CD' AS OFFICE_CD  FROM MDM_COM_CODE A WHERE 1=1   AND A.GRP_CD = 'S07'   AND A.COMN_CD NOT IN (SELECT A.ACCT_TYPE						   FROM MDM_OFFICE_ACCT A						  WHERE 1=1						    AND A.OFFICE_CD = '@OFFICE_CD'						 )  
