#CodeService@CommonCode
-- CodeService@CommonCodeSELECT A.CODE     [TYPE_C]     	, CASE WHEN OPT_ITEM1 IS NULL      	       THEN DECODE(A.LOC_NM,NULL,A.NAME,A.LOC_NM)     	       ELSE '['||OPT_ITEM1||'] '|| DECODE(A.LOC_NM,NULL,A.NAME,A.LOC_NM)     	  END AS NAME     [/TYPE_C]     [TYPE_B]     	, '['||A.CODE||']'||' '||DECODE(A.LOC_NM,NULL,A.NAME,A.LOC_NM) AS NAME       [/TYPE_B]     [TYPE_A]        --, DECODE(A.LOC_NM,NULL,A.NAME,A.LOC_NM) AS NAME         , A.NAME     [/TYPE_A]     [Item]        , A.OPT_ITEM1 AS ITEM     [/Item]     [Item2]        , A.OPT_ITEM2 AS ITEM2     [/Item2]     [ColItem3]        , A.OPT_ITEM3 AS ITEM3     [/ColItem3] FROM (	SELECT COMN_CD AS CODE	     , CD_NM   AS NAME	     , SORT	     , OPT_ITEM1 	     , OPT_ITEM2 	     , OPT_ITEM3 	  FROM MDM_COM_CODE	 WHERE GRP_CD = '@GRP_CD' 	   AND USE_YN = 'Y'	   [SEARCH]	       AND COMN_CD||CD_NM||OPT_ITEM1 LIKE '%@KEY%' 	   [/SEARCH]	   [VALIDATE]	   	   AND COMN_CD = '@KEY'	   [/VALIDATE]	   [AUTH_ADMIN_FALSE]	   	   AND COMN_CD <> '0'		   [/AUTH_ADMIN_FALSE]	   [OPT_ITEM1]           AND OPT_ITEM1 = '@OPT_ITEM1'                                       [/OPT_ITEM1]	   [OPT_ITEM3]           AND OPT_ITEM3 LIKE '%@OPT_ITEM3%'                                       [/OPT_ITEM3]       [SEARCHTYPE_SALES]           AND COMN_CD IN ('04','08')       [/SEARCHTYPE_SALES]    ) A	[ORDER_BY_DEFAULT]  ORDER BY A.SORT,A.CODE[/ORDER_BY_DEFAULT][ORDER_BY_CODE_DESC]  ORDER BY A.CODE DESC, A.SORT[/ORDER_BY_CODE_DESC]
#CodeService@Customer
--CodeService@CustomerSELECT A.CUST_CD AS CODE     , (CASE WHEN A.USE_YN = 'Y' THEN '' ELSE '미사용 ' END) || A.CUST_LOC_NM AS NAME     , (CASE WHEN A.USE_YN = 'Y' THEN '' ELSE '미사용 ' END) || A.CUST_LOC_NM AS CUST_LOCNM     , A.CUST_ADDR AS OFFICE_ADDR     , A.CRN      , A.CEO      , A.DOMAIN     --, NVL(B.BANK_YN,'N') AS BANK_YN     , NVL((SELECT B.BANK_YN FROM CRM_CUST_MST B WHERE A.CUST_CD = B.CUST_CD),'N') AS BANK_YN	 --, C.CHECK_YN     --, C.STOP_YN       --, C.OUTSTAND_AMT     --, C.STOP_YMD       , A.SETUP_URL     , (SELECT UFN_TABLE_ITEM('COM_CODE', A.TAX_TRANS_TYPE, 'C15') FROM CRM_CUST_MST B WHERE A.CUST_CD = B.CUST_CD) AS TAX_TRANS_TYPE  FROM CRM_CUST_MST A       --LEFT OUTER JOIN CRM_CUST_MST B       --        ON A.CUST_CD = B.CUST_CD       --LEFT OUTER JOIN VT_CRM_CUST_MST C       --        ON C.CRN = A.CRN AND C.CUST_CD = A.CUST_CD WHERE 1=1 [USE_YN]    AND A.USE_YN = '@USE_YN' [/USE_YN] [SEARCH] 	AND (1=2 	      OR A.CUST_NM LIKE '%@KEY%' 	      OR A.CUST_LOC_NM LIKE '%@KEY%' 	      OR A.CRN LIKE '%@KEY%' 	      OR A.CEO LIKE '%@KEY%' 	     )  [/SEARCH] [VALIDATE]    AND A.CUST_CD = '@KEY' [/VALIDATE] [VALIDATE_LIKE]    AND A.CUST_LOC_NM LIKE '%@KEY%' [/VALIDATE_LIKE]ORDER BY (CASE WHEN A.USE_YN = 'Y' THEN 0 ELSE 1 END), A.CUST_LOC_NM   
#CodeService@CustomerPic
--CodeService@CustomerPicSELECT A.PIC_NM AS CODE     , A.TEL_NO AS NAME     , A.EMAIL FROM CRM_CUST_PIC AWHERE CUST_CD = '@CUST_CD'  [SEARCH]     AND A.PIC_NM LIKE '%@KEY%'   [/SEARCH]  [VALIDATE]     AND A.PIC_NM = '@KEY'  [/VALIDATE]  [VALIDATE_LIKE]     AND A.PIC_NM LIKE '%@KEY%'  [/VALIDATE_LIKE]ORDER BY A.PIC_NM  
#CodeService@DLCustomer
--CodeService@DLCustomer   SELECT X1.CUST_CD AS CODE          ,X.NAME2 AS NAME         ,X.NAME2 AS CUST_LOCNM          ,X.REGNO AS CRN          ,X.DAENM AS CEO     FROM CO_CUSTOMER@DL_YJITEXP X , CRM_CUST_MST X1    WHERE TRIM(X.CODE)  = X1.CUST_CD  [SEARCH] 	AND (1=2 	      OR CUST_NM LIKE '%@KEY%' 	      OR CUST_LOC_NM LIKE '%@KEY%' 	      OR CRN LIKE '%@KEY%' 	      OR CEO LIKE '%@KEY%' 	     )  [/SEARCH] [VALIDATE]    AND TRIM(X.CODE) = '@KEY' [/VALIDATE]    AND x1.USE_YN = 'Y'
#CodeService@DLDept
--CodeService@DLDept  SELECT TRIM(DEPT) AS CODE         , (DEPTNM) AS NAME     FROM CO_DEPT@DL_YJITEXP   WHERE 1=1   [SEARCH]    AND ( DEPT LIKE '%' || '@KEY' || '%'        OR DEPTNM LIKE '%' || '@KEY' || '%' )   [/SEARCH]   [VALIDATE]     AND TRIM(DEPT) = '@KEY'   [/VALIDATE]
#CodeService@DLFreight
--CodeService@DLFreightSELECT TRIM(FCODE) AS CODE     , TRIM(FDESC) AS NAME  FROM CO_FREIGHT @DL_YJITEXP WHERE FOAKB = 'O'     [SEARCH]    AND ( FCODE LIKE '%' || '@KEY' || '%'        OR FDESC LIKE '%' || '@KEY' || '%' )   [/SEARCH]   [VALIDATE]     AND TRIM(FCODE) = '@KEY'   [/VALIDATE] 
#CodeService@DLProject
  --CodeService@DLProject   SELECT TRIM(RFNO) AS CODE        ,TRIM(TITLE) AS NAME   FROM CO_PROJECT@DL_YJITEXP   WHERE ACTYN = 'Y'   [SEARCH]    AND ( RFNO LIKE '%' || '@KEY' || '%'        OR TITLE LIKE '%' || '@KEY' || '%' )   [/SEARCH]   [VALIDATE]     AND TRIM(RFNO) = '@KEY'   [/VALIDATE] 
#CodeService@DLSalse
  --CodeService@DLProject  SELECT TRIM(SSALESCD) AS CODE       ,TRIM(SSALESNM) AS NAME   FROM CO_SALES@DL_YJITEXP   WHERE 1=1   [SEARCH]    AND ( SSALESCD LIKE '%' || '@KEY' || '%'        OR SSALESNM LIKE '%' || '@KEY' || '%' )   [/SEARCH]   [VALIDATE]     AND TRIM(SSALESCD) = '@KEY'   [/VALIDATE] 
#CodeService@Office
-- CodeService@OfficeSELECT OFFICE_CD AS CODE     , OFFICE_NM AS NAME     , CTRY_CD FROM MDM_OFFICE_MST WHERE 1=1  [SEARCH]       AND OFFICE_CD || OFFICE_NM LIKE '%@KEY%'   [/SEARCH]  [VALIDATE]	  AND OFFICE_CD = '@KEY'   [/VALIDATE]  [OFFICE_LVL]      AND ORG_LVL = 'LB'  [/OFFICE_LVL]    [UPPER_ORG]      AND ORG_LVL = 'LB'      AND UPPER_ORG_CD IN (            SELECT UPPER_ORG_CD              FROM MDM_OFFICE_MST              WHERE OFFICE_CD = '@OFFICE_CD'          )  [/UPPER_ORG]  
#CodeService@OfficeBank
-- CodeService@OfficeBankSELECT TO_CHAR(SEQ) AS CODE     , BANK_TITLE   AS NAME  FROM MDM_OFFICE_BANK WHERE OFFICE_CD = '@KEY'   [LOC_BANK]   		AND BANK_TYPE = 'L'   [/LOC_BANK]   [ENG_BANK]   		AND BANK_TYPE = 'E'   [/ENG_BANK]   [FRGN_BANK]   		AND BANK_TYPE = 'F'   [/FRGN_BANK] ORDER BY BANK_TITLE    
#CodeService@User
-- CodeService@UserSELECT USR_ID AS CODE      , LOC_NM||(CASE WHEN USE_YN = 'N' THEN '_퇴사' END) AS NAME      , ENG_NM     , HP_NO     , TEL_NO     , FAX_NO     , EMAIL     , DEPT_CD     ,(SELECT CD_NM          FROM MDM_COM_CODE          WHERE GRP_CD = 'C03'          AND COMN_CD = A.DEPT_CD        ) AS DEPT_NM  FROM CRM_USR_MST A WHERE 1=1   AND DEPT_CD IS NOT NULL   [DEPT_CD]       AND DEPT_CD = '@DEPT_CD'   [/DEPT_CD]   [SEARCH]       AND LOC_NM || ENG_NM LIKE '%@KEY%'   [/SEARCH]   [VALIDATE]       AND USR_ID = '@KEY'   [/VALIDATE]   [VALIDATE_LIKE]       AND ((ENG_NM LIKE '%@KEY%') OR (LOC_NM LIKE '%@KEY%'))   [/VALIDATE_LIKE]   --AND USE_YN = 'Y' ORDER BY USE_YN DESC, LOC_NM    
