#SysCustomerMgt@DeleteCustomRmk
  DELETE SYS_CUST_RMK@DL_SYS   WHERE DOMAIN = '@DOMAIN'     AND SEQ = @SEQ    
#SysCustomerMgt@InsertCustom
 INSERT INTO SYS_CUST_MST@DL_SYS(     DOMAIN     ,TNS_NM     ,USR_ID     ,USR_PWD      ,SERVER_IP     ,DB_IP     ,DB_PORT 
    ,DB_SID    ,CUST_NM     ,CUST_ADDR     ,TEL_NO     ,FAX_NO     ,CUST_PIC1     ,CUST_EMAIL1     ,CUST_PIC2     ,CUST_EMAIL2       ,USE_YN     ,INS_USR     ,INS_YMD     ,INS_HM     ,UPD_USR     ,UPD_YMD     ,UPD_HM      )VALUES (     '@DOMAIN'     ,'@TNS_NM'     ,'@USR_ID'     ,'@USR_PWD'      ,'@SERVER_IP'     ,'@DB_IP'     ,'@DB_PORT' 
    ,'@DB_SID'     ,'@CUST_NM'     ,'@CUST_ADDR'     ,'@TEL_NO'     ,'@FAX_NO'     ,'@CUST_PIC1'     ,'@CUST_EMAIL1'     ,'@CUST_PIC2'     ,'@CUST_EMAIL2'       ,'@USE_YN'     ,'@USER_ID'    , TO_CHAR(SYSDATE,'YYYYMMDD')        , TO_CHAR(SYSDATE,'HH24MISS')     ,'@USER_ID'    , TO_CHAR(SYSDATE,'YYYYMMDD')         , TO_CHAR(SYSDATE,'HH24MISS')     )
#SysCustomerMgt@InsertCustomRmk
--SysCustomerMgt@InsertCustomRmkINSERT INTO SYS_CUST_RMK@DL_SYS(                         DOMAIN                          ,SEQ                          ,TITLE                          ,RMK                          ,INS_USR                          ,INS_YMD                          ,INS_HM                          ,UPD_USR                          ,UPD_YMD                          ,UPD_HM)                 VALUES (                         '@DOMAIN'                          ,NVL((SELECT MAX(SEQ) FROM SYS_CUST_RMK@DL_SYS WHERE DOMAIN = '@DOMAIN'),0) +1                         ,'@TITLE'                          ,'@RMK'                          ,'@INS_USR'                          ,TO_CHAR(SYSDATE,'YYYYMMDD')                          ,TO_CHAR(SYSDATE,'HH24MISS')                         ,'@UPD_USR'                          ,TO_CHAR(SYSDATE,'YYYYMMDD')                          ,TO_CHAR(SYSDATE,'HH24MISS'))
#SysCustomerMgt@SearchCustom
--SysCustomerMgt@SearchCustom SELECT  DOMAIN  		,DOMAIN AS DIS_DOMAIN        ,USE_YN        ,CUST_NM        ,CUST_ADDR        ,TEL_NO        ,FAX_NO        ,CUST_PIC1        ,CUST_EMAIL1        ,CUST_PIC2        ,CUST_EMAIL2        ,SERVER_IP        ,DB_IP        ,DB_PORT
        ,DB_SID        ,TNS_NM         ,'' AS RMK   FROM SYS_CUST_MST@DL_SYS  WHERE 1=1    AND DOMAIN = '@DOMAIN'
#SysCustomerMgt@SearchCustomList
--SysCustomerMgt@SearchCustomList  SELECT DOMAIN        ,CUST_NM        ,TEL_NO          ,CUST_PIC1    FROM SYS_CUST_MST@DL_SYS  WHERE 1=1 [DOMAIN]   AND DOMAIN LIKE '%' || '@DOMAIN' || '%' [/DOMAIN] [CUST_NM]   AND CUST_NM LIKE '%' || '@CUST_NM' || '%' [/CUST_NM] [SERCHIP]   AND (SERVER_IP LIKE '%' || '@SERVER_IP' || '%' OR             DB_IP LIKE '%' || '@SERVER_IP' || '%'    ) [/SERCHIP] ORDER BY DOMAIN
#SysCustomerMgt@SearchCustomRmk
--SysCustomerMgt@SearchCustomRmk	 SELECT DOMAIN	       ,SEQ 	       ,ROWNUM AS DIS_SEQ	       ,UPD_USR	       ,TO_CHAR(TO_DATE(NVL(UPD_YMD,TO_CHAR(SYSDATE,'YYYYMMDD')) || NVL(UPD_HM,'000000'),'YYYYMMDDHH24MISS'),'YYYY-MM-DD / HH24:MI:SS') AS UPD_YMD	       ,TITLE 	       ,RMK    	   FROM SYS_CUST_RMK@DL_SYS	  WHERE DOMAIN = '@DOMAIN'  	   [LIST]	    AND SEQ ='@SEQ'	   [/LIST]   ORDER BY SEQ DESC
#SysCustomerMgt@UpdateCustom
UPDATE SYS_CUST_MST@DL_SYSSET      TNS_NM='@TNS_NM'     ,USR_ID='@USR_ID'     ,USR_PWD='@USR_PWD'       ,SERVER_IP='@SERVER_IP'     ,DB_IP='@DB_IP'     ,DB_PORT='@DB_PORT' 
    ,DB_SID='@DB_SID'     ,CUST_NM='@CUST_NM'     ,CUST_ADDR='@CUST_ADDR'     ,TEL_NO='@TEL_NO'     ,FAX_NO='@FAX_NO'     ,CUST_PIC1='@CUST_PIC1'     ,CUST_EMAIL1='@CUST_EMAIL1'     ,CUST_PIC2='@CUST_PIC2'     ,CUST_EMAIL2='@CUST_EMAIL2'      ,USE_YN='@USE_YN'      ,UPD_USR='@UPD_USR'     ,UPD_YMD= TO_CHAR(SYSDATE,'YYYYMMDD')    ,UPD_HM= TO_CHAR(SYSDATE,'HH24MISS') WHERE    DOMAIN = '@DOMAIN'    
#SysCustomerMgt@UpdateCustomRmk
 UPDATE SYS_CUST_RMK@DL_SYS	SET 	     TITLE   ='@TITLE' 	    ,RMK     ='@RMK'   	    ,UPD_USR ='@UPD_USR' 	    ,UPD_YMD = TO_CHAR(SYSDATE,'YYYYMMDD')        ,UPD_HM  = TO_CHAR(SYSDATE,'HH24MISS')   WHERE DOMAIN = '@DOMAIN'    AND SEQ = @SEQ    
