#SvrModuleMst@InsertModuleLog
--SvrModuleMst@InsertModuleLogBEGIN  [USE_YN]    UPDATE CRM_SERVER_MODULE_LOG       SET USE_YN = 'N'     WHERE MNGT_NO = '@MNGT_NO'       AND MODULE_TYPE = '@MODULE_TYPE'       AND USE_YN = '@USE_YN';  [/USE_YN]    INSERT INTO CRM_SERVER_MODULE_LOG (           MNGT_NO         , MODULE_TYPE         , LOG_TIMESTAMP         , INS_YMD         , INS_HM         [LOG_TYPE], LOG_TYPE[/LOG_TYPE]         [LOG_MSG], LOG_MSG[/LOG_MSG]         [USE_YN], USE_YN[/USE_YN]    ) VALUES (           '@MNGT_NO'         , '@MODULE_TYPE'         , '@LOG_TIMESTAMP'         , TO_CHAR(SYSDATE,'yyyyMMdd')         , TO_CHAR(SYSDATE,'HH24MISS')         [LOG_TYPE], '@LOG_TYPE'[/LOG_TYPE]         [LOG_MSG], '@LOG_MSG'[/LOG_MSG]         [USE_YN], '@USE_YN'[/USE_YN]    );END;
#SvrModuleMst@SearchModule
--SvrModuleMst@SearchModuleSELECT A.MNGT_NO     , A.SERVER_IP     , A.SERVER_IP_EXT     , B.MODULE_TYPE     , B.LOOP_TYPE     , B.LOOP_VALUE     , B.PROC_WAIT_SEC     , B.PROC_LOG_SEC     , B.SMS_LIST     , B.EMAIL_LIST     , B.USE_YN     , (SELECT Z.LOC_NM FROM CRM_USR_MST Z WHERE Z.USR_ID = B.INS_USR) AS INS_USR     , TO_CHAR(TO_DATE(B.INS_YMD,'YYYYMMDD'),'YYYY-MM-DD') || ' ' ||       TO_CHAR(TO_DATE(B.INS_HM,'HH24MISS'), 'HH24:MI:SS') AS INS_YMD     , (SELECT Z.LOC_NM FROM CRM_USR_MST Z WHERE Z.USR_ID = B.UPD_USR) AS UPD_USR     , TO_CHAR(TO_DATE(B.UPD_YMD,'YYYYMMDD'),'YYYY-MM-DD') || ' ' ||       TO_CHAR(TO_DATE(B.UPD_HM,'HH24MISS'), 'HH24:MI:SS') AS UPD_YMD  FROM CRM_SERVER_MST A           INNER JOIN CRM_SERVER_MODULE B                       ON A.MNGT_NO = B.MNGT_NO                       AND B.USE_YN = 'Y'                    [MODULE_TYPE]                      AND B.MODULE_TYPE = '@MODULE_TYPE'                    [/MODULE_TYPE] WHERE 1 = 1 [SERVER_IP]   AND A.SERVER_IP = '@SERVER_IP' [/SERVER_IP]
#SvrModuleMst@SearchModuleLogCheck
--SvrModuleMst@SearchModuleLogCheckSELECT A.MNGT_NO          , A.SERVER_IP          , B.MODULE_TYPE          , C.* FROM CRM_SERVER_MST A         INNER JOIN CRM_SERVER_MODULE B         ON A.MNGT_NO = B.MNGT_NO AND MODULE_TYPE = 'CK'         LEFT OUTER JOIN CRM_SERVER_MODULE_LOG C         ON B.MNGT_NO = C.MNGT_NO AND B.MODULE_TYPE = C.MODULE_TYPE          AND C.INS_YMD = TRIM(TO_CHAR(SYSDATE,'YYYYMMDD'))         AND C.INS_HM >= TRIM(TO_CHAR((SYSTIMESTAMP - PROC_LOG_SEC),'HHMMDD'))         AND C.USE_YN = 'Y'--         LEFT OUTER JOIN CRM_SERVER_INFO_LOG C--         ON A.SERVER_IP = C.SERVER_IP AND DATA_DIV = 'SC' --         AND CHECK_YMD = TRIM(TO_CHAR(SYSDATE,'YYYYMMDD'))--         AND CHECK_HM >= TRIM(TO_CHAR((SYSTIMESTAMP - INTERVAL '5' MINUTE),'HHMMDD'))--         AND LAST_DATA_YN = 'Y'WHERE C.MNGT_NO IS NULLORDER BY C.MNGT_NO
#SvrModuleMst@SearchRPAInfo_20231005
--SvrModuleMst@SearchRPAInfoSELECT PKG_CRYPTO.DECRYPT(A.DB_ID,'Yjit1!43#2^3' || 'Key!#^') AS DB_ID     , PKG_CRYPTO.DECRYPT(A.DB_PWD,'Yjit1!43#2^3' || 'Key!#^') AS DB_PWD     , PKG_CRYPTO.DECRYPT(A.SVR_IP,'Yjit1!43#2^3' || 'Key!#^') AS SVR_IP     , B.AUTH_KEY     , B.MNGT_NO FROM CRM_CUST_SERVER A     LEFT OUTER JOIN  RPA_AUTH_KEY@DL_RPA B ON A.CUST_CD = B.CUST_CD WHERE A.CUST_CD = (SELECT CUST_CD FROM CRM_CUST_MST WHERE ELVIS_OFFICE_CD = '@OFFICE_CD')     AND A.SVR_TYPE ='D'     AND B.USE_YN ='Y' 
#SvrModuleMst@SearchTableName
--SvrModuleMst@SearchTableNameSELECT *  FROM @TABLE_NAME WHERE MNGT_NO = 'X'
#SvrModuleMst@삭제예정_CK모듈사용중

