#ComExcelMgt@Delete
--ComExcelMgt@Delete DELETE CRM_AS_MST WHERE MNGT_NO ='@MNGT_NO'
#ComExcelMgt@Delete_20200117
--ComMailMsg@DeleteDELETE   FROM MDM_COM_CODE  WHERE GRP_CD  = '@GRP_CD'   AND COMN_CD = '@COMN_CD'
#ComExcelMgt@Insert
-- ComExcelMgt@Insert	INSERT INTO CRM_AS_MST (		  MNGT_NO		, UPPER_MNGT_NO		, SYS_ID		, REQ_YMD		, REQ_HM		, REQ_SVC		, REQ_SVC2		, REQ_TYPE2		, CUST_CD		, CONTENT		, PROC_TYPE		, PRAR_YMD		, CMPT_YMD		, CMPT_HM		, RMK
		, CMPT_RMK		, DEPT_CD			, REQ_USR		, ONLINE_YN		, WORK_USR		, PROJECT_CD		, BATCH_ID		, INS_USR		, INS_YMD		, INS_HM		, UPD_USR		, UPD_YMD		, UPD_HM	) VALUES (	       '@MNGT_NO'	     , '@MNGT_NO'         , '@SYS_ID'         , '@REQ_YMD'         , '@REQ_HM'         , '@REQ_SVC'         , '@REQ_SVC2'         , '@REQ_TYPE2'         , '@CUST_CD'         , '@CONTENT'         , '@PROC_TYPE'         , '@PRAR_YMD'         , '@CMPT_YMD'         , '@CMPT_HM'         , '@RMK'
         , '@CMPT_RMK'         , '@DEPT_CD'         , '@REQ_USR'         , 'N'         , '@WORK_USR'         , '@PROJECT_CD'         , '@BATCH_ID'         , '@USR_ID'		 , TO_CHAR(SYSDATE,'yyyyMMdd')		 , TO_CHAR(SYSDATE,'HH24MISS')		 , '@USR_ID'		 , TO_CHAR(SYSDATE,'yyyyMMdd')		 , TO_CHAR(SYSDATE,'HH24MISS')	)
#ComExcelMgt@Save_20200117
--ComMailMsg@SaveMERGE INTO MDM_COM_CODE DUSING (      SELECT '@GRP_CD'		AS GRP_CD           , '@COMN_CD'		AS COMN_CD           , '@SUBJECT'		AS SUBJECT           , '@CONTENTS'	AS CONTENTS           , '@MSG_TYPE'	AS MSG_TYPE           , '@MSG_TYPE2'	AS MSG_TYPE2           , '@DEPT_CD'		AS DEPT_CD           , '@SSN_USR_ID'	AS INS_USR           , UFN_DATE_FORMAT('DATE') AS INS_YMD           , UFN_DATE_FORMAT('TIME') AS INS_HM        FROM DUAL      ) S ON (D.GRP_CD = S.GRP_CD AND D.COMN_CD = S.COMN_CD)WHEN MATCHED THEN    UPDATE SET        D.UPD_USR = S.INS_USR      , D.UPD_YMD = S.INS_YMD      , D.UPD_HM  = S.INS_HM    [SUBJECT]   , D.CD_NM     = S.SUBJECT[/SUBJECT]    [CONTENTS]  , D.RMK       = S.CONTENTS[/CONTENTS]    [MSG_TYPE]  , D.OPT_ITEM1 = S.MSG_TYPE[/MSG_TYPE]    [MSG_TYPE2] , D.OPT_ITEM2 = S.MSG_TYPE2[/MSG_TYPE2]    [DEPT_CD]   , D.OPT_ITEM3 = S.DEPT_CD[/DEPT_CD]WHEN NOT MATCHED THEN    INSERT (        D.GRP_CD 	, D.COMN_CD      , D.INS_USR   , D.INS_YMD , D.INS_HM      , D.UPD_USR   , D.UPD_YMD , D.UPD_HM      [SUBJECT]     , D.CD_NM[/SUBJECT]      [CONTENTS]    , D.RMK[/CONTENTS]      [MSG_TYPE]    , D.OPT_ITEM1[/MSG_TYPE]      [MSG_TYPE2]   , D.OPT_ITEM2[/MSG_TYPE2]      [DEPT_CD]     , D.OPT_ITEM3[/DEPT_CD]    ) VALUES (        S.GRP_CD 	        , (SELECT TRIM(TO_CHAR(NVL(MAX(A.COMN_CD),0)+1,'000'))		       FROM MDM_COM_CODE A			      WHERE A.GRP_CD = '@GRP_CD') 	      , S.INS_USR   , S.INS_YMD , S.INS_HM      , S.INS_USR   , S.INS_YMD , S.INS_HM          [SUBJECT]     , S.SUBJECT[/SUBJECT]      [CONTENTS]    , S.CONTENTS[/CONTENTS]      [MSG_TYPE]    , S.MSG_TYPE[/MSG_TYPE]      [MSG_TYPE2]   , S.MSG_TYPE[/MSG_TYPE2]      [DEPT_CD]     , S.DEPT_CD[/DEPT_CD]    )
#ComExcelMgt@Search
--ComExcelMgt@SearchSELECT A.OFFICE_CD     , A.TABLE_ID	 , A.FM_CD	 , A.FM_TYPE	 , A.TO_CD	 , A.TO_NM	 , A.RMK	 , A.FIELD_ID	 , A.FIELD_TYPE     , (SELECT B.LOC_NM FROM CRM_USR_MST B WHERE B.USR_ID = A.INS_USR) AS INS_USR     , TO_CHAR(TO_DATE(A.INS_YMD,'YYYYMMDD'),'YYYY-MM-DD') || ' ' ||	   TO_CHAR(TO_DATE(A.INS_HM,'hh24miss'), 'hh24:mi:ss') 	AS INS_YMD     , (SELECT B.LOC_NM FROM CRM_USR_MST B WHERE B.USR_ID = A.INS_USR) AS UPD_USR     , TO_CHAR(TO_DATE(A.UPD_YMD,'YYYYMMDD'),'YYYY-MM-DD') || ' ' ||	   TO_CHAR(TO_DATE(A.UPD_HM,'hh24miss'), 'hh24:mi:ss') 	AS UPD_YMD  FROM MDM_MAPPING_MST A WHERE A.OFFICE_CD = '@OFFICE_CD'   AND A.TABLE_ID = '@TABLE_ID' [FM_CD]   AND A.FM_CD = '@FM_CD' [/FM_CD] [FM_TYPE]   AND A.FM_TYPE = '@FM_TYPE' [/FM_TYPE] [TO_CD]   AND A.TO_CD = '@TO_CD' [/TO_CD] ORDER BY A.FM_CD
#ComExcelMgt@SearchCheck
--ComExcelMgt@SearchCheckSELECT A.MNGT_NO  FROM CRM_AS_MST A WHERE A.MNGT_NO = '@MNGT_NO'        
#ComExcelMgt@SearchExcelInfo
--ComExcelMgt@SearchExcelInfoSELECT NVL(OPT_ITEM1,'1') AS START_ROW      , OPT_ITEM2 AS MAPPING_TABLE     , OPT_ITEM3 AS MAPPING_TYPE  FROM MDM_COM_CODE  WHERE GRP_CD = 'T17'
#ComExcelMgt@SearchRmkList_20200117
--ComMailMsg@SearchRmkList          SELECT '#DEPT_NM' 	AS TAG, ''       			AS CAPTION, '부서명'			AS RMK FROM DUALUNION ALL SELECT '#SETUP_URL' 	AS TAG, '설치 URL : '       AS CAPTION, '설치주소'			AS RMK FROM DUALUNION ALL SELECT '#DOMAIL' 		AS TAG, '도메인 : '       	AS CAPTION, '도메인'			AS RMK FROM DUALUNION ALL SELECT '#VENDER_CD' 	AS TAG, ''       			AS CAPTION, '선사코드(VENDER)'	AS RMK FROM DUALUNION ALL SELECT '#VENDER_NM' 	AS TAG, ''    				AS CAPTION, '선사명(VENDER)'	AS RMK FROM DUALUNION ALL SELECT '#CRN' 		AS TAG, ''       			AS CAPTION, '사업자번호'		AS RMK FROM DUALUNION ALL SELECT '#CUSTOMS_CD' 	AS TAG, ''       			AS CAPTION, '세관코드'			AS RMK FROM DUALUNION ALL SELECT '#CUST_NM' 	AS TAG, ''       			AS CAPTION, '거래처명'			AS RMK FROM DUALUNION ALL SELECT '#CUST_ADDR' 	AS TAG, ''       			AS CAPTION, '거래처주소'		AS RMK FROM DUALUNION ALL SELECT '#AS_CONTENT' 	AS TAG, ''       			AS CAPTION, '고객요청사항'		AS RMK FROM DUALUNION ALL SELECT '#AS_CMPT_RMK' AS TAG, ''       			AS CAPTION, '고객게시판 답변'	AS RMK FROM DUAL
#ComExcelMgt@Update
--ComExcelMgt@UpdateBEGIN UPDATE CRM_AS_MST   SET UPD_USR   = '@USR_ID'	 , UPD_YMD   = TO_CHAR(SYSDATE,'yyyyMMdd')	 , UPD_HM    = TO_CHAR(SYSDATE,'HH24MISS')	 , SAVE_CNT  = SAVE_CNT + 1	 , SYS_ID='@SYS_ID' 	 , REQ_YMD='@REQ_YMD' 	 , REQ_HM='@REQ_HM' 	 , REQ_SVC='@REQ_SVC' 	 , REQ_SVC2='@REQ_SVC2' 	 , REQ_TYPE2='@REQ_TYPE2' 	 , CUST_CD='@CUST_CD'	 , CONTENT='@CONTENT' 	 , PROC_TYPE='@PROC_TYPE'      , PRAR_YMD='@PRAR_YMD'     , CMPT_YMD='@CMPT_YMD'      , CMPT_HM='@CMPT_HM'      , RMK='@RMK' 
     , CMPT_RMK='@CMPT_RMK' 	 , DEPT_CD='@DEPT_CD' 	 , PROJECT_CD='@PROJECT_CD'  WHERE MNGT_NO   = '@MNGT_NO';   UPDATE CRM_AS_MST     SET DEPT_CD = '@DEPT_CD'   WHERE DEPT_CD IS NULL     AND MNGT_NO = '@MNGT_NO';    END ;
