#MetaStlMgt@Search
--MetaStlMgt@Search
SELECT SUBSTR(USE_YMD,1,4)||'-'||SUBSTR(USE_YMD,5,2) AS STL_YMD
     , USR_TYPE
     , CRN
     , CUST_NM
     , NVL(EXPORT,0)       AS EXP_SIZE
     , NVL(EXPORT,0)*100   AS EXP_AMT
     , NVL(IMPORT,0)       AS IMP_SIZE
     , NVL(IMPORT,0)*100   AS IMP_AMT
     , NVL(SEA_IM,0)       AS IMP_SEA_SIZE
     , NVL(SEA_IM,0)*100   AS IMP_SEA_AMT
     , NVL(SEA_EX,0)       AS EXP_SEA_SIZE
     , NVL(SEA_EX,0)*100   AS EXP_SEA_AMT
     , NVL(AIR_IM,0)       AS IMP_AIR_SIZE
     , NVL(AIR_IM,0)*100   AS IMP_AIR_AMT
     , NVL(AIR_EX,0)       AS EXP_AIR_SIZE
     , NVL(AIR_EX,0)*100   AS EXP_AIR_AMT
     , NVL(QUOT,0)     AS QUT_SIZE
     , NVL(QUOT,0)*100 AS QUT_AMT
     , NVL(DOCU,0)     AS DOC_SIZE
     , NVL(DOCU,0)*100 AS DOC_AMT
     , (NVL(EXPORT,0)*100)+(NVL(IMPORT,0)*100)+(NVL(SEA_IM,0)*100)+(NVL(SEA_EX,0)*100)+(NVL(AIR_IM,0)*100)+(NVL(AIR_EX,0)*100)+(NVL(QUOT,0)*100)+(NVL(DOCU,0)*100) AS TOT_AMT
FROM (SELECT USE_YMD, USR_TYPE, CRN, CUST_NM, SVC_TYPE, TO_NUMBER(FILE_CNT) AS NUM_FILE_AMT
        FROM META_USE_DTL A
       WHERE 1 = 1
       [STL_YMD]
         AND USE_YMD BETWEEN '@STL_YMD'||'01' AND '@STL_YMD'||'31'
       [/STL_YMD]
       [CRN]
         AND CRN LIKE '@CRN%'
       [/CRN]
       [CUST_NM]
         AND CUST_NM LIKE '%@CUST_NM%'
       [/CUST_NM]
       [USR_TYPE]
         AND USR_TYPE = '@USR_TYPE' --S:화주 F:포워더
       [/USR_TYPE]
      )
PIVOT (
  SUM(NVL(NUM_FILE_AMT,0))
  FOR SVC_TYPE IN ('EXPORT' AS EXPORT, 'IMPORT' AS IMPORT, 'SEA_IM' AS SEA_IM, 'SEA_EX' AS SEA_EX, 'AIR_IM' AS AIR_IM, 'AIR_EX' AS AIR_EX, 'QUOT' AS QUOT, 'DOCU' AS DOCU)
)
ORDER BY USR_TYPE
