#Login@AuthCheck_X
-- Login@AuthCheckSELECT NVL(MAX(ROWNUM),0) AS CNT  FROM MDM_USER_AUTHWHERE USR_ID = '@USR_ID'   AND USE_YN = 'Y'
#Login@CheckUser
-- Login@CheckUser  SELECT  USR_ID        , ENG_NM        , LOC_NM        , PSWD AS Password    FROM CRM_USR_MST   WHERE USR_ID = '@UserID'      AND USE_YN = 'Y'
#Login@GetDmoainList_X
   SELECT  DOMAIN AS NAME    	   ,TNS_NM AS CODE           [SETOFFICE]    	   ,USR_ID    	   ,USR_PWD           [/SETOFFICE]    FROM SYS_CUST_MST          [SETOFFICE]   WHERE UPPER(DOMAIN) = UPPER('@DOMAIN')          [/SETOFFICE]
#Login@RET_USER2_X
Select A.USR_ID,     A.ENG_NM AS USR_NM,     CASE WHEN A.TEL IS NULL THEN C.TEL_NO ELSE A.TEL END AS USR_TEL,     CASE WHEN A.FAX IS NULL THEN C.FAX_NO ELSE A.FAX END AS USR_FAX,    A.EMAIL AS USR_MAIL,     REPLACE(O.LOC_ADDR, CHR(13), '') AS CO_LOC_ADDR,    REPLACE(O.ENG_ADDR, CHR(13), '') AS CO_ENG_ADDR,    O.OFFICE_NM AS CO_OFFICE_NM,    REPLACE(O.LOC_BANK_INFO, CHR(13), '') AS CO_LOC_BANK,    O.LOCAL_NM AS CO_OFFICE_LOCALNM,    REPLACE(O.FCUR_BANK_INFO, CHR(13), '') AS CO_FCUR_BANK,    A.ORG_CD AS ORG_CD,     O.CURR_CD,     A.ENG_NM||' ['||TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI')||']' AS USR_NM_YMD,     (SELECT DEPT_NM FROM MDM_DEPT_MST  WHERE  DEPT_CD = A.ORG_CD) AS ORG_NM ,    A.LOCAL_NM AS USR_LOCNMFrom MDM_USER_MST A, MDM_OFFICE_MST O,MDM_CUST_MST CWhere A.USR_ID= '@USR_ID' 	AND O.OFFICE_CD = A.OFFICE_CD	AND O.OFFICE_CD = C.CUST_CD(+)
#Login@RetrieveMenu
-- Login@RetrieveMenuSELECT A.OFFICE_CD     , A.MENU_CD     , A.UPPER_MENU_CD     , A.FORM_ID     , A.FORM_NM     , A.GRP_TAG  FROM SYS_MENU_MST A WHERE A.OFFICE_CD = '@OFFICE_HQ'   AND A.FORM_TAG != 'P'ORDER BY A.MENU_CD
#Login@SearchOffice
-- Login@SearchOfficeSELECT '' AS OFFICE_NM     , '' AS LOC_NM     , '' AS LOC_ADDR     , '' AS ENG_ADDR     , '' AS BL_ADDR     , '' AS CURR_CD     , '' AS CTRY_CD     , '' AS  DCM_POINT     , '' AS AIR_PORT_CD     , '' AS  AIR_PORT_NM     , '' AS SEA_PORT_CD     , '' AS  SEA_PORT_NM     , '' AS AIR_BL_PREFIX     , '' AS SEA_BL_PREFIX     , '' AS OFFICE_PREFIX     , '' AS CUSTOMS_CD     , '' AS FOUND_YEAR     , 'YJIT' AS HQ_OFFICE_CD     , '' AS UPPER_ORG_CD     , '' AS AGENT_IATA_CD     , '' AS LANG_CD     , '' AS AIR_FRT_CD     , '' AS SEA_FRT_CD     , '' AS VAT_FRT_CD     , '' AS VAT_FRT_NM     , '' AS VAT_PER     , '' AS CITY_CD     , '' AS AUTO_SLIP_BY_TAX     , '' AS AUTO_INVOICE     , '' AS PFM_BY_OP     , '' AS DATE_FORMAT     , '' AS FCUR_EXRT_YN     , '' AS TRACKING_YN     , '' AS ETRUCK_BANK_YN     , '' AS LOGO_TYPE  FROM DUAL 
#Login@SearchUser
-- Login@SearchUserSELECT      USR_ID    ,ENG_NM    ,LOC_NM    ,'' AS GEND     ,'' AS HP_NO    ,'' AS TEL_NO    ,'' AS FAX_NO    ,EMAIL AS EMAIL    ,'YJIT' AS OFFICE_CD    ,DEPT_CD AS DEPT_CD    ,(SELECT Z.CD_NM FROM MDM_COM_CODE Z WHERE Z.GRP_CD = 'C03' AND Z.COMN_CD = A.DEPT_CD) AS DEPT_NM    ,AUTH_TYPE AS AUTH_TYPE    ,'HQ' AS ACT_LVL    ,'' AS SALES_LVL    ,'' AS MAIN_JOB    ,'' AS FIRST_LOAD_FORM    ,'' AS DFT_WH_CD    ,'' AS MAIN_BL_FORM    ,GROUP_EMAIL AS GROUP_EMAILFROM CRM_USR_MST AWHERE USR_ID = '@UserID'
#Login@SearchUserFuncAuth
-- Login@SearchUserFuncAuthSELECT SYS_ID     , PGM_ID     , FUNC_ID  FROM (  	SELECT SYS_ID  	     , PGM_ID  	     , FUNC_ID  	     , MIN(USE_YN) AS USE_YN  	  FROM (    		    SELECT SYS_ID		         , PGM_ID		         , FUNC_ID		         , USE_YN		      FROM MDM_USER_AUTH		     WHERE USR_ID = '@UserID'		       AND FUNC_ID <> PGM_ID		       --AND USE_YN = 'Y'		    UNION		    SELECT SYS_ID		         , PGM_ID		         , FUNC_ID		         , USE_YN		      FROM MDM_GRP_AUTH 		     WHERE GRP_ID=(SELECT AUTH_TYPE FROM CRM_USR_MST 		                    WHERE USR_ID = '@UserID') 		       AND FUNC_ID <> PGM_ID 		       AND USE_YN = 'Y' 		) GROUP BY SYS_ID, PGM_ID, FUNC_ID		       ) WHERE USE_YN = 'Y'
#Login@SearchUserPgmAuth
-- Login@SearchUserPgmAuthSELECT  SYS_ID      , PGM_ID FROM (		  	SELECT  SYS_ID			      , PGM_ID			      , MIN(USE_YN) AS USE_YN			  FROM (							SELECT SYS_ID 								 , PGM_ID 								 , USE_YN							  FROM MDM_USER_AUTH							 WHERE USR_ID = '@UserID'							   AND PGM_ID = FUNC_ID							  -- AND USE_YN = 'Y'							 GROUP BY  SYS_ID							          ,PGM_ID							          ,USE_YN							UNION ALL							SELECT SYS_ID							     , PGM_ID 							     , USE_YN							  FROM MDM_GRP_AUTH 							 WHERE 1=1 							   AND USE_YN = 'Y'							   AND GRP_ID =(SELECT AUTH_TYPE 							                  FROM CRM_USR_MST WHERE USR_ID = '@UserID')							 GROUP BY SYS_ID							         ,PGM_ID 							         ,USE_YN				   )		  GROUP BY SYS_ID			       ,PGM_ID		)WHERE USE_YN='Y'
#Login@UpdateFailCnt_X
--Login@UpdateFailCntUPDATE MDM_USER_MST   SET      [FAILED]        LOGIN_FAIL_CNT = LOGIN_FAIL_CNT+1     [/FAILED]     [SUCCESS]         LOGIN_FAIL_CNT = 0     [/SUCCESS]     [UNLOCK]         LOGIN_FAIL_CNT = -1        ,PSWD = UNF_MD5_ENCRYPTION('@PSWD')     [/UNLOCK] WHERE USR_ID='@USR_ID'
