#SetupWizard@CheckDomain
-- SetupWizard@CheckDomainSELECT DOMAIN  FROM SYS_CUST_MST@DL_SYS WHERE DOMAIN = '@DOMAIN'  
#SetupWizard@CheckNew
-- SetupWizard@CheckNewSELECT *   FROM MDM_OFFICE_MST   WHERE ROWNUM =1  
#SetupWizard@InsertHqOffice
-- SetupWizard@InsertHqOfficeBEGIN	INSERT INTO MDM_OFFICE_MST (	   OFFICE_CD	 , OFFICE_NM	 , LOC_NM	 , HQ_OFFICE_CD     , UPPER_ORG_CD	 , ORG_LVL	 , CTRY_CD	 , CURR_CD	 , TM_ZONE	 , PAPER_SIZE	 , AIR_PORT_CD	 , SEA_PORT_CD	 , CITY_CD	 , FOUND_YEAR	 , USE_YN	 , LANG_CD	 , VAT_PER	 , PWD_CHG_MM	 , DATE_FORMAT  ) VALUES (	   '@HQ_OFFICE_CD'	 , '@HQ_OFFICE_CD'||' HQ'	 , '@HQ_OFFICE_CD'||' HQ'	 , ''	 , ''	 , 'HQ'	 , '@CTRY_CD'	 , '@CURR_CD'	 , 0	 , 'A4'	 , '@AIR_PORT_CD'	 , '@SEA_PORT_CD'	 , '@CITY_CD'	 , ''	 , 'Y'	 , ''	 , 0	 , 0	 , 'YYYY-MM-DD'   );INSERT INTO MDM_OFFICE_MST (	   OFFICE_CD	 , OFFICE_NM	 , LOC_NM	 , HQ_OFFICE_CD     , UPPER_ORG_CD	 , ORG_LVL	 , CTRY_CD	 , CURR_CD	 , TM_ZONE	 , PAPER_SIZE	 , AIR_PORT_CD	 , SEA_PORT_CD	 , CITY_CD	 , FOUND_YEAR	 , USE_YN	 , LANG_CD	 , VAT_PER	 , PWD_CHG_MM	 , DATE_FORMAT  ) VALUES (	   '@AQ_OFFICE_CD'	 , '@AQ_OFFICE_CD'||' AQ'	 , '@AQ_OFFICE_CD'||' AQ'	 , '@HQ_OFFICE_CD'	 , '@HQ_OFFICE_CD'	 , 'AQ'	 , '@CTRY_CD'	 , '@CURR_CD'	 , 0	 , 'A4'	 , '@AIR_PORT_CD'	 , '@SEA_PORT_CD'	 , '@CITY_CD'	 , ''	 , 'Y'	 , ''	 , 0	 , 0	 , 'YYYY-MM-DD'   );   END ;
#SetupWizard@InsertMdm
-- SetupWizard@InsertMdmBEGIN	INSERT INTO MDM_CARR_MST	    SELECT * FROM MDM_CARR_MST@DL_ELVIS ;	    	INSERT INTO MDM_CNTN_MST	    SELECT * FROM MDM_CNTN_MST@DL_ELVIS ;	    	INSERT INTO MDM_CNTR_MST	    SELECT * FROM MDM_CNTR_MST@DL_ELVIS ;	INSERT INTO MDM_COM_CODE	    SELECT * FROM MDM_COM_CODE@DL_ELVIS ;	INSERT INTO MDM_COM_GRP	    SELECT * FROM MDM_COM_GRP@DL_ELVIS ;	INSERT INTO MDM_CTRY_MST	    SELECT * FROM MDM_CTRY_MST@DL_ELVIS ;	INSERT INTO MDM_FRT_MST	    SELECT * FROM MDM_FRT_MST@DL_ELVIS ;	INSERT INTO MDM_HS_MST	    SELECT * FROM MDM_HS_MST@DL_ELVIS ;	INSERT INTO MDM_LOOP	    SELECT * FROM MDM_LOOP@DL_ELVIS ;	INSERT INTO MDM_PORT_MST	    SELECT * FROM MDM_PORT_MST@DL_ELVIS ;	INSERT INTO MDM_WH_MST	    SELECT * FROM MDM_WH_MST@DL_ELVIS ;	INSERT INTO MDM_LANG_NAME	    SELECT * FROM MDM_LANG_NAME@DL_ELVIS ;	    	INSERT INTO MDM_GRP_AUTH	    SELECT * FROM MDM_GRP_AUTH@DL_ELVIS ;	INSERT INTO FMS_IATA_TRF	    SELECT * FROM FMS_IATA_TRF@DL_ELVIS ;END ;    
#SetupWizard@InsertOffice
-- SetupWizard@InsertOfficeINSERT INTO MDM_OFFICE_MST (	   OFFICE_CD	 , OFFICE_NM	 , LOC_NM	 , HQ_OFFICE_CD     , UPPER_ORG_CD	 , ORG_LVL	 , CTRY_CD	 , CURR_CD	 , TM_ZONE	 , PAPER_SIZE	 , AIR_PORT_CD	 , SEA_PORT_CD	 , CITY_CD	 , FOUND_YEAR	 , USE_YN	 , LANG_CD	 , VAT_PER	 , PWD_CHG_MM	 , DATE_FORMAT	 , AIR_BL_PREFIX     , SEA_BL_PREFIX     , OFFICE_PREFIX     , CUSTOMS_CD  ) VALUES (	   '@OFFICE_CD'	 , '@ENG_NM'	 , '@LOC_NM'	 , '@HQ_OFFICE_CD'	 , '@AQ_OFFICE_CD'	 , 'LB'	 , '@CTRY_CD'	 , '@CURR_CD'	 , 0	 , 'A4'	 , '@AIR_PORT_CD'	 , '@SEA_PORT_CD'	 , '@CITY_CD'	 , TO_CHAR(SYSDATE,'YYYY')	 , 'Y'	 , '@LANG_CD'	 , 6	 , 0	 , 'YYYY-MM-DD'	 , '@AIR_BL_PREFIX'     , '@SEA_BL_PREFIX'     , '@OFFICE_PREFIX'     , '@CUSTOMS_CD'   )
#SetupWizard@InsertOfficeConfig
-- SetupWizard@InsertOfficeConfigBEGIN    ----------------------------	INSERT INTO ACT_CODE_MST	    SELECT * 	      FROM ACT_CODE_MST@DL_ELVIS	     WHERE OFFICE_CD = '@CTRY_CD' ;		    	UPDATE ACT_CODE_MST	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = '@CTRY_CD' ;	 		---------------------------- 		INSERT INTO MDM_FRT_VAT	    SELECT * 	      FROM MDM_FRT_VAT@DL_ELVIS ;	---------------------------- 			INSERT INTO MDM_FRT_ACCT	    SELECT * 	      FROM MDM_FRT_ACCT@DL_ELVIS	     WHERE OFFICE_CD = '@CTRY_CD' ;	UPDATE MDM_FRT_ACCT	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = '@CTRY_CD' ;        ----------------------------		INSERT INTO MDM_OFFICE_MAND	    SELECT * 	      FROM MDM_OFFICE_MAND@DL_ELVIS ;		UPDATE MDM_OFFICE_MAND	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = 'ALL' ;	 	 	----------------------------		INSERT INTO MDM_OFFICE_ACCT	    SELECT * 	      FROM MDM_OFFICE_ACCT@DL_ELVIS	     WHERE OFFICE_CD = '@CTRY_CD' ;	UPDATE MDM_OFFICE_ACCT	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = '@CTRY_CD' ;	 	 ----------------------------		INSERT INTO MDM_OFFICE_CONFIG	    SELECT * 	      FROM MDM_OFFICE_CONFIG@DL_ELVIS	     WHERE OFFICE_CD = '@CTRY_CD' ;	UPDATE MDM_OFFICE_CONFIG	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = '@CTRY_CD' ;	 	 	 ------------------------------		INSERT INTO MDM_DEPT_MST	    SELECT * FROM MDM_DEPT_MST@DL_ELVIS ;	    	UPDATE MDM_DEPT_MST	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = 'ALL' ;	 	 ------------------------------		INSERT INTO MDM_KEY_NO_RULE	    SELECT * FROM MDM_KEY_NO_RULE@DL_ELVIS ;	    	UPDATE MDM_KEY_NO_RULE	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = 'ALL' ;	 	 	 ------------------------------		INSERT INTO MDM_OFFICE_BASE_EXRT	    SELECT * FROM MDM_OFFICE_BASE_EXRT@DL_ELVIS ;	    	UPDATE MDM_OFFICE_BASE_EXRT	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = 'ALL' ;	   ----------------------------        INSERT INTO ACT_FNCL_MST        SELECT *           FROM ACT_FNCL_MST@DL_ELVIS         WHERE OFFICE_CD = '@CTRY_CD' ;                UPDATE ACT_FNCL_MST       SET OFFICE_CD = '@OFFICE_CD'     WHERE OFFICE_CD = '@CTRY_CD' ;             ----------------------------             INSERT INTO ACT_FNCL_SOA        SELECT *           FROM ACT_FNCL_SOA@DL_ELVIS         WHERE OFFICE_CD = '@CTRY_CD' ;                UPDATE ACT_FNCL_SOA       SET OFFICE_CD = '@OFFICE_CD'     WHERE OFFICE_CD = '@CTRY_CD' ;	 	 	 ------------------------------		INSERT INTO MDM_OFFICE_EDI	    SELECT * FROM MDM_OFFICE_EDI@DL_ELVIS ;	    	UPDATE MDM_OFFICE_EDI	   SET OFFICE_CD = '@OFFICE_CD'	 WHERE OFFICE_CD = 'ALL' ;	 	 	 END;
#SetupWizard@InsertTempTable
--SetupWizard@InsertTempTableBEGIN	CREATE GLOBAL TEMPORARY TABLE TEMP_OFFICE_LIST	(	  OFFICE_CD  VARCHAR2(10 CHAR)                  NOT NULL	)	ON COMMIT PRESERVE ROWS	NOCACHE;	CREATE GLOBAL TEMPORARY TABLE TEMP_FNCL_BOOK	(	  OFFICE_CD     VARCHAR2(10 CHAR)               NOT NULL,	  TYPE          VARCHAR2(6 CHAR)                NOT NULL,	  SOA_TYPE      VARCHAR2(2 CHAR)                NOT NULL,	  ACCT_CD       VARCHAR2(10 CHAR)               NOT NULL,	  ACCT_NM       VARCHAR2(50 CHAR),	  SEQ           NUMBER(4)                       DEFAULT 0                     NOT NULL,	  PRT_LOC       VARCHAR2(1 CHAR),	  ACCM_ACCT_CD  VARCHAR2(10 CHAR),	  BEF_DR_AMT    NUMBER(15,2)                    DEFAULT 0                     NOT NULL,	  BEF_CR_AMT    NUMBER(15,2)                    DEFAULT 0                     NOT NULL,	  DR_AMT        NUMBER(15,2)                    DEFAULT 0                     NOT NULL,	  CR_AMT        NUMBER(15,2)                    DEFAULT 0                     NOT NULL,	  BAL_DR_AMT    NUMBER(15,2)                    DEFAULT 0                     NOT NULL,	  BAL_CR_AMT    NUMBER(15,2)                    DEFAULT 0                     NOT NULL,	  SUM_DR_AMT    NUMBER(15,2)                    DEFAULT 0                     NOT NULL,	  SUM_CR_AMT    NUMBER(15,2)                    DEFAULT 0                     NOT NULL	)	ON COMMIT PRESERVE ROWS	NOCACHE;END;
#SetupWizard@InsertUser
-- SetupWizard@InsertUserBEGIN 	INSERT INTO MDM_USER_MST (	     USR_ID	   , ENG_NM	   , LOC_NM	   , PSWD	   , GEND	   , HP_NO	   , TEL_NO	   , FAX_NO	   , EMAIL	   , OFFICE_CD	   , DEPT_CD	   , AUTH_TYPE	   , SALES_LVL	   , ACT_LVL	   , USE_YN	   , PSWD_CHG_YMD	   , LOGIN_FAIL_CNT	) VALUES (	     'ADMIN'	   , 'ADMIN-'||'@OFFICE_CD' 	   , 'ADMIN-'||'@OFFICE_CD'	   , UNF_MD5_ENCRYPTION ('@OFFICE_CD'||'121')	   , 'M'	   , '111'	   , '222'	   , '333'	   , 'help@yjit.co.kr'	   , '@OFFICE_CD'	   , 'MGT'	   , '0'	   , 'HQ'	   , 'HQ'	   , 'Y'	   , sysdate	   , 0	 );	 	 DELETE MDM_USER_MST WHERE USR_ID = 'SETUP';	 	 UPDATE SYS_CUST_MST@DL_SYS	    SET NEW_CUST_YN = 'N'	  WHERE DOMAIN = '@DOMAIN';	 END;
