#YjediSpecDetailMgt@Delete
--YjediSpecDetailMgt@DeleteDELETE YJEDI_SPEC_DTL WHERE CUSTOMS_CD = '@CUSTOMS_CD'   AND SYS_ID = '@SYS_ID'   AND SPEC_CD = '@SPEC_CD'   AND SEG = '@SEG'   AND QUAL = '@QUAL'
#YjediSpecDetailMgt@Save
--YjediSpecDetailMgt@Save MERGE INTO YJEDI_SPEC_DTL A USING    (SELECT '@CUSTOMS_CD' AS CUSTOMS_CD          , '@SYS_ID' AS SYS_ID          , '@SPEC_CD' AS SPEC_CD          , '@SPEC_VER' AS SPEC_VER          , '@SEG' AS SEG          , '@QUAL' AS QUAL          , '@SPEC_SEQ' AS SPEC_SEQ          , '@DESCRIPTION' AS DESCRIPTION          , '@ELVIS_DESC' AS ELVIS_DESC          , '@MAND_TYPE' AS MAND_TYPE          , '@DATA_TYPE' AS DATA_TYPE          , '@DATA_LEN' AS DATA_LEN          , '@GROUP_YN' AS GROUP_YN          , '@USE_YN' AS USE_YN          , '@UPPER_SEG' AS UPPER_SEG          , '@UPPER_QUAL' AS UPPER_QUAL          , '@MAP_TBL' AS MAP_TBL          , '@MAP_COL' AS MAP_COL          , '@RMK' AS RMK
          , '@QUAL' AS COL_NM       FROM DUAL) B         ON (A.CUSTOMS_CD = B.CUSTOMS_CD AND A.SYS_ID = B.SYS_ID AND A.SPEC_CD = B.SPEC_CD AND A.SPEC_VER = B.SPEC_VER AND A.SEG = B.SEG AND A.COL_NM = B.COL_NM)       WHEN NOT MATCHED THEN     INSERT (INS_USR           , INS_YMD           , INS_HM           , UPD_USR           , UPD_YMD           , UPD_HM           , CUSTOMS_CD           , SYS_ID           , SPEC_CD           , SPEC_VER           , SEG           , QUAL           , SPEC_SEQ           , DESCRIPTION           , ELVIS_DESC           , MAND_TYPE           , DATA_TYPE           , DATA_LEN           , GROUP_YN           , USE_YN           , UPPER_SEG           , UPPER_QUAL           , MAP_TBL           , MAP_COL
           , COL_NM           , RMK)     VALUES ('@USR_ID'           , UFN_DATE_FORMAT('DATE')           , UFN_DATE_FORMAT('TIME')           , '@USR_ID'           , UFN_DATE_FORMAT('DATE')           , UFN_dATE_FORMAT('TIEM')           , B.CUSTOMS_CD           , B.SYS_ID           , B.SPEC_CD           , B.SPEC_VER           , B.SEG           , B.QUAL           , B.SPEC_SEQ           , B.DESCRIPTION           , B.ELVIS_DESC           , B.MAND_TYPE           , B.DATA_TYPE           , B.DATA_LEN           , B.GROUP_YN           , B.USE_YN           , B.UPPER_SEG           , B.UPPER_QUAL           , B.MAP_TBL           , B.MAP_COL
           , B.COL_NM           , B.RMK)       WHEN MATCHED THEN     UPDATE        SET  UPD_USR = '@USR_ID'           , UPD_YMD = UFN_DATE_FORMAT('DATE')           , UPD_HM = UFN_DATE_FORMAT('TIME')           --, CUSTOMS_CD = B.CUSTOMS_CD           --, SYS_ID = B.SYS_ID           --, SPEC_CD = B.SPEC_CD           --, SPEC_VER = B.SPEC_VER           --, SEG = B.SEG           --, QUAL = B.QUAL           , SPEC_SEQ = B.SPEC_SEQ           , DESCRIPTION = B.DESCRIPTION           , ELVIS_DESC = B.ELVIS_DESC           , MAND_TYPE = B.MAND_TYPE           , DATA_TYPE = B.DATA_TYPE           , DATA_LEN = B.DATA_LEN           , GROUP_YN = B.GROUP_YN           , USE_YN = B.USE_YN           , UPPER_SEG = B.UPPER_SEG           , UPPER_QUAL = B.UPPER_QUAL           , MAP_TBL = B.MAP_TBL           , MAP_COL = B.MAP_COL           , RMK = B.RMK
#YjediSpecDetailMgt@Search
--YjediSpecDetailMgt@SearchSELECT A.CUSTOMS_CD     , A.SYS_ID     , A.SPEC_CD     , A.SPEC_VER     , A.SEG     , A.QUAL     , A.SPEC_SEQ     , A.DESCRIPTION     , A.ELVIS_DESC     , A.MAND_TYPE     , A.DATA_TYPE     , A.DATA_LEN     , A.GROUP_YN     , A.USE_YN     , A.UPPER_SEG     , A.UPPER_QUAL     , A.MAP_TBL     , A.MAP_COL     , A.RMK     , UFN_TABLE_ITEM('USER_NM',A.INS_USR,'L','') AS INS_USR     , TO_CHAR(TO_DATE(A.INS_YMD,'YYYYMMDD'),'YYYY-MM-DD') || ' ' ||       TO_CHAR(TO_DATE(A.INS_HM,'hh24miss'), 'hh24:mi:ss') AS INS_YMD     , UFN_TABLE_ITEM('USER_NM',A.UPD_USR,'L','') AS UPD_USR     , TO_CHAR(TO_DATE(A.UPD_YMD,'YYYYMMDD'),'YYYY-MM-DD') || ' ' ||       TO_CHAR(TO_DATE(A.UPD_HM,'hh24miss'), 'hh24:mi:ss') AS UPD_YMD  FROM YJEDI_SPEC_DTL A WHERE 1 = 1 [CUSTOMS_CD]   AND CUSTOMS_CD = '@CUSTOMS_CD' [/CUSTOMS_CD] [SYS_ID]   AND SYS_ID = '@SYS_ID' [/SYS_ID] [SPEC_CD]   AND SPEC_CD = '@SPEC_CD' [/SPEC_CD] ORDER BY SPEC_CD, SPEC_SEQ
#YjediSpecDetailMgt@SearchChk
--YjediSpecDetailMgt@SearchChkSELECT A.CUSTOMS_CD AS CUSTOMS_CD  FROM YJEDI_SPEC_DTL A WHERE 1 = 1   AND A.CUSTOMS_CD = '@CUSTOMS_CD'
