#SysHelpMgt@ChangeParentNode
-- SysHelpMgt@ChangeParentNodeUPDATE CRM_FAQ_MST   SET PARENT_NODE_ID = '@PARENT_NODE_ID'     , UPD_USR='@UPD_USR' 	 , UPD_DATE= SYSDATE WHERE NODE_ID = '@NODE_ID'
#SysHelpMgt@ChangeParentNodeSys
-- SysHelpMgt@ChangeParentNodeSysUPDATE SYS_FAQ_MST   SET PARENT_NODE_ID = '@PARENT_NODE_ID'     , UPD_USR='@UPD_USR' 	 , UPD_DATE= SYSDATE WHERE NODE_ID = '@NODE_ID'
#SysHelpMgt@CheckNodeForDelete
--SysHelpMgt@CheckNodeForDeleteSELECT NODE_ID 	 , NODE_TYPE 	 , PARENT_NODE_ID 	 , TITLE 	 , CONTENT 	 , LANG_CD	 , INS_USR 	 , INS_DATE 	 , UPD_USR 	 , UPD_DATE FROM CRM_FAQ_MSTWHERE PARENT_NODE_ID = '@NODE_ID'   AND NODE_TYPE='G'
#SysHelpMgt@CheckNodeForDeleteSys
--SysHelpMgt@CheckNodeForDeleteSysSELECT NODE_ID 	 , NODE_TYPE 	 , PARENT_NODE_ID 	 , TITLE 	 , CONTENT 	 , LANG_CD	 , INS_USR 	 , INS_DATE 	 , UPD_USR 	 , UPD_DATE FROM SYS_FAQ_MSTWHERE PARENT_NODE_ID = '@NODE_ID'   AND NODE_TYPE='G'
#SysHelpMgt@DeleteNode
-- SysHelpMgt@DeleteNodeBEGIN	DELETE CRM_FAQ_MST  	 WHERE PARENT_NODE_ID = '@NODE_ID';		DELETE CRM_FAQ_MST	 WHERE NODE_ID='@NODE_ID';END;
#SysHelpMgt@DeleteNodeSys
-- SysHelpMgt@DeleteNodeSysBEGIN	DELETE SYS_FAQ_MST  	 WHERE PARENT_NODE_ID = '@NODE_ID';		DELETE SYS_FAQ_MST	 WHERE NODE_ID='@NODE_ID';END;
#SysHelpMgt@GetChildNodes
-- SysHelpMgt@GetChildNodesSELECT NODE_ID 	 , NODE_TYPE 	 , PARENT_NODE_ID 	 , LANG_CD  FROM CRM_FAQ_MST WHERE (PARENT_NODE_ID='@NODE_ID'         OR NODE_ID='@NODE_ID')    AND NODE_TYPE = 'N'ORDER BY NODE_ID
#SysHelpMgt@GetChildNodesSys
-- SysHelpMgt@GetChildNodesSysSELECT NODE_ID 	 , NODE_TYPE 	 , PARENT_NODE_ID 	 , LANG_CD  FROM SYS_FAQ_MST WHERE (PARENT_NODE_ID='@NODE_ID'         OR NODE_ID='@NODE_ID')    AND NODE_TYPE = 'N'ORDER BY NODE_ID
#SysHelpMgt@GetNewNodeID
--SysHelpMgt@GetNewNodeIDSELECT '@NODE_TYPE'||TO_CHAR(SYSDATE,'YYMMDD')||LPAD(cast(NVL(MAX(SUBSTR(NODE_ID,8,4)),0) AS INT) + 1 ,4,'0000') AS NEW_ID  FROM CRM_FAQ_MSTWHERE SUBSTR(NODE_ID,2,6) = TO_CHAR(SYSDATE,'YYMMDD')
#SysHelpMgt@GetNewNodeIDSys
--SysHelpMgt@GetNewNodeIDSysSELECT '@NODE_TYPE'||TO_CHAR(SYSDATE,'YYMMDD')||LPAD(cast(NVL(MAX(SUBSTR(NODE_ID,8,4)),0) AS INT) + 1 ,4,'0000') AS NEW_ID  FROM SYS_FAQ_MSTWHERE SUBSTR(NODE_ID,2,6) = TO_CHAR(SYSDATE,'YYMMDD')
#SysHelpMgt@GetNode
--SysHelpMgt@GetNodeSELECT *  FROM CRM_FAQ_MST WHERE NODE_ID = '@NODE_ID' 
#SysHelpMgt@GetNodeList
-- SysHelpMgt@GetNodeListSELECT NODE_ID 	 , NODE_TYPE 	 , PARENT_NODE_ID 	 , TITLE 	 , DISPLAY_SEQ	 , LANG_CD	 , INS_USR 	 , INS_DATE 	 , UPD_USR 	 , UPD_DATE FROM CRM_FAQ_MSTWHERE 1=1  [SEARCH_KEY]     AND ( 1=2           OR TITLE LIKE '%@SEARCH_KEY%'           OR CONTENT LIKE '%@SEARCH_KEY%'          )    [/SEARCH_KEY]ORDER BY DISPLAY_SEQ, NODE_ID
#SysHelpMgt@GetNodeListSys
--SysHelpMgt@GetNodeListSysSELECT NODE_ID 	 , NODE_TYPE 	 , PARENT_NODE_ID 	 , TITLE 	 , DISPLAY_SEQ	 , LANG_CD	 , INS_USR 	 , INS_DATE 	 , UPD_USR 	 , UPD_DATE FROM SYS_FAQ_MSTWHERE 1=1  [SEARCH_KEY]     AND ( 1=2           OR TITLE LIKE '%@SEARCH_KEY%'           OR CONTENT LIKE '%@SEARCH_KEY%'          )    [/SEARCH_KEY]ORDER BY DISPLAY_SEQ, NODE_ID
#SysHelpMgt@GetNodeSys
--SysHelpMgt@GetNodeSysSELECT *  FROM SYS_FAQ_MST WHERE NODE_ID = '@NODE_ID' 
#SysHelpMgt@InsertNode
--SysHelpMgt@InsertNodeINSERT INTO CRM_FAQ_MST(	 NODE_ID 	,NODE_TYPE 	,PARENT_NODE_ID 	,TITLE 	,DISPLAY_SEQ	,INS_USR 	,INS_DATE)VALUES (	 '@NODE_ID' 	,'@NODE_TYPE' 	,'@PARENT_NODE_ID' 	,'@TITLE' 	,(SELECT NVL(MAX(DISPLAY_SEQ),0)+1 	    FROM CRM_FAQ_MST 	   WHERE PARENT_NODE_ID='@PARENT_NODE_ID')	,'@INS_USR' 	,SYSDATE)
#SysHelpMgt@InsertNodeSys
--SysHelpMgt@InsertNodeSysINSERT INTO SYS_FAQ_MST(	 NODE_ID 	,NODE_TYPE 	,PARENT_NODE_ID 	,TITLE 	,DISPLAY_SEQ	,INS_USR 	,INS_DATE)VALUES (	 '@NODE_ID' 	,'@NODE_TYPE' 	,'@PARENT_NODE_ID' 	,'@TITLE' 	,(SELECT NVL(MAX(DISPLAY_SEQ),0)+1 	    FROM SYS_FAQ_MST 	   WHERE PARENT_NODE_ID='@PARENT_NODE_ID')	,'@INS_USR' 	,SYSDATE)
#SysHelpMgt@UpdateContent
-- SysHelpMgt@UpdateContentDECLARE    CONT VARCHAR2(32767);BEGIN	CONT :='@CONTENT';	UPDATE CRM_FAQ_MST	   SET NODE_TYPE = '@NODE_TYPE'	     , PARENT_NODE_ID = '@PARENT_NODE_ID'	     , TITLE = '@TITLE'	     , CONTENT=CONT	     , LANG_CD = '@LANG_CD'	     , UPD_USR='@UPD_USR' 	     , UPD_DATE= SYSDATE	 WHERE NODE_ID = '@NODE_ID';END;
#SysHelpMgt@UpdateContentSys
-- SysHelpMgt@UpdateContentSysDECLARE    CONT VARCHAR2(32767);BEGIN	CONT :='@CONTENT';	UPDATE SYS_FAQ_MST	   SET NODE_TYPE = '@NODE_TYPE'	     , PARENT_NODE_ID = '@PARENT_NODE_ID'	     , TITLE = '@TITLE'	     , CONTENT=CONT	     , LANG_CD = '@LANG_CD'	     , UPD_USR='@UPD_USR' 	     , UPD_DATE= SYSDATE	 WHERE NODE_ID = '@NODE_ID';END;
#SysHelpMgt@UpdateTitle
--SysHelpMgt@UpdateTitleUPDATE CRM_FAQ_MST   SET TITLE='@TITLE' 	 , UPD_USR='@UPD_USR' 	 , UPD_DATE= SYSDATE WHERE NODE_ID = '@NODE_ID'	
#SysHelpMgt@UpdateTitleSys
--SysHelpMgt@UpdateTitleSysUPDATE SYS_FAQ_MST   SET TITLE='@TITLE' 	 , UPD_USR='@UPD_USR' 	 , UPD_DATE= SYSDATE WHERE NODE_ID = '@NODE_ID'
