#CrmAsMonthly@Search
--CrmAsMonthly@SearchWITH W_CRM_AS_MST_WORKAS(        SELECT (CASE W.REQ_SVC                     WHEN 'B' THEN '1.FMS' --공통업무                     WHEN 'E' THEN '1.FMS' --해운                     WHEN 'CM' THEN '1.FMS' --CRM                     WHEN 'EP' THEN '1.FMS' --전자결재                     WHEN 'V' THEN '1.FMS' --정산                     WHEN 'G' THEN '1.FMS' --특송업무                     WHEN 'J' THEN '1.FMS' --대리점                     WHEN 'L' THEN '1.FMS' --문서관리                     WHEN 'R' THEN '1.FMS' --해운/항공                     WHEN 'D' THEN '1.FMS' --항공                     WHEN 'C' THEN '2.회계' --회계                     WHEN 'P' THEN '3.EDI' --EDI                                     WHEN 'PR' THEN '5.ETC' --PRIME                     WHEN 'F' THEN '5.ETC' --운송업무                     WHEN 'Z' THEN (CASE WHEN A.REQ_SVC = 'CS' THEN '4.CS' ELSE '5.ETC' END) --ETC                     WHEN 'I' THEN '5.ETC' --운송업무                     WHEN 'CS' THEN '4.CS'                     WHEN 'M' THEN '5.ETC'                     ELSE '5.ETC'                END) AS REQ_SVC_GRP_NM                   , C1.CD_NM AS REQ_SVC_NM             , C1.COMN_CD AS COMN_CD             , (CASE W.REQ_SVC3                     WHEN '02' THEN '신규개발' --2.신규개발                     WHEN '06' THEN '기능개선' --6.기능개선                     WHEN '04' THEN '기능개선' --4.기능추가                     WHEN '05' THEN '기능개선' --5.기능변경                     WHEN '07' THEN '오류수정' --7.오류수정                     WHEN '03' THEN '기타' --3.기능분석                     WHEN '99' THEN '기타' --8.기타
                     ELSE '기타'                END) AS REQ_SVC_GRP_NM3             , C3.CD_NM AS REQ_SVC_NM3             , C3.COMN_CD AS COMN_CD3             , W.PROC_TYPE             , A.REQ_YMD           FROM CRM_AS_MST_WORK W               INNER JOIN CRM_AS_MST A                       ON W.MNGT_NO = A.MNGT_NO                INNER JOIN MDM_COM_CODE C1                       ON W.REQ_SVC = C1.COMN_CD                      AND C1.GRP_CD = 'Z01' --개발팀 업무구분1               INNER JOIN MDM_COM_CODE C3                       ON W.REQ_SVC3 = C3.COMN_CD                      AND C3.GRP_CD = 'Z03' --개발팀 업무구분3          WHERE 1 = 1           AND W.SEQ <> 0
           AND A.REQ_YMD LIKE '@FM_YMD%'          [DEPT_CD]           AND W.DEPT_CD IN ('@DEPT_CD')         [/DEPT_CD]         [DEV_PIC_CD]           AND W.USR_ID IN ('@DEV_PIC_CD')         [/DEV_PIC_CD]), W_CRM_AS_MST_DTLAS(       SELECT A.REQ_SVC_GRP_NM AS WORK_TYPE             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '신규개발' THEN 1 ELSE 0 END),0) AS NEW_DEV             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기능개선' THEN 1 ELSE 0 END),0) AS FUNC_INPR             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '오류수정' THEN 1 ELSE 0 END),0) AS ERR_CORR             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기타' THEN 1 ELSE 0 END),0) AS ETC             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '신규개발' THEN 1                             WHEN A.REQ_SVC_GRP_NM3 = '기능개선' THEN 1                            WHEN A.REQ_SVC_GRP_NM3 = '오류수정' THEN 1                            WHEN A.REQ_SVC_GRP_NM3 = '기타' THEN 1                          END),0) AS SUMM             , NVL(SUM(CASE WHEN A.PROC_TYPE = '1' OR A.PROC_TYPE = '9' THEN 1 ELSE 0 END),0) AS TOTAL_SUMM             , MAX(A.REQ_YMD) AS REQ_YMD        FROM W_CRM_AS_MST_WORK A--        WHERE  A.REQ_YMD LIKE '@FM_YMD%'         GROUP BY A.REQ_SVC_GRP_NM), W_CRM_AS_MST_SUMAS(        SELECT '6.합계' AS WORK_TYPE             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '신규개발' THEN 1 ELSE 0 END),0) AS NEW_DEV             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기능개선' THEN 1 ELSE 0 END),0) AS FUNC_INPR             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '오류수정' THEN 1 ELSE 0 END),0) AS ERR_CORR             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기타' THEN 1 ELSE 0 END),0) AS ETC             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '신규개발' THEN 1 ELSE 0 END),0)               +NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기능개선' THEN 1 ELSE 0 END),0)               +NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '오류수정' THEN 1 ELSE 0 END),0)               +NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기타' THEN 1 ELSE 0 END),0) AS SUMM             , NVL(SUM(CASE WHEN A.PROC_TYPE = '1' OR A.PROC_TYPE = '9' THEN 1 ELSE 0 END),0) AS TOTAL_SUMM             , MAX(A.REQ_YMD) AS REQ_YMD        FROM W_CRM_AS_MST_WORK A--       WHERE A.REQ_YMD LIKE '@FM_YMD%' )SELECT A.WORK_TYPE,A.NEW_DEV,A.FUNC_INPR,A.ERR_CORR,A.ETC,A.SUMM     , ROUND((A.SUMM/NVL((SELECT SUM(Z.SUMM) FROM W_CRM_AS_MST_SUM Z),0))*100,0) AS RATIOFROM W_CRM_AS_MST_DTL AORDER BY 1
#CrmAsMonthly@SearchDetail
--CrmAsMonthly@SearchDetailWITH W_CRM_AS_MST_WORKAS(        SELECT (CASE W.REQ_SVC                     WHEN 'B' THEN '1.FMS' --공통업무                     WHEN 'E' THEN '1.FMS' --해운                     WHEN 'CM' THEN '1.FMS' --CRM                     WHEN 'EP' THEN '1.FMS' --전자결재                     WHEN 'V' THEN '1.FMS' --정산                     WHEN 'G' THEN '1.FMS' --특송업무                     WHEN 'J' THEN '1.FMS' --대리점                     WHEN 'L' THEN '1.FMS' --문서관리                     WHEN 'R' THEN '1.FMS' --해운/항공                     WHEN 'D' THEN '1.FMS' --항공                     WHEN 'C' THEN '2.회계' --회계                     WHEN 'P' THEN '3.EDI' --EDI                                     WHEN 'PR' THEN '5.ETC' --PRIME                     WHEN 'F' THEN '5.ETC' --운송업무                     WHEN 'Z' THEN (CASE WHEN A.REQ_SVC = 'CS' THEN '4.CS' ELSE '5.ETC' END) --ETC                     WHEN 'I' THEN '5.ETC' --운송업무                     WHEN 'CS' THEN '4.CS'                     WHEN 'M' THEN '5.ETC'                     ELSE '5.ETC'                END) AS REQ_SVC_GRP_NM             , C1.CD_NM AS REQ_SVC_NM             , C1.COMN_CD AS COMN_CD             , (CASE W.REQ_SVC3                     WHEN '02' THEN '신규개발' --2.신규개발                     WHEN '06' THEN '기능개선' --6.기능개선                     WHEN '04' THEN '기능개선' --4.기능추가                     WHEN '05' THEN '기능개선' --5.기능변경                     WHEN '07' THEN '오류수정' --7.오류수정                     WHEN '03' THEN '기타' --3.기능분석                     WHEN '99' THEN '기타' --8.기타
                     ELSE '기타'                END) AS REQ_SVC_GRP_NM3             , C3.CD_NM AS REQ_SVC_NM3             , C3.COMN_CD AS COMN_CD3             , W.PROC_TYPE             , A.REQ_YMD           FROM CRM_AS_MST_WORK W               INNER JOIN CRM_AS_MST A                       ON W.MNGT_NO = A.MNGT_NO                INNER JOIN MDM_COM_CODE C1                       ON W.REQ_SVC = C1.COMN_CD                      AND C1.GRP_CD = 'Z01' --개발팀 업무구분1               INNER JOIN MDM_COM_CODE C3                       ON W.REQ_SVC3 = C3.COMN_CD                      AND C3.GRP_CD = 'Z03' --개발팀 업무구분3          WHERE 1 = 1           AND W.SEQ <> 0
           AND A.REQ_YMD LIKE '@FM_YMD%'          [DEPT_CD]           AND W.DEPT_CD IN ('@DEPT_CD')         [/DEPT_CD]         [DEV_PIC_CD]           AND W.USR_ID IN ('@DEV_PIC_CD')         [/DEV_PIC_CD]), W_CRM_AS_MST_DTLAS(       SELECT A.REQ_SVC_GRP_NM AS WORK_TYPE             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '신규개발' THEN 1 ELSE 0 END),0) AS NEW_DEV             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기능개선' THEN 1 ELSE 0 END),0) AS FUNC_INPR             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '오류수정' THEN 1 ELSE 0 END),0) AS ERR_CORR             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기타' THEN 1 ELSE 0 END),0) AS ETC             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '신규개발' THEN 1                             WHEN A.REQ_SVC_GRP_NM3 = '기능개선' THEN 1                            WHEN A.REQ_SVC_GRP_NM3 = '오류수정' THEN 1                            WHEN A.REQ_SVC_GRP_NM3 = '기타' THEN 1                          END),0) AS SUMM             , NVL(SUM(CASE WHEN A.PROC_TYPE = '1' OR A.PROC_TYPE = '9' THEN 1 ELSE 0 END),0) AS TOTAL_SUMM--             , MAX(A.REQ_YMD) AS REQ_YMD        FROM W_CRM_AS_MST_WORK A--        WHERE  A.REQ_YMD LIKE '@FM_YMD%'         GROUP BY A.REQ_SVC_GRP_NM), W_CRM_AS_MST_SUMAS(        SELECT '6.합계' AS WORK_TYPE             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '신규개발' THEN 1 ELSE 0 END),0) AS NEW_DEV             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기능개선' THEN 1 ELSE 0 END),0) AS FUNC_INPR             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '오류수정' THEN 1 ELSE 0 END),0) AS ERR_CORR             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기타' THEN 1 ELSE 0 END),0) AS ETC             , NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '신규개발' THEN 1 ELSE 0 END),0)               +NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기능개선' THEN 1 ELSE 0 END),0)               +NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '오류수정' THEN 1 ELSE 0 END),0)               +NVL(SUM(CASE WHEN A.REQ_SVC_GRP_NM3 = '기타' THEN 1 ELSE 0 END),0) AS SUMM             , NVL(SUM(CASE WHEN A.PROC_TYPE = '1' OR A.PROC_TYPE = '9' THEN 1 ELSE 0 END),0) AS TOTAL_SUMM--             , MAX(A.REQ_YMD) AS REQ_YMD        FROM W_CRM_AS_MST_WORK A--       WHERE A.REQ_YMD LIKE '@FM_YMD%'), W_CRM_AS_MST_SUM_PREVAS(        SELECT '@WORK_TYPE' AS REQ_YMD             , @NEW_DEV AS NEW_DEV             , @FUNC_INPR AS FUNC_INPR             , @ERR_CORR AS ERR_CORR             , @ETC AS ETC             , @SUMM AS SUMM             , @RATIO AS RATIO        FROM DUAL)SELECT '1.'||TO_NUMBER(SUBSTR('@WORK_TYPE',6,2))||'월' AS WORK_TYPE     ,A.NEW_DEV,A.FUNC_INPR,A.ERR_CORR,A.ETC,A.SUMM,A.RATIO 
     ,ROUND(((B.NEW_DEV-A.NEW_DEV)/NVL((CASE WHEN A.NEW_DEV = 0 THEN 1 ELSE A.NEW_DEV END),1))*100,0) AS R_NEW_DEV
     ,ROUND(((B.FUNC_INPR-A.FUNC_INPR)/NVL((CASE WHEN A.FUNC_INPR = 0 THEN 1 ELSE A.FUNC_INPR END),1))*100,0) AS R_FUNC_INPR
     ,ROUND(((B.ERR_CORR-A.ERR_CORR)/NVL((CASE WHEN A.ERR_CORR = 0 THEN 1 ELSE A.ERR_CORR END),1))*100,0) AS R_ERR_CORR
     ,ROUND(((B.ETC-A.ETC)/NVL((CASE WHEN A.ETC = 0 THEN 1 ELSE A.ETC END),1))*100,0) AS R_ETC
     ,ROUND(((B.SUMM-A.SUMM)/NVL((CASE WHEN A.SUMM = 0 THEN 1 ELSE A.SUMM END),1))*100,0) AS R_SUMMFROM W_CRM_AS_MST_SUM_PREV A 
     FULL JOIN W_CRM_AS_MST_SUM B
             ON 1 = 1
UNION ALL SELECT '2.'||TO_NUMBER(SUBSTR('@FM_YMD',5,2))||'월' AS WORK_TYPE     ,A.NEW_DEV,A.FUNC_INPR,A.ERR_CORR,A.ETC,A.SUMM     ,ROUND((NVL(A.TOTAL_SUMM, 0) / NVL((CASE WHEN A.SUMM = 0 THEN 1 ELSE A.SUMM END), 1) * 100))AS RATIO
     ,ROUND(((A.NEW_DEV-B.NEW_DEV)/NVL((CASE WHEN B.NEW_DEV = 0 THEN 1 ELSE B.NEW_DEV END),1))*100,0) AS R_NEW_DEV
     ,ROUND(((A.FUNC_INPR-B.FUNC_INPR)/NVL((CASE WHEN B.FUNC_INPR = 0 THEN 1 ELSE B.FUNC_INPR END),1))*100,0) AS R_FUNC_INPR
     ,ROUND(((A.ERR_CORR-B.ERR_CORR)/NVL((CASE WHEN B.ERR_CORR = 0 THEN 1 ELSE B.ERR_CORR END),1))*100,0) AS R_ERR_CORR
     ,ROUND(((A.ETC-B.ETC)/NVL((CASE WHEN B.ETC = 0 THEN 1 ELSE B.ETC END),1))*100,0) AS R_ETC
     ,ROUND(((A.SUMM-B.SUMM)/NVL((CASE WHEN B.SUMM = 0 THEN 1 ELSE B.SUMM END),1))*100,0) AS R_SUMMFROM W_CRM_AS_MST_SUM A 
     FULL JOIN W_CRM_AS_MST_SUM_PREV B
             ON 1 = 1ORDER BY 1
