#ComDashboard@SearchDev
--ComDashboard@SearchDevSELECT A.USR_ID     , (SELECT MAX(Z.LOC_NM) FROM CRM_USR_MST Z WHERE Z.USR_ID = A.USR_ID) AS USR_NM     , COUNT(CASE WHEN A.PROC_TYPE IN ('7', '8') THEN 1 ELSE NULL END) AS SUM_CNT     , COUNT(CASE WHEN A.PROC_TYPE IN ('1', '9', 'Z') THEN 1 ELSE NULL END) AS SUM_CMPT     , (COUNT(CASE WHEN A.PROC_TYPE IN ('7', '8') THEN 1 ELSE NULL END) + COUNT(CASE WHEN A.PROC_TYPE IN ('1', '9', 'Z') THEN 1 ELSE NULL END)) AS SUM_REQ FROM  CRM_AS_MST_WORK A       INNER JOIN CRM_AS_MST B                ON A.MNGT_NO = B.MNGT_NO       INNER JOIN CRM_USR_MST C                ON A.USR_ID = C.USR_ID WHERE 1=1   AND B.REQ_YMD >= '@FM_YMD'   AND B.REQ_YMD <= '@TO_YMD'   AND A.SEQ <> 0   AND C.DEPT_CD IN ('02', '07')GROUP BY A.USR_ID ORDER BY USR_NM 
#ComDashboard@SearchWorkType
--ComDashboard@SearchWorkType
SELECT X.WORK_TYPE
     , COUNT(*) AS REQ_SUM
     , COUNT(CASE WHEN X.PROC_TYPE = '0' OR X.PROC_TYPE IS NULL THEN 1 END) AS SUM_UNCFM
     , COUNT(CASE WHEN X.PROC_TYPE IN ('7', '8') THEN 1 END) AS SUM_CNT
     , COUNT(CASE WHEN X.PROC_TYPE IN ('1', '9', 'Z') THEN 1 ELSE NULL END) AS SUM_CMPT
     , X.TYPE_SORT
 FROM (
  SELECT A.PROC_TYPE
       , NVL(D.SORT,'25') AS TYPE_SORT
       ,(CASE WHEN A.REQ_SVC IS NULL OR Z.COMN_CD IS NULL
              THEN '기타'
              ELSE D.CD_NM
              END) AS WORK_TYPE
    FROM CRM_AS_MST_WORK A
         INNER JOIN CRM_AS_MST B 
                 ON A.MNGT_NO = B.MNGT_NO
         INNER JOIN CRM_USR_MST C 
                 ON A.USR_ID = C.USR_ID 
         LEFT OUTER JOIN MDM_COM_CODE Z 
                 ON A.REQ_SVC = Z.COMN_CD 
                AND Z.GRP_CD = 'Z01'
         LEFT OUTER JOIN MDM_COM_CODE D 
                 ON Z.OPT_ITEM2 = D.COMN_CD 
                AND D.GRP_CD = 'D01'
    WHERE 1=1
       AND B.REQ_YMD >= '@FM_YMD'
       AND B.REQ_YMD <= '@TO_YMD'
       AND A.SEQ <> 0
       AND C.DEPT_CD IN ('02', '07')
       
UNION ALL
  SELECT A.PROC_TYPE
       , NVL(D.SORT,'25') AS SORT
       ,(CASE WHEN B.REQ_SVC IS NULL OR Z.COMN_CD IS NULL
              THEN '기타'
              ELSE D.CD_NM
              END) AS WORK_TYPE
   FROM CRM_AS_MST_WORK A
        INNER JOIN CRM_AS_MST B 
                ON A.MNGT_NO = B.MNGT_NO
        INNER JOIN CRM_AS_MST_SHARE D 
                ON A.MNGT_NO = D.MNGT_NO
        LEFT OUTER JOIN MDM_COM_CODE Z 
                ON B.REQ_SVC = Z.COMN_CD 
               AND Z.GRP_CD = 'Z01'
        LEFT OUTER JOIN MDM_COM_CODE D 
                ON Z.OPT_ITEM2 = D.COMN_CD 
               AND D.GRP_CD = 'D01'
  WHERE 1 = 1
     AND B.REQ_YMD >= '@FM_YMD'
     AND B.REQ_YMD <= '@TO_YMD'
     AND A.SEQ = 0
     AND D.EXCEPT_YN = 'N'
     AND NOT B.PROC_TYPE IN ('1','2','8')
     AND  EXISTS (SELECT '' FROM CRM_AS_MST_SHARE X WHERE X.MNGT_NO = B.MNGT_NO AND (X.DEPT_CD IN ('02','07') AND X.EXCEPT_YN = 'N'))
     AND  NOT EXISTS (SELECT '' FROM CRM_AS_MST_WORK X WHERE X.MNGT_NO = B.MNGT_NO AND X.SEQ = 1)
) X
GROUP BY X.WORK_TYPE, X.TYPE_SORT
ORDER BY X.TYPE_SORT




#ComDashboard@SearchYear
--ComDashboard@SearchYear
SELECT X.SUM_TYPE
     , SUM(SUM_CMPT_01) AS SUM_CMPT_01
     , SUM(SUM_CMPT_02) AS SUM_CMPT_02
     , SUM(SUM_CMPT_03) AS SUM_CMPT_03
     , SUM(SUM_CMPT_04) AS SUM_CMPT_04
     , SUM(SUM_CMPT_05) AS SUM_CMPT_05
     , SUM(SUM_CMPT_06) AS SUM_CMPT_06
     , SUM(SUM_CMPT_07) AS SUM_CMPT_07
     , SUM(SUM_CMPT_08) AS SUM_CMPT_08
     , SUM(SUM_CMPT_09) AS SUM_CMPT_09
     , SUM(SUM_CMPT_10) AS SUM_CMPT_10
     , SUM(SUM_CMPT_11) AS SUM_CMPT_11
     , SUM(SUM_CMPT_12) AS SUM_CMPT_12
     , X.TYPE_SORT
FROM (
  SELECT 
    (CASE WHEN A.PROC_TYPE = '0' THEN '미확인건'
          WHEN A.PROC_TYPE IN ('7', '8') THEN '진행중건'
          ELSE '완료건'
          END) AS SUM_TYPE
  , (CASE WHEN A.PROC_TYPE = '0' THEN 1
          WHEN A.PROC_TYPE IN ('7', '8') THEN 2
          ELSE 3
          END) AS TYPE_SORT
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '01' THEN 1 ELSE 0 END) AS SUM_CMPT_01
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '02' THEN 1 ELSE 0 END) AS SUM_CMPT_02
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '03' THEN 1 ELSE 0 END) AS SUM_CMPT_03
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '04' THEN 1 ELSE 0 END) AS SUM_CMPT_04
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '05' THEN 1 ELSE 0 END) AS SUM_CMPT_05
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '06' THEN 1 ELSE 0 END) AS SUM_CMPT_06
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '07' THEN 1 ELSE 0 END) AS SUM_CMPT_07
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '08' THEN 1 ELSE 0 END) AS SUM_CMPT_08
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '09' THEN 1 ELSE 0 END) AS SUM_CMPT_09
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '10' THEN 1 ELSE 0 END) AS SUM_CMPT_10
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '11' THEN 1 ELSE 0 END) AS SUM_CMPT_11
  , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '12' THEN 1 ELSE 0 END) AS SUM_CMPT_12
  FROM CRM_AS_MST_WORK A
       INNER JOIN CRM_AS_MST B 
               ON A.MNGT_NO = B.MNGT_NO
       INNER JOIN CRM_USR_MST C 
               ON A.USR_ID = C.USR_ID
  WHERE 1=1
     AND B.REQ_YMD LIKE '@YEAR%' 
     AND A.SEQ <> 0
     AND C.DEPT_CD IN ('02', '07')
        
UNION ALL
  
 SELECT (CASE WHEN A.PROC_TYPE IS NULL 
              THEN '미확인건'
              END) AS SUM_TYPE
     , 1 AS TYPE_SORT
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '01' THEN 1 ELSE 0 END) AS SUM_CMPT_01
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '02' THEN 1 ELSE 0 END) AS SUM_CMPT_02
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '03' THEN 1 ELSE 0 END) AS SUM_CMPT_03
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '04' THEN 1 ELSE 0 END) AS SUM_CMPT_04
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '05' THEN 1 ELSE 0 END) AS SUM_CMPT_05
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '06' THEN 1 ELSE 0 END) AS SUM_CMPT_06
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '07' THEN 1 ELSE 0 END) AS SUM_CMPT_07
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '08' THEN 1 ELSE 0 END) AS SUM_CMPT_08
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '09' THEN 1 ELSE 0 END) AS SUM_CMPT_09
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '10' THEN 1 ELSE 0 END) AS SUM_CMPT_10
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '11' THEN 1 ELSE 0 END) AS SUM_CMPT_11
     , (CASE WHEN SUBSTR(B.REQ_YMD, 5, 2) = '12' THEN 1 ELSE 0 END) AS SUM_CMPT_12
  FROM CRM_AS_MST_WORK A
       INNER JOIN CRM_AS_MST B 
               ON A.MNGT_NO = B.MNGT_NO
       INNER JOIN CRM_AS_MST_SHARE D 
               ON A.MNGT_NO = D.MNGT_NO
   WHERE 1 = 1
      AND B.REQ_YMD LIKE '@YEAR%' 
      AND A.SEQ = 0
      AND D.EXCEPT_YN = 'N'
      AND NOT B.PROC_TYPE IN ('1','2','8')
      AND EXISTS (SELECT '' FROM CRM_AS_MST_SHARE X WHERE X.MNGT_NO = B.MNGT_NO AND (X.DEPT_CD IN ('02','07') AND X.EXCEPT_YN = 'N'))
      AND NOT EXISTS (SELECT '' FROM CRM_AS_MST_WORK X WHERE X.MNGT_NO = B.MNGT_NO AND X.SEQ = 1)
) X 
GROUP BY X.SUM_TYPE, X.TYPE_SORT
ORDER BY X.TYPE_SORT

#ComDashboard@TotalSearch
--ComDashboard@TotalSearch
SELECT SUM(X.SUM_UNCFM + X.SUM_CNT + X.SUM_CMPT) AS SUM_REQ
     , SUM(X.SUM_UNCFM) AS SUM_UNCFM
     , SUM(X.SUM_CNT) AS SUM_CNT
     , SUM(X.SUM_CMPT) AS SUM_CMPT
FROM (
    SELECT 
           COUNT(CASE WHEN A.PROC_TYPE = '0' THEN 1 ELSE NULL END) AS SUM_UNCFM
         , COUNT(CASE WHEN A.PROC_TYPE IN ('7', '8') THEN 1 ELSE NULL END) AS SUM_CNT
         , COUNT(CASE WHEN A.PROC_TYPE IN ('1', '9', 'Z') THEN 1 ELSE NULL END) AS SUM_CMPT  
     FROM  CRM_AS_MST_WORK A
           INNER JOIN CRM_AS_MST B 
                   ON A.MNGT_NO = B.MNGT_NO
           INNER JOIN CRM_USR_MST C 
                   ON A.USR_ID = C.USR_ID 
    WHERE 1=1
       AND B.REQ_YMD >= '@FM_YMD'
      AND B.REQ_YMD <= '@TO_YMD'
       AND A.SEQ <> 0
       AND C.DEPT_CD IN ('02', '07')
    UNION ALL
    SELECT COUNT(DISTINCT A.MNGT_NO)
            , 0 AS SUM_CNT
            , 0 AS SUM_CMPT
    FROM CRM_AS_MST_WORK A
    INNER JOIN CRM_AS_MST B ON A.MNGT_NO = B.MNGT_NO
    INNER JOIN CRM_AS_MST_SHARE D ON A.MNGT_NO = D.MNGT_NO
    WHERE 1 = 1
      AND B.REQ_YMD >= '@FM_YMD'
      AND B.REQ_YMD <= '@TO_YMD'
      AND A.SEQ = 0
     AND D.EXCEPT_YN = 'N'
      AND NOT B.PROC_TYPE IN ('1','2','8')
     AND  EXISTS (SELECT '' FROM CRM_AS_MST_SHARE X WHERE X.MNGT_NO = B.MNGT_NO AND (X.DEPT_CD IN ('02','07') AND X.EXCEPT_YN = 'N'))
          AND  NOT EXISTS (SELECT '' FROM CRM_AS_MST_WORK X WHERE X.MNGT_NO = B.MNGT_NO AND X.SEQ = 1)
) X          
