#CrmTwmsMgt@CUST_CHK
--CrmTwmsMgt@CUST_CHKselect CUST_CDFROM WMS_DB_INFOWHERE CUST_CD = '@CUST_CD'
#CrmTwmsMgt@Delete
DELETE FROM WMS_DB_INFO WHERE CUST_CD = '@CUST_CD'
#CrmTwmsMgt@Insert
INSERT INTO WMS_DB_INFO (         CUST_CD,		 CUST_NM,		 IP_ADDRESS,		 PORT_NO,		 SID_NAME,         SCHEMA_ID,         SCHEMA_PW,         VERSION,         INS_ID,         INS_PW,         SCHEMA,         WEBIP,         EDI_USERID,         EDI_USERPW,         NPKI_PW,         RMK,         MAIL_BOX_ID,         REG_NO,         WH_CODE,         GBUN,         SERVER,         USE_YN,         INP_DT,         INP_USR,         TAX_YN,         VPN_ID,         VPN_PW,         LOADER_LOC,         UNIPASS_YN,         AT_LOADER_LOC,		 ATLAS_YN,	 	 KTNET_ID,	 	 KTNET_PW	 ) VALUES (	     '@CUST_CD',		 '@CUST_NM',		 '@IP_ADDRESS',		 '@PORT_NO',		 '@SID_NAME',         '@SCHEMA_ID',         '@SCHEMA_PW',         '@VERSION',         '@INS_ID',         '@INS_PW',         '@SCHEMA',         '@WEBIP',         '@EDI_USERID',         '@EDI_USERPW',         '@NPKI_PW',         '@RMK',         '@MAIL_BOX_ID',         '@REG_NO',         '@WH_CODE',         '@GBUN',         '@SERVER',         '@USE_YN',         SYSDATE,         '@INP_USR',         '@TAX_YN',         '@VPN_ID',         '@VPN_PW',         '@LOADER_LOC',         '@UNIPASS_YN',         '@AT_LOADER_LOC',		 '@ATLAS_YN',	 	 '@KTNET_ID',	 	 '@KTNET_PW')
#CrmTwmsMgt@Search
-- CrmTwmsMgt@Searchselect W.CUST_CD,W.CUST_NM,W.IP_ADDRESS,W.PORT_NO,W.SID_NAME,W.SCHEMA_ID,W.SCHEMA_PW,W.VERSION,W.INS_ID,W.INS_PW,W.SCHEMA,W.WEBIP,W.EDI_USERID,W.EDI_USERPW,W.NPKI_PW,W.RMK,W.MAIL_BOX_ID,W.REG_NO,W.WH_CODE,--CASE WHEN W.GBUN = 'W' THEN '보세창고'--     WHEN W.GBUN = 'G' THEN '일반창고'--     WHEN W.GBUN = 'B' THEN '영업창고'--     WHEN W.GBUN = 'T' THEN '운송'--     WHEN W.GBUN = 'C' THEN 'CFS'--     WHEN W.GBUN = 'Y' THEN 'CY'--     END --     AS GBUN,             W.GBUN,W.SERVER,W.USE_YN,W.INP_DT,W.INP_USR,W.UPD_DT,W.UPD_USR,W.TAX_YN,W.VPN_ID,W.VPN_PW,A.CUST_CD AS CHK_CUST_CD,W.LOADER_LOC,W.UNIPASS_YN,W.AT_LOADER_LOC,W.ATLAS_YN,W.KTNET_ID,W.KTNET_PW,A.CTRT_AMT,A.MATN_AMT,A.IDC_AMT,A.LICENSE_AMT,A.USER_QTY,(SELECT MAX(Z.OUTSTAND_AMT) FROM ACT_CUST_OUTSTAND Z WHERE Z.CRN = REPLACE(A.CRN, '-', '')) AS OUTSTAND_AMT,(SELECT MAX(Z.TAX_AMT) FROM ACT_CUST_OUTSTAND Z WHERE Z.CRN = REPLACE(A.CRN, '-', '')) AS TAX_AMT,
A.CUST_ADDR,
A.TEL_NO,
A.CEO,
A.ETC_AMT_INFOFROM WMS_DB_INFO W      LEFT OUTER JOIN CRM_CUST_MST A  ON W.CUST_CD = A.CUST_CDWHERE 1=1[SEARCH_KEY]   AND ( 1 != 1	   OR A.CUST_CD LIKE '%@SEARCH_KEY%'	   OR A.CUST_NM LIKE '%@SEARCH_KEY%'	   OR A.CUST_LOC_NM LIKE '%@SEARCH_KEY%'	   OR A.DOMAIN LIKE '%@SEARCH_KEY%' 		   OR A.TEL_NO LIKE '%@SEARCH_KEY%'	   OR A.CUSTOMS_CD LIKE '%@SEARCH_KEY%'	   OR A.CUST_CD IN (	   	    SELECT X.CUST_CD 	   	      FROM CRM_CUST_PIC X	   	     WHERE (X.PIC_NM LIKE '%@SEARCH_KEY%'	   	          OR X.TEL_NO LIKE '%@SEARCH_KEY%'   	   	          )	      )   	   OR A.CUST_CD IN (	   	    SELECT X.CUST_CD 	   	      FROM CRM_CUST_PIC X	   	     WHERE X.TEL_NO LIKE '%@SEARCH_KEY%'	      )   	   OR A.CUST_CD IN (	        SELECT X.CUST_CD	          FROM CRM_CUST_SERVER X	         WHERE PKG_CRYPTO.DECRYPT(X.SVR_IP,'@CRYPTO_KEY' || 'Key!//////////////#^') LIKE '%@SEARCH_KEY%'	   	      )	   OR W.IP_ADDRESS LIKE '%@SEARCH_KEY%'	   OR W.WEBIP LIKE '%@SEARCH_KEY%'	   OR W.IP_ADDRESS LIKE '@CRYPTO_KEY'	   OR W.WEBIP LIKE '@CRYPTO_KEY'	   	)[/SEARCH_KEY][SVC_CD]    --AND A.SVC_CD = '@SVC_CD'    AND A.CUST_CD IN (SELECT CUST_CD FROM CRM_CUST_SVC WHERE SVC_CD = '@SVC_CD')[/SVC_CD][USE_YN]    AND W.USE_YN = '@USE_YN'[/USE_YN][CUST_TYPE]    AND A.CUST_TYPE = '@CUST_TYPE'[/CUST_TYPE][CUST_CD]    AND W.CUST_CD = '@CUST_CD'[/CUST_CD][GBUN]    AND W.GBUN = '@GBUN'[/GBUN][UNIPASS_YN]    AND W.UNIPASS_YN = '@UNIPASS_YN'[/UNIPASS_YN] ORDER BY W.USE_YN DESC, W.CUST_NM,A.CUST_CD
#CrmTwmsMgt@Search_Detail
--CrmCustomerMgt@SearchServerSELECT      MAX((SELECT MAX(PKG_CRYPTO.DECRYPT(A.SVR_IP,'@CRYPTO_KEY' || 'Key!///#^')) FROM CRM_CUST_SERVER WHERE SVR_TYPE = 'D' AND CUST_CD = '@CUST_CD')) AS IP_ADDRESS,     MAX((SELECT MAX(PKG_CRYPTO.DECRYPT(A.SVR_IP,'@CRYPTO_KEY' || 'Key!///#^')) FROM CRM_CUST_SERVER WHERE SVR_TYPE = 'A' AND CUST_CD = '@CUST_CD')) AS WEB_IP,          MAX(PKG_CRYPTO.DECRYPT(A.DB_PORT,'@CRYPTO_KEY' || 'Key!///#^')) AS PORT_NO,     MAX(PKG_CRYPTO.DECRYPT(A.DB_SID,'@CRYPTO_KEY' || 'Key!///#^')) AS SID_NAME,     MAX(PKG_CRYPTO.DECRYPT(A.DB_ID,'@CRYPTO_KEY' || 'Key!///#^')) AS SCHEMA_ID,     MAX(PKG_CRYPTO.DECRYPT(A.DB_PWD,'@CRYPTO_KEY' || 'Key!///#^')) AS SCHEMA_PW  FROM CRM_CUST_SERVER A WHERE A.CUST_CD = '@CUST_CD'  AND SVR_TYPE = 'D'
#CrmTwmsMgt@Update
UPDATE WMS_DB_INFOSET         		 CUST_NM = '@CUST_NM',		 IP_ADDRESS = '@IP_ADDRESS',		 PORT_NO = '@PORT_NO',		 SID_NAME = '@SID_NAME',         SCHEMA_ID = '@SCHEMA_ID',         SCHEMA_PW = '@SCHEMA_PW',         VERSION = '@VERSION',         INS_ID = '@INS_ID',         INS_PW = '@INS_PW',         SCHEMA = '@SCHEMA',         WEBIP = '@WEBIP',         EDI_USERID = '@EDI_USERID',         EDI_USERPW = '@EDI_USERPW',         NPKI_PW = '@NPKI_PW',         RMK = '@RMK',         MAIL_BOX_ID = '@MAIL_BOX_ID',         REG_NO = '@REG_NO',         WH_CODE = '@WH_CODE',         GBUN = '@GBUN',         SERVER = '@SERVER',         USE_YN= '@USE_YN',         UPD_USR ='@UPD_USR',         UPD_DT = SYSDATE,         TAX_YN = '@TAX_YN',         VPN_ID = '@VPN_ID',         VPN_PW = '@VPN_PW',         LOADER_LOC = '@LOADER_LOC',         UNIPASS_YN = '@UNIPASS_YN',         AT_LOADER_LOC = '@AT_LOADER_LOC',		 ATLAS_YN = '@ATLAS_YN',	 	 KTNET_ID = '@KTNET_ID',	 	 KTNET_PW = '@KTNET_PW'WHERE CUST_CD = '@CUST_CD'
