#CrmYoutubeMgt@Delete
--CrmYoutubeMgt@DeleteDELETE  FROM CRM_YOUTUBE_MST WHERE BOARD_ID = '@BOARD_ID'
#CrmYoutubeMgt@Save
--CrmYoutubeMgt@SaveMERGE INTO CRM_YOUTUBE_MST DUSING (       SELECT '@BOARD_ID' AS BOARD_ID            , '@BOARD_TYPE' AS BOARD_TYPE            , '@BOARD_TITLE' AS BOARD_TITLE            , '@BOARD_BODY' AS BOARD_BODY            , '@YOUTUBE_CODE' AS YOUTUBE_CODE            , '@YOUTUBE_URL' AS YOUTUBE_URL            , '@SSN_USR_ID' AS INS_USR            , TO_CHAR(SYSDATE,'yyyyMMdd') AS INS_YMD            , TO_CHAR(SYSDATE,'HH24MISS') AS INS_HM            , '@SSN_USR_ID' AS UPD_USR            , TO_CHAR(SYSDATE,'yyyyMMdd') AS UPD_YMD            , TO_CHAR(SYSDATE,'HH24MISS') AS UPD_HM         FROM DUAL      ) S ON (D.BOARD_ID = S.BOARD_ID)WHEN MATCHED THEN     UPDATE         SET D.UPD_USR = S.UPD_USR          , D.UPD_YMD = S.UPD_YMD          , D.UPD_HM = S.UPD_HM       [BOARD_TYPE], D.BOARD_TYPE = S.BOARD_TYPE[/BOARD_TYPE]       [BOARD_TITLE], D.BOARD_TITLE = S.BOARD_TITLE[/BOARD_TITLE]       [BOARD_BODY], D.BOARD_BODY = S.BOARD_BODY[/BOARD_BODY]       [YOUTUBE_CODE], D.YOUTUBE_CODE = S.YOUTUBE_CODE[/YOUTUBE_CODE]       [YOUTUBE_URL], D.YOUTUBE_URL = S.YOUTUBE_URL[/YOUTUBE_URL]WHEN NOT MATCHED THEN     INSERT (         D.INS_USR, D.INS_YMD, D.INS_HM       , D.UPD_USR, D.UPD_YMD, D.UPD_HM       , D.BOARD_ID       [BOARD_TYPE], D.BOARD_TYPE[/BOARD_TYPE]       [BOARD_TITLE], D.BOARD_TITLE[/BOARD_TITLE]       [BOARD_BODY], D.BOARD_BODY[/BOARD_BODY]       [YOUTUBE_CODE], D.YOUTUBE_CODE[/YOUTUBE_CODE]       [YOUTUBE_URL], D.YOUTUBE_URL[/YOUTUBE_URL]     ) VALUES (         S.INS_USR, S.INS_YMD, S.INS_HM       , S.UPD_USR, S.UPD_YMD, S.UPD_HM       , (SELECT LPAD(NVL(MAX(Z.BOARD_ID),0)+1,8,'0') FROM CRM_YOUTUBE_MST Z)       [BOARD_TYPE], S.BOARD_TYPE[/BOARD_TYPE]       [BOARD_TITLE], S.BOARD_TITLE[/BOARD_TITLE]       [BOARD_BODY], S.BOARD_BODY[/BOARD_BODY]       [YOUTUBE_CODE], S.YOUTUBE_CODE[/YOUTUBE_CODE]       [YOUTUBE_URL], S.YOUTUBE_URL[/YOUTUBE_URL]     )
#CrmYoutubeMgt@Search
--CrmYoutubeMgt@SearchSELECT A.BOARD_ID     , A.BOARD_TYPE     , A.BOARD_TITLE     , A.BOARD_BODY     , A.YOUTUBE_CODE     , A.YOUTUBE_URL     , (SELECT B.LOC_NM FROM CRM_USR_MST B WHERE B.USR_ID = A.INS_USR) AS INS_USR     , TO_CHAR(TO_DATE(A.INS_YMD,'YYYYMMDD'),'YYYY-MM-DD') || ' ' ||       TO_CHAR(TO_DATE(A.INS_HM,'HH24MISS'), 'HH24:MI:SS') AS INS_YMD     , (SELECT B.LOC_NM FROM CRM_USR_MST B WHERE B.USR_ID = A.UPD_USR) AS UPD_USR     , TO_CHAR(TO_DATE(A.UPD_YMD,'YYYYMMDD'),'YYYY-MM-DD') || ' ' ||       TO_CHAR(TO_DATE(A.UPD_HM,'HH24MISS'), 'HH24:MI:SS') AS UPD_YMD  FROM CRM_YOUTUBE_MST A WHERE 1 = 1
 [BOARD_ID]   AND A.BOARD_ID = '@BOARD_ID' [/BOARD_ID]
 [DATE_TYPE_REG]
   [DATE_FM]
     AND A.INS_YMD >= '@DATE_FM'
   [/DATE_FM]   [DATE_FM]
     AND A.INS_YMD <= '@DATE_TO'
   [/DATE_FM]
 [/DATE_TYPE_REG] [BOARD_TYPE]
   AND A.BOARD_TYPE = '@BOARD_TYPE'
 [/BOARD_TYPE]
 [SEARCH_KEY]
   [SEARCH_TYPE_A]
     AND (A.BOARD_TITLE LIKE '%@SEARCH_KEY%'
          OR DBMS_LOB.INSTR(A.BOARD_BODY, '@SEARCH_KEY') > 0
          OR A.INS_USR IN (SELECT Z.USR_ID FROM CRM_USR_MST Z WHERE LOC_NM LIKE '%@SEARCH_KEY%'))
   [/SEARCH_TYPE_A]
   [SEARCH_TYPE_T]
     AND A.BOARD_TITLE LIKE '%@SEARCH_KEY%'
   [/SEARCH_TYPE_T]
   [SEARCH_TYPE_B]
     AND DBMS_LOB.INSTR(A.BOARD_BODY, '@SEARCH_KEY') > 0
   [/SEARCH_TYPE_B]
   [SEARCH_TYPE_U]
     AND A.INS_USR IN (SELECT Z.USR_ID FROM CRM_USR_MST Z WHERE LOC_NM LIKE '%@SEARCH_KEY%')
   [/SEARCH_TYPE_U]
 [/SEARCH_KEY] ORDER BY A.BOARD_ID DESC
