#MdmExrateMgt_v1@Check
--MdmExrateMgt_v1@CheckSELECT BASE_CURR   FROM MDM_EX_RATE WHERE OFFICE_CD 	= '@OFFICE_CD'		AND	BASE_CURR	= '@BASE_CURR'    		AND EXRT_YMD 	= '@CURR_DATE'
#MdmExrateMgt_v1@CN_Copy
--MdmExrateMgt_v1@CopyBEGIN	    DELETE MDM_EX_RATE WHERE  OFFICE_CD 	= '@OFFICE_CD'			AND	BASE_CURR	= '@BASE_CURR' 	   		AND EXRT_YMD 	= '@CURR_DATE';   		INSERT INTO MDM_EX_RATE(			OFFICE_CD		, BASE_CURR		, CURR_CD			, EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT		, CASH_SELLRT	, WIRE_SEND_EXRT	, WIRE_RECV_EXRT	, EXCH_BASERT		  , USD_CONV_RT		, INS_USR		, INS_YMD			, INS_HM			, UPD_USR		  , UPD_YMD			, UPD_HM		  )	 SELECT OFFICE_CD	 	  , BASE_CURR	 	  , CURR_CD	 	  , '@CURR_DATE'	 	  , CURR_UNIT	 	  ,	CASH_BUYRT	 	  , CASH_SELLRT	 	  , WIRE_SEND_EXRT	 	  , WIRE_RECV_EXRT	 	  , EXCH_BASERT	 	  , USD_CONV_RT	 	  , '@USR_ID'	 	  , UFN_DATE_FORMAT('DATE')	 	  , UFN_DATE_FORMAT('TIME')	 	  , '@USR_ID'		  , UFN_DATE_FORMAT('DATE')		  , UFN_DATE_FORMAT('TIME') 	   FROM MDM_EX_RATE  	  WHERE OFFICE_CD 	= '@OFFICE_CD'		AND	BASE_CURR	= '@BASE_CURR'    		AND EXRT_YMD 	= '@EXRT_YMD';END ;
#MdmExrateMgt_v1@Copy
--MdmExrateMgt_v1@CopyBEGIN	INSERT INTO MDM_EX_RATE(			OFFICE_CD		, BASE_CURR		, CURR_CD			, EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT		, CASH_SELLRT	, WIRE_SEND_EXRT	, WIRE_RECV_EXRT	, EXCH_BASERT		  , USD_CONV_RT		, INS_USR		, INS_YMD			, INS_HM			, UPD_USR		  , UPD_YMD			, UPD_HM        		  )	 SELECT OFFICE_CD	 	  , BASE_CURR	 	  , CURR_CD	 	  , '@CURR_DATE'	 	  , CURR_UNIT	 	  ,	CASH_BUYRT	 	  , CASH_SELLRT	 	  , WIRE_SEND_EXRT	 	  , WIRE_RECV_EXRT	 	  , EXCH_BASERT	 	  , USD_CONV_RT	 	  , '@USR_ID'	 	  , UFN_DATE_FORMAT('DATE')	 	  , UFN_DATE_FORMAT('TIME')	 	  , '@USR_ID'		  , UFN_DATE_FORMAT('DATE')		  , UFN_DATE_FORMAT('TIME') 	   FROM MDM_EX_RATE  	  WHERE OFFICE_CD 	= '@OFFICE_CD'		AND	BASE_CURR	= '@BASE_CURR'    		AND EXRT_YMD 	= '@EXRT_YMD';   			INSERT INTO MDM_EX_RATE2(			OFFICE_CD		, BASE_CURR		, CURR_CD			, EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT		, CASH_SELLRT	, WIRE_SEND_EXRT	, WIRE_RECV_EXRT	, EXCH_BASERT		  , USD_CONV_RT		, SEQ		  , INS_USR			, INS_YMD		, INS_HM			, UPD_USR		  , UPD_YMD			, UPD_HM        		  )	 SELECT OFFICE_CD	 	  , BASE_CURR	 	  , CURR_CD	 	  , '@CURR_DATE'	 	  , CURR_UNIT	 	  ,	CASH_BUYRT	 	  , CASH_SELLRT	 	  , WIRE_SEND_EXRT	 	  , WIRE_RECV_EXRT	 	  , EXCH_BASERT	 	  , USD_CONV_RT	 	  , SEQ	 	  , '@USR_ID'	 	  , UFN_DATE_FORMAT('DATE')	 	  , UFN_DATE_FORMAT('TIME')	 	  , '@USR_ID'		  , UFN_DATE_FORMAT('DATE')		  , UFN_DATE_FORMAT('TIME') 	   FROM MDM_EX_RATE2  	  WHERE OFFICE_CD 	= '@OFFICE_CD'		AND	BASE_CURR	= '@BASE_CURR'    		AND EXRT_YMD 	= '@EXRT_YMD';   		   		END ;
#MdmExrateMgt_v1@Delete
--MdmExrateMgt_v1@DeleteDELETE MDM_EX_RATE WHERE OFFICE_CD	= '@OFFICE_CD'   AND BASE_CURR 	= '@BASE_CURR'   AND CURR_CD 		= '@CURR_CD'   AND EXRT_YMD 	= '@EXRT_YMD'
#MdmExrateMgt_v1@Delete2
--MdmExrateMgt_v1@Delete2DELETE MDM_EX_RATE2 WHERE OFFICE_CD	= '@OFFICE_CD'   AND BASE_CURR 	= '@BASE_CURR'   AND CURR_CD 		= '@CURR_CD'   AND EXRT_YMD 	= '@EXRT_YMD'   AND SEQ			= LPAD('@SEQ', 3, '0')
#MdmExrateMgt_v1@DeleteAll
--MdmExrateMgt_v1@DeleteAllBEGIN	DELETE MDM_EX_RATE	 WHERE EXRT_YMD	 = '@EXRT_YMD'	   AND OFFICE_CD = '@OFFICE_CD'	   AND BASE_CURR = '@BASE_CURR';	 	DELETE MDM_EX_RATE2	 WHERE EXRT_YMD	 = '@EXRT_YMD'	   AND OFFICE_CD = '@OFFICE_CD'	   AND BASE_CURR = '@BASE_CURR';   --  AND SEQ 		 = '001';	 END;	    
#MdmExrateMgt_v1@DeleteMonthly
-- MdmExrateMgt_v1@DeleteMonthlyDELETE MDM_MM_EX_RATE WHERE OFFICE_CD	= '@OFFICE_CD'   AND BASE_CURR 	= '@BASE_CURR'   AND CURR_CD 		= '@CURR_CD'   AND EXRT_MM 	= '@EXRT_MM'
#MdmExrateMgt_v1@GetExRate
/* Local Amount Value Search */ -- 2012.01.17SELECT NVL(CASE WHEN '@CURR_CLS' = 'A' THEN A.EXCH_BASERT                WHEN '@CURR_CLS' = 'B' THEN A.CASH_BUYRT	                WHEN '@CURR_CLS' = 'C' THEN A.CASH_SELLRT	                WHEN '@CURR_CLS' = 'D' THEN A.WIRE_SEND_EXRT                WHEN '@CURR_CLS' = 'E' THEN A.WIRE_RECV_EXRT           END, 1) AS EX_RATE,      (SELECT NVL(CASE WHEN '@CURR_CLS' = 'A' THEN B.EXCH_BASERT                       WHEN '@CURR_CLS' = 'B' THEN B.CASH_BUYRT	                       WHEN '@CURR_CLS' = 'C' THEN B.CASH_SELLRT	                       WHEN '@CURR_CLS' = 'D' THEN B.WIRE_SEND_EXRT                       WHEN '@CURR_CLS' = 'E' THEN B.WIRE_RECV_EXRT                  END, 1)        FROM   MDM_EX_RATE B        WHERE  B.BASE_CURR = A.BASE_CURR        AND    B.CURR_CD   = 'USD'        AND    B.EXRT_YMD  = A.EXRT_YMD       AND    B.OFFICE_CD = '@OFFICE_CD') AS USD_EX_RATE,       A.CURR_UNITFROM   MDM_EX_RATE AWHERE  A.BASE_CURR = '@BASE_CURR' --SESSION("Currency")AND    A.CURR_CD   = '@CURR_CD'   --CURR_CD  AND    A.EXRT_YMD  = '@EXRT_YMD'AND    A.OFFICE_CD = '@OFFICE_CD' 
#MdmExrateMgt_v1@Insert
--MdmExrateMgt_v1@InsertBEGIN  	INSERT INTO MDM_EX_RATE(			OFFICE_CD	    	, BASE_CURR		, CURR_CD					  , EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT			, CASH_SELLRT			  , WIRE_SEND_EXRT		, WIRE_RECV_EXRT			  , EXCH_BASERT         , USD_CONV_RT	, RMK			  , INS_USR				, INS_YMD			, INS_HM					  , UPD_USR  			, UPD_YMD			, UPD_HM			  )     VALUES (			'@OFFICE_CD'			, '@BASE_CURR'			, '@CURR_CD'					      , '@EXRT_YMD'				, @CURR_UNIT		  , @CASH_BUYRT				, @CASH_SELLRT		  , @WIRE_SEND_EXRT			, @WIRE_RECV_EXRT		  , @EXCH_BASERT		  , @USD_CONV_RT            , '@RMK'		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	 	, UFN_DATE_FORMAT('TIME')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	    , UFN_DATE_FORMAT('TIME')		  ) ;		  END;
#MdmExrateMgt_v1@Insert2
--MdmExrateMgt_v1@Insert2BEGIN  	INSERT INTO MDM_EX_RATE2(			OFFICE_CD	    	, BASE_CURR		, CURR_CD					  , EXRT_YMD			, CURR_UNIT		  , CASH_BUYRT			, CASH_SELLRT			  , WIRE_SEND_EXRT		, WIRE_RECV_EXRT			  , EXCH_BASERT         		  , USD_CONV_RT			, RMK				, SEQ		  , INS_USR				, INS_YMD			, INS_HM					  , UPD_USR  			, UPD_YMD			, UPD_HM			  )     VALUES (			'@OFFICE_CD'			, '@BASE_CURR'			, '@CURR_CD'					      , '@EXRT_YMD'				, @CURR_UNIT		  , @CASH_BUYRT				, @CASH_SELLRT		  , @WIRE_SEND_EXRT			, @WIRE_RECV_EXRT		  , @EXCH_BASERT		  , @USD_CONV_RT            , '@RMK'					, LPAD('@SEQ', 3, '0')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	 	, UFN_DATE_FORMAT('TIME')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	    , UFN_DATE_FORMAT('TIME')		  ) ;		  END ;
#MdmExrateMgt_v1@InsertAS
-- MdmExrateMgt_v1@InsertAS    INSERT INTO CRM_AS_MST (            INS_USR      , INS_YMD          , INS_HM          , UPD_USR      , UPD_YMD          , UPD_HM          , REQ_YMD      , REQ_HM          , SYS_ID       , FORM_ID          , MNGT_NO            , REQ_SVC             , CUST_CD           , CONTENT                 , REQ_USR              , TEL_NO             , PROC_TYPE                  , WORK_USR            , PRAR_YMD             , CMPT_YMD                , PRIORITY               , FREE_YN             , REQ_TYPE            , CMPT_RMK           , REQ_SVC2                 )        VALUES (            'ADMIN'    , TO_CHAR(SYSDATE,'YYYYMMDD'),    TO_CHAR(SYSDATE,'HH24MISS')          , 'ADMIN'    , TO_CHAR(SYSDATE,'YYYYMMDD'),    TO_CHAR(SYSDATE,'HH24MISS')          , TO_CHAR(SYSDATE,'YYYYMMDD')    , TO_CHAR(SYSDATE,'HH24MISS')          , 'ELVIS'    , 'ComRequestMgt'          , '@MNGT_NO'                     ,'Z'                     ,'YJIT'                   ,'@CONTENT'                   ,'ADMIN'                    ,''                      ,'0'                  ,''                 ,''          ,''          ,'0'                  ,'Y'                      ,''                  ,''                 ,'R005'                        )
#MdmExrateMgt_v1@InsertMonthly
-- MdmExrateMgt_v1@InsertMonthlyBEGIN  	INSERT INTO MDM_MM_EX_RATE(			OFFICE_CD	    	, BASE_CURR		, CURR_CD					  , EXRT_MM			    , CURR_UNIT		  , CASH_BUYRT			, CASH_SELLRT			  , WIRE_SEND_EXRT		, WIRE_RECV_EXRT			  , EXCH_BASERT         , USD_CONV_RT				  , INS_USR				, INS_YMD			, INS_HM					  , UPD_USR  			, UPD_YMD			, UPD_HM			  )     VALUES (			'@OFFICE_CD'			, '@BASE_CURR'			, '@CURR_CD'					      , '@EXRT_MM'				, @CURR_UNIT		  , NVL(@CASH_BUYRT,0)		, NVL(@CASH_SELLRT,0)		  , NVL(@WIRE_SEND_EXRT,0)	, NVL(@WIRE_RECV_EXRT,0)		  , NVL(@EXCH_BASERT,0)		  , NVL(@USD_CONV_RT,0)		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	 	, UFN_DATE_FORMAT('TIME')		  , '@USR_ID'			, UFN_DATE_FORMAT('DATE')	    , UFN_DATE_FORMAT('TIME')		  ) ;		  END ;
#MdmExrateMgt_v1@Search
--MdmExrateMgt_v1@SearchSELECT CURR_CD     , CURR_UNIT     , CASH_BUYRT     , CASH_SELLRT	 , WIRE_SEND_EXRT     , WIRE_RECV_EXRT     , EXCH_BASERT     , USD_CONV_RT     , RMK     , SEQ  FROM MDM_EX_RATE2 WHERE OFFICE_CD = '@OFFICE_CD'   AND EXRT_YMD = '@S_EXRT_YMD'   AND SEQ = LPAD('@SEQ', 3, '0') ORDER BY CURR_CD
#MdmExrateMgt_v1@SearchMonthly
-- MdmExrateMgt_v1@SearchMonthlySELECT OFFICE_CD     , BASE_CURR     , CURR_CD     , EXRT_MM     , CURR_UNIT     , CASH_BUYRT     , CASH_SELLRT     , WIRE_SEND_EXRT     , WIRE_RECV_EXRT     , EXCH_BASERT     , USD_CONV_RT     , UPD_USR     , UPD_YMD     , UPD_HM  FROM MDM_MM_EX_RATE WHERE OFFICE_CD = '@OFFICE_CD'   AND BASE_CURR = '@BASE_CURR'   AND EXRT_MM = '@EXRT_MM' ORDER BY CURR_CD   
#MdmExrateMgt_v1@Update
--MdmExrateMgt_v1@UpdateUPDATE MDM_EX_RATE    SET CURR_UNIT		= '@CURR_UNIT'     , CASH_BUYRT		= @CASH_BUYRT     , CASH_SELLRT		= @CASH_SELLRT     , WIRE_SEND_EXRT	= @WIRE_SEND_EXRT     , WIRE_RECV_EXRT	= @WIRE_RECV_EXRT     , EXCH_BASERT		= @EXCH_BASERT     , USD_CONV_RT		= @USD_CONV_RT     , RMK              = '@RMK'     , UPD_USR			= '@USR_ID'     , UPD_YMD			= UFN_DATE_FORMAT('DATE')     , UPD_HM			= UFN_DATE_FORMAT('TIME')WHERE  OFFICE_CD 		= '@OFFICE_CD'  AND  BASE_CURR 		= '@BASE_CURR'  AND  CURR_CD 			= '@CURR_CD'  AND  EXRT_YMD 		= '@EXRT_YMD'
#MdmExrateMgt_v1@Update2
--MdmExrateMgt_v1@Update2UPDATE MDM_EX_RATE2    SET CURR_UNIT		= '@CURR_UNIT'     , CASH_BUYRT		= @CASH_BUYRT     , CASH_SELLRT		= @CASH_SELLRT     , WIRE_SEND_EXRT	= @WIRE_SEND_EXRT     , WIRE_RECV_EXRT	= @WIRE_RECV_EXRT     , EXCH_BASERT		= @EXCH_BASERT     , USD_CONV_RT		= @USD_CONV_RT     , RMK              = '@RMK'     , UPD_USR			= '@USR_ID'     , UPD_YMD			= UFN_DATE_FORMAT('DATE')     , UPD_HM			= UFN_DATE_FORMAT('TIME')WHERE  OFFICE_CD 		= '@OFFICE_CD'  AND  BASE_CURR 		= '@BASE_CURR'  AND  CURR_CD 			= '@CURR_CD'  AND  EXRT_YMD 		= '@EXRT_YMD'  AND  SEQ				= LPAD('@SEQ', 3, '0')
#MdmExrateMgt_v1@UpdateMonthly
-- MdmExrateMgt_v1@UpdateMonthlyUPDATE MDM_MM_EX_RATE    SET CURR_UNIT		= '@CURR_UNIT'     , CASH_BUYRT		= 'CASH_BUYRT     , CASH_SELLRT		= NVL(@CASH_SELLRT,0)     , WIRE_SEND_EXRT	= NVL(@WIRE_SEND_EXRT,0)     , WIRE_RECV_EXRT	= NVL(@WIRE_RECV_EXRT,0)     , EXCH_BASERT		= NVL(@EXCH_BASERT,0)     , USD_CONV_RT		= NVL(@USD_CONV_RT,0)     , UPD_USR			= '@USR_ID'     , UPD_YMD			= UFN_DATE_FORMAT('DATE')     , UPD_HM			= UFN_DATE_FORMAT('TIME')WHERE  OFFICE_CD 		= '@OFFICE_CD'  AND  BASE_CURR 		= '@BASE_CURR'  AND  CURR_CD 			= '@CURR_CD'  AND  EXRT_MM 		    = '@EXRT_MM'
